#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Examination
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Examination\EditExamination.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Examination/EditExamination.cshtml")]
    public partial class EditExamination : System.Web.Mvc.WebViewPage<LiXinModels.Examination.DBModel.tbExamination>
    {
        public EditExamination()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Examination\EditExamination.cshtml"
  
    ViewBag.Title = NavigateMenuLanguage.EditExamination;


            
            #line default
            #line hidden
WriteLiteral("<div class=\"main-c\">\r\n    ");


            
            #line 7 "..\..\Views\Examination\EditExamination.cshtml"
Write(Html.Action("SiteMapLink", "Common", new {linkName = "EditExamination"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <form id=\"fro_EditExamination\">\r\n        <input type=\"hidden\" name=\"_id\" id" +
"=\"txt_id\" value=\"");


            
            #line 9 "..\..\Views\Examination\EditExamination.cshtml"
                                                      Write(Model._id);

            
            #line default
            #line hidden
WriteLiteral(@""" />
        <h3 class=""tit-h3"">考试基本信息</h3>
        <table class=""tab-Form mt10"">
            <tr>
                <td class=""Tit span10""><span class=""must"" title=""必填项"">*</span>考试名称：</td>
                <td><input type=""text"" class=""span30"" name=""ExaminationTitle"" value=""");


            
            #line 14 "..\..\Views\Examination\EditExamination.cshtml"
                                                                                Write(Model.ExaminationTitle);

            
            #line default
            #line hidden
WriteLiteral("\" id=\"txtExaminationTitle\" /></td>\r\n            </tr>\r\n            <tr>\r\n        " +
"        <td class=\"Tit\"><span class=\"must\" title=\"必填项\">*</span>考试时长：</td>\r\n     " +
"           <td><input type=\"text\" class=\"span6\" name=\"ExamLength\" maxlength=\"3\" " +
"value=\"");


            
            #line 18 "..\..\Views\Examination\EditExamination.cshtml"
                                                                                       Write(Model.ExamLength);

            
            #line default
            #line hidden
WriteLiteral("\" id=\"txt_ExamLength\" /> 分钟</td>\r\n            </tr>\r\n            <tr>\r\n          " +
"      <td class=\"Tit\"><span class=\"must\" title=\"必填项\">*</span>考试次数：</td>\r\n       " +
"         <td><input type=\"text\" class=\"span6\" name=\"TestTimes\" value=\"");


            
            #line 22 "..\..\Views\Examination\EditExamination.cshtml"
                                                                        Write(Model.TestTimes);

            
            #line default
            #line hidden
WriteLiteral("\" id=\"txt_TestTimes\" /></td>\r\n            </tr>\r\n            <tr>\r\n              " +
"  <td class=\"Tit\"><span class=\"must\" title=\"必填项\">*</span>通过分数：</td>\r\n           " +
"     <td>试卷总分的 <input type=\"text\" class=\"span6\" name=\"PassScore\" value=\"");


            
            #line 26 "..\..\Views\Examination\EditExamination.cshtml"
                                                                              Write(Model.PassScore);

            
            #line default
            #line hidden
WriteLiteral(@""" id=""txt_PassScore""  /> %</td>
            </tr>
            <tr>
                <td class=""Tit""><span class=""must"" title=""必填项"">*</span>考试时间：</td>
                <td>
                    <div class=""time-choose"">
                        <input type=""text"" readonly=""readonly"" onclick="" WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm', maxDate: '#F{$dp.$D(\'txt_ExamEndTime\',{m:-1})}' }) "" name=""ExamBeginTime"" id=""txt_ExamBeginTime"" value=""");


            
            #line 32 "..\..\Views\Examination\EditExamination.cshtml"
                                                                                                                                                                                                                          Write(Model.ExamBeginTime > DateTime.MinValue ? Model.ExamBeginTime.ToString("yyyy-MM-dd HH:mm") : "");

            
            #line default
            #line hidden
WriteLiteral(@"""/>
                        <i></i>
                    </div>
                    至 
                    <div class=""time-choose"">
                        <input type=""text"" name=""ExamEndTime"" readonly=""readonly"" onclick="" WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm', minDate: '#F{$dp.$D(\'txt_ExamBeginTime\',{m:1})}' }) "" id=""txt_ExamEndTime"" value=""");


            
            #line 37 "..\..\Views\Examination\EditExamination.cshtml"
                                                                                                                                                                                                                       Write(Model.ExamEndTime > DateTime.MinValue ? Model.ExamEndTime.ToString("yyyy-MM-dd HH:mm") : "");

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                        <i></i>\r\n                    </div>\r\n               " +
" </td>\r\n            </tr>\r\n            <tr>\r\n                <td class=\"Tit\">试卷顺" +
"序：</td>\r\n                <td>\r\n                    <div class=\"sel\">\r\n          " +
"              <input type=\"radio\" name=\"RadomOrderFlag\" value=\"0\" id=\"txt_RadomO" +
"rderFlag0\" /><label>固定排序</label>\r\n                        <input type=\"radio\" na" +
"me=\"RadomOrderFlag\" value=\"1\" id=\"txt_RadomOrderFlag1\" /><label>随机排序</label>\r\n  " +
"                  </div>\r\n                </td>\r\n            </tr>\r\n            " +
"<tr>\r\n                <td class=\"Tit\">显示模式：</td>\r\n                <td>\r\n        " +
"            <div class=\"sel\">\r\n                        <input type=\"radio\" name=" +
"\"ShowType\" value=\"0\" id=\"txt_ShowType0\" /><label>整卷显示</label>\r\n                 " +
"       <input type=\"radio\" name=\"ShowType\" value=\"1\" id=\"txt_ShowType1\" /><label" +
">单题可逆</label>\r\n                        <input type=\"radio\" name=\"ShowType\" value" +
"=\"2\" id=\"txt_ShowType2\" /><label>单题不可逆</label>\r\n                    </div>\r\n    " +
"            </td>\r\n            </tr>\r\n            <tr>\r\n                <td clas" +
"s=\"Tit\">是否百分制：</td>\r\n                <td>\r\n                    <div class=\"sel\">" +
"\r\n                        <input type=\"radio\" name=\"PercentFlag\" value=\"0\" id=\"t" +
"xt_PercentFlag0\" /><label>是</label>\r\n                        <input type=\"radio\"" +
" name=\"PercentFlag\" value=\"1\" id=\"txt_PercentFlag1\" /><label>否</label>\r\n        " +
"            </div>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n" +
"                <td class=\"Tit\">选择试卷：</td>\r\n                <td>\r\n              " +
"      <input type=\"button\" id=\"btnChoosePaper\" class=\"btn btn-co\" value=\"选择试卷\" o" +
"nclick=\" choosePaper() \" />\r\n                    <input name=\"PaperID\" type=\"hid" +
"den\" style=\"display: none\"  id=\"hid_PaperId\" value=\"");


            
            #line 74 "..\..\Views\Examination\EditExamination.cshtml"
                                                                                                  Write(Model.PaperID);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                    <div id=\"lbl_PaperName\">");


            
            #line 75 "..\..\Views\Examination\EditExamination.cshtml"
                                        Write(ViewBag.PaperName);

            
            #line default
            #line hidden
WriteLiteral(@"</div>
                </td>
            </tr>
            <tr>
                <td class=""Tit"">批阅人信息：</td>
                <td>
                    <input type=""button"" id=""btnChooseApprovalUser"" value=""选择批阅人""  class=""btn btn-co"" />
                    <input name=""ApprovalUser"" id=""ApprovalUserIds"" type=""hidden"" value=""");


            
            #line 82 "..\..\Views\Examination\EditExamination.cshtml"
                                                                                    Write(ViewBag.ApprovalUserIds);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                    <div id=\"AUser\"></div>\r\n                </td>\r\n        " +
"    </tr>\r\n        </table>\r\n        <h3 class=\"tit-h3 mt20\">\r\n            参考人信息" +
"\r\n        </h3>\r\n        <div>");


            
            #line 90 "..\..\Views\Examination\EditExamination.cshtml"
        Write(Html.Action("AuthorizedExam", "Examination", new {examinationId = @Model._id}));

            
            #line default
            #line hidden
WriteLiteral(@"</div>
        <center class =""mt10"">
            <a name=""btnSave"" title=""保存"" id=""btnSave"" onclick="" SaveExam() "" class=""btn"">保存</a>
            <input  type=""hidden"" name=""PublishedFlag"" id=""txt_PublishedFlag"" />
            <a title=""发布"" id=""btnPublish"" name=""btnPublish"" onclick=""PublishedExam()"" class=""btn"">发布</a>
            <a title=""返回"" id=""btnBack"" name=""back"" onclick="" fnback() "" class=""btn btn-cancel"">返回</a>
        </center>
    </form>
</div>

<script type=""text/javascript"">
    $(document).ready(
        function() {
            //编辑时，数据初始化radio
            $(""input[name=RadomOrderFlag][value='");


            
            #line 104 "..\..\Views\Examination\EditExamination.cshtml"
                                            Write(Model.RadomOrderFlag);

            
            #line default
            #line hidden
WriteLiteral("\']\").attr(\"checked\", true);\r\n            $(\"input[name=ShowType][value=\'");


            
            #line 105 "..\..\Views\Examination\EditExamination.cshtml"
                                      Write(Model.ShowType);

            
            #line default
            #line hidden
WriteLiteral("\']\").attr(\"checked\", true);\r\n            $(\"input[name=PercentFlag][value=\'");


            
            #line 106 "..\..\Views\Examination\EditExamination.cshtml"
                                         Write(Model.PercentFlag);

            
            #line default
            #line hidden
WriteLiteral("\']\").attr(\"checked\", true);\r\n            //客户端数据验证\r\n            $(\"#fro_EditExami" +
"nation\").validate(\r\n                {\r\n                    submitHandler: submit" +
"Exam,\r\n                    event: \"blur\",\r\n                    rules: {\r\n       " +
"                 ExaminationTitle: {\r\n                            required: true" +
",\r\n                            maxlength: 30,\r\n                            remot" +
"e: {\r\n                                type: \"post\",\r\n                           " +
"     dataType: \"json\",\r\n                                url: \"/Examination/IsExi" +
"stExaminationTitle?t=\" + new Date(),\r\n                                data: {\r\n " +
"                                   ExamTitle: function() { return $(\"#txtExamina" +
"tionTitle\").val(); },\r\n                                    id: function() { retu" +
"rn $(\"#txt_id\").val(); }\r\n                                }\r\n                   " +
"         }\r\n                        },\r\n                        ExamLength: { re" +
"quired: true, min: 1, digits: true },\r\n                        TestTimes: { requ" +
"ired: true, min: 1, range: [1, 100], digits: true },\r\n                        Pa" +
"ssScore: { required: true, range: [1, 100], digits: true },\r\n                   " +
"     ExamEndTime: \"ExamEndTime\",\r\n                        ExamBeginTime: { requi" +
"red: true },\r\n                        ExamEndTime: { required: true },\r\n        " +
"                ApprovalUser: { required: true },\r\n                        Paper" +
"ID: { required: true, min: 1 }\r\n                    },\r\n                    mess" +
"ages: {\r\n                        ExaminationTitle: {\r\n                          " +
"  required: \"考试名称不能为空！\",\r\n                            remote: \"考试名称已经存在！\",\r\n    " +
"                        maxlength: \"考试名称不能超过30个字符！\"\r\n                        },\r" +
"\n                        ExamLength: { required: \"请输入考试时长！\", min: \"考试时长在1~999之间！" +
"\", digits: \"考试时长在1~999之间！\" },\r\n                        TestTimes: { required: \"请" +
"输入考试次数！\", min: \"考试次数在1~100之间！\", range: \"考试次数在1~100之间！\", digits: \"考试次数必须为正整数！\" }," +
"\r\n                        PassScore: { required: \"请输入通过分数！\", range: \"通过分数在1~100之" +
"间！\", digits: \"通过分数必须为正整数！\" },\r\n                        ExamBeginTime: { required" +
": \"请选择开始时间！\" },\r\n                        ExamEndTime: { required: \"请选择结束时间！\" },\r" +
"\n                        ApprovalUser: { required: \"请选择批阅人！\" },\r\n               " +
"         PaperID: { required: \"请选择试卷！\", min: \"请选择试卷！\" }\r\n                    }\r\n" +
"                }\r\n            );\r\n\r\n            $(\"#btnChooseApprovalUser\").bin" +
"d(\"click\", function() {\r\n                $(\"#AllUserID\").val($(\"#ApprovalUserIds" +
"\").val());\r\n                $(\"#SelectUserFlag\").val(\"ApprovalUser\");\r\n\r\n       " +
"         art.dialog.load(\"/UserCommon/SelectUser\", { title: \"添加批阅人\", id: \"SelUse" +
"r\"});\r\n            });\r\n            AddApprovalUser();\r\n        }\r\n    );\r\n\r\n\r\n " +
"   function choosePaper() {\r\n        art.dialog.load(\"/Exampaper/ExampaperSelect" +
"?selectType=radio\",{\r\n            title: \"选择试卷\",\r\n            id: \"SelExam\"\r\n   " +
"     });\r\n    }\r\n\r\n    function ExamIDList(str) {\r\n        $(\"#hid_PaperId\").val" +
"(str);\r\n        var paperName = $(\"#paper_\" + $(\'#hid_PaperId\').val());\r\n       " +
" var paperHtml = \"\";\r\n        paperHtml += \"<div class=\'seled-list\'><h4 style=\'m" +
"argin-top:5px;float:left;\'>已选择试卷：</h4><ul>\";\r\n        paperHtml += \"<li id=\'sp_p" +
"aperName\' class=\'ovh\'>\" + paperName.html() + \" <a class=\'btn btn-cancel\' onclick" +
"=\'removeRelPaper()\'>X</a></li>\";\r\n        paperHtml += \"</ul></div>\";\r\n        $" +
"(\"#lbl_PaperName\").html(paperHtml);\r\n        art.dialog.list[\'SelExam\'].close();" +
"\r\n    }\r\n\r\n    function submitExam(form) {\r\n        if ($(\"#txt_PublishedFlag\")." +
"val() == 1) {\r\n            if ($(\"#personids\").val().length == 0) {\r\n           " +
"     //art.dialog({ content: \"发布考试必须有考生参加！\", time: 3 });\r\n                art.di" +
"alog.tips(\"发布考试必须有考生参加\", 3);\r\n                return;\r\n            }\r\n\r\n        " +
"    art.dialog({\r\n                content: \'考试发布之后不可修改，确认发布吗？\',\r\n               " +
" ok: function () {\r\n                    $(\"#btnSave\").removeAttr(\"onclick\");\r\n  " +
"                  $(\"#btnPublish\").removeAttr(\"onclick\");\r\n                    \r" +
"\n                    $.post(\"/Examination/SubmitEditExamination?personIds=\" + $(" +
"\"#personids\").val() + \"&ApprovalUser=\" + $(\"#ApprovalUserIds\").val(), $(\"#fro_Ed" +
"itExamination\").formSerialize(), function (data) {\r\n                        \r\n  " +
"                      art.dialog.tips(data.content, 3, function () {\r\n          " +
"                  if (data.result == 1) {\r\n                                windo" +
"w.location.href = \'/Examination/ExaminationList\';\r\n                            }" +
"\r\n                            else {\r\n                                $(\"#btnSav" +
"e\").attr(\"onclick\", \"SaveExam()\");\r\n                                $(\"#btnPubli" +
"sh\").attr(\"onclick\", \"PublishedExam()\");\r\n                            }\r\n       " +
"                 });\r\n                    });\r\n                    return true;\r" +
"\n                },\r\n                cancelVal: \'关闭\',\r\n                cancel: t" +
"rue //为true等价于function(){}\r\n            });\r\n        } else {\r\n            $(\"#b" +
"tnSave\").removeAttr(\"onclick\");\r\n            $(\"#btnPublish\").removeAttr(\"onclic" +
"k\");\r\n            $.post(\"/Examination/SubmitEditExamination?personIds=\" + $(\"#p" +
"ersonids\").val() + \"&ApprovalUser=\" + $(\"#ApprovalUserIds\").val(), $(\"#fro_EditE" +
"xamination\").formSerialize(), function(data) {\r\n                \r\n              " +
"  art.dialog.tips(data.content, 3, function () {\r\n                    $(\"#txt_id" +
"\").val(data.examId);\r\n                    if (data.result == 1) {\r\n             " +
"           window.location.href = \'/Examination/ExaminationList\';\r\n\r\n           " +
"         }\r\n                    else {\r\n                        $(\"#btnSave\").at" +
"tr(\"onclick\", \"SaveExam()\");\r\n                        $(\"#btnPublish\").attr(\"onc" +
"lick\", \"PublishedExam()\");\r\n                    }\r\n                });\r\n        " +
"    });\r\n        }\r\n    }\r\n\r\n    function PublishedExam() {\r\n        $(\"#txt_Pub" +
"lishedFlag\").val(1);\r\n        $(\"#fro_EditExamination\").submit();\r\n    }\r\n\r\n    " +
"function SaveExam() {\r\n        $(\"#txt_PublishedFlag\").val(0);\r\n        $(\"#fro_" +
"EditExamination\").submit();\r\n    }\r\n\r\n    function AddApprovalUser() {\r\n        " +
"$(\"#AUser\").html(\"\");\r\n        $.getJSON(\"/Examination/GetUserByIds\", { ids: $(\"" +
"#ApprovalUserIds\").val() }, function (data) {\r\n            var html = \"\";\r\n     " +
"       if (data.data.length > 0) {\r\n                html += \"<div class=\'seled-l" +
"ist\'><h4>已选择批阅人：</h4><ul>\";\r\n                for (var i = 0; i < data.data.lengt" +
"h; i++) {\r\n                    var tagId = \"Tag_\" + data.data[i].UserId;\r\n      " +
"              //$(\"#AUser\").prepend(\'<li id=\' + tagId + \'><span title=\' + data.d" +
"ata[i].Realname + \'>\' + data.data[i].Realname + \'</span><a class=\"btn btn-cancel" +
"\" onclick=\"removeApprovalUser(\\\'\' + data.data[i].UserId + \'\\\')\">X</a></li>\');\r\n " +
"                   html += \"<li id=\'\" + tagId + \"\'><span title=\'\" + data.data[i]" +
".Realname + \"\' >\" + data.data[i].Realname + \"</span><a onclick=\'removeApprovalUs" +
"er(\" + data.data[i].UserId + \")\' class=\'btn btn-cancel\'>X</a></li>\";\r\n          " +
"      }\r\n                html += \"</ul></div>\";\r\n\r\n                $(\"#AUser\").p" +
"repend(html);\r\n            }\r\n            $(\"#ApprovalUserIds\").val(data.ids);\r\n" +
"        });\r\n    }\r\n\r\n    function removeApprovalUser(tagId) {\r\n        $(\"#Tag_" +
"\" + tagId).remove();\r\n        var tagArray = [];\r\n        tagArray = $(\"#Approva" +
"lUserIds\").val().split(\",\");\r\n        $.arrayRemove(tagArray, tagId);\r\n        $" +
"(\"#ApprovalUserIds\").val(tagArray.join(\",\"));\r\n    }\r\n\r\n    function removeRelPa" +
"per() {\r\n        $(\"#sp_paperName\").html(\"\");\r\n        $(\'#hid_PaperId\').val(0);" +
"\r\n    }\r\n\r\n    function fnback() {\r\n        window.location.href = \'/Examination" +
"/ExaminationList\';\r\n    }\r\n</script>");


        }
    }
}
#pragma warning restore 1591
