
INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2014, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2015, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2016, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2017, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2018, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估',1, 0, NULL, 0.5, NULL, 0, '4', '', 2019, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2020, getdate(), 0, 2)
  INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2021, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2022, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估', 1, 0, NULL, 0.5, NULL, 0, '4', '', 2023, getdate(), 0, 2)
 INSERT INTO dbo.Free_OtherApplyConfig (ApplyContent, ConvertType, ConvertBase, ConvertBaseInfo, ConvertBaseTo, UploadTip, ConvertMax, TrainGradeScore, Memo, year, CreateTime, IsDelete, ApplyType)
VALUES ('集中授课及视频课程课后评估',1, 0, NULL, 0.5, NULL, 0, '4', '', 2024, getdate(), 0, 2)