//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Question {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Question() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiXinLanguage.Examination.Question", typeof(Question).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 考试管理 的本地化字符串。
        /// </summary>
        public static string Question_ExamManage {
            get {
                return ResourceManager.GetString("Question_ExamManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加附件 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_AddFiles {
            get {
                return ResourceManager.GetString("Question_QuestionManage_AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加选项 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_AddItemAnswer {
            get {
                return ResourceManager.GetString("Question_QuestionManage_AddItemAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增试题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_AddQuestion {
            get {
                return ResourceManager.GetString("Question_QuestionManage_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加正确答案 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_AddRightAnswer {
            get {
                return ResourceManager.GetString("Question_QuestionManage_AddRightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加题库 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_AddSort {
            get {
                return ResourceManager.GetString("Question_QuestionManage_AddSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览试题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_BrowseQuestion {
            get {
                return ResourceManager.GetString("Question_QuestionManage_BrowseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （点击‘添加正确答案’按钮添加正确答案） 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_BtnAddRightAnswer {
            get {
                return ResourceManager.GetString("Question_QuestionManage_BtnAddRightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_CommonLevel {
            get {
                return ResourceManager.GetString("Question_QuestionManage_CommonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除试题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_DeleteQuestion {
            get {
                return ResourceManager.GetString("Question_QuestionManage_DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除题库 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_DeleteSort {
            get {
                return ResourceManager.GetString("Question_QuestionManage_DeleteSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_EasyLevel {
            get {
                return ResourceManager.GetString("Question_QuestionManage_EasyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Failed {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入的数据模板内容不正确 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FileDataWrong {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FileDataWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传附件不可以为空 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FileNotNull {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FileNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题附件 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Files {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音频 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FileType_Audio {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FileType_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FileType_Picture {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FileType_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FileType_Vidio {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FileType_Vidio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填空题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FillBlank {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FillBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要加填空的地方请输入 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_FillBlankTip {
            get {
                return ResourceManager.GetString("Question_QuestionManage_FillBlankTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 难 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_HardLevel {
            get {
                return ResourceManager.GetString("Question_QuestionManage_HardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入试题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ImportQuestion {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ImportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题选项 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ItemAnswer {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ItemAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项内容 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ItemContent {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项内容不可以为空 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ItemContentNotNull {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ItemContentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题最多可以26个选项 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ItemCountLimit {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ItemCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 判断题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Judge {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题难度 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Level {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题管理 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Manage {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多媒体题型至少有一个附件 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_MediaFileLimit {
            get {
                return ResourceManager.GetString("Question_QuestionManage_MediaFileLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 情景题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Mediea {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Mediea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改题库 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ModifySort {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ModifySort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Mulitple {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Mulitple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题至少有2个选项 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_MustOneItem {
            get {
                return ResourceManager.GetString("Question_QuestionManage_MustOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题必须有一个正确选项 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_MustOneRightItem {
            get {
                return ResourceManager.GetString("Question_QuestionManage_MustOneRightItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题答案不可以为空 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QueationAnswerNotNull {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QueationAnswerNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题题干不可以为空 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QueationContentNotNull {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QueationContentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题基本信息 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QuestionBaseInformation {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QuestionBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题题干 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QuestionContent {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题编辑 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QuestionEdit {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QuestionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题形式 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QuestionFormat {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QuestionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题模板 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_QuestionTemplete {
            get {
                return ResourceManager.GetString("Question_QuestionManage_QuestionTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正确 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Right {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正确答案 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_RightAnswer {
            get {
                return ResourceManager.GetString("Question_QuestionManage_RightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项： 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_SelectItem {
            get {
                return ResourceManager.GetString("Question_QuestionManage_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择题库 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_SelectSort {
            get {
                return ResourceManager.GetString("Question_QuestionManage_SelectSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Single {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属题库 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Sort {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问答题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Subject {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题模板不符合要求 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_TempleteFormat {
            get {
                return ResourceManager.GetString("Question_QuestionManage_TempleteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入正确的查询时间 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_TimeLimit {
            get {
                return ResourceManager.GetString("Question_QuestionManage_TimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填空的个数与答案的个数不符合 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_BlankNumberIsOK {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_BlankNumberIsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传文件的个数在5个以内 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_FileCountLimit {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_FileCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式错误 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_FileFormat {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传格式：MP3 大小在8M以内 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_FileType_AudioFormat {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_FileType_AudioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传格式：jpg、png大小在500K以内 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_FileType_PictureFormat {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_FileType_PictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传格式：wmv 大小在8M以内 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_FileType_VidioFormat {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_FileType_VidioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择试题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_SelectQuestion {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_SelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择题库 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Tip_SelectSort {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Tip_SelectSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共成功导入 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_TotalImport {
            get {
                return ResourceManager.GetString("Question_QuestionManage_TotalImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题题型 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Type {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建者 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_UpLoader {
            get {
                return ResourceManager.GetString("Question_QuestionManage_UpLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_UpLoadTime {
            get {
                return ResourceManager.GetString("Question_QuestionManage_UpLoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要预览的试题 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_ViewQuestion {
            get {
                return ResourceManager.GetString("Question_QuestionManage_ViewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用次数 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_VoidTimes {
            get {
                return ResourceManager.GetString("Question_QuestionManage_VoidTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_Wrong {
            get {
                return ResourceManager.GetString("Question_QuestionManage_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的行为 的本地化字符串。
        /// </summary>
        public static string Question_QuestionManage_WrongRow {
            get {
                return ResourceManager.GetString("Question_QuestionManage_WrongRow", resourceCulture);
            }
        }
    }
}
