#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Exampaper
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Exampaper\ExampaperList.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Exampaper/ExampaperList.cshtml")]
    public class ExampaperList : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExampaperList()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Exampaper\ExampaperList.cshtml"
  
    ViewBag.Title = NavigateMenuLanguage.ExampaperManage;
    Layout = "~/Views/Shared/_Layout.cshtml";
    string sortID = Request.QueryString["sortID"] ?? "0";


            
            #line default
            #line hidden
WriteLiteral("<script src=\"");


            
            #line 7 "..\..\Views\Exampaper\ExampaperList.cshtml"
        Write(Url.Content("~/Scripts/jquery.contextmenu.r2.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"> </script>\r\n<input type=\"hidden\" id=\"selExampaperSort\" v" +
"alue=\"");


            
            #line 8 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                             Write(sortID);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n<div id=\"contentInfor\" class=\"main-c\">\r\n    ");


            
            #line 10 "..\..\Views\Exampaper\ExampaperList.cshtml"
Write(Html.Action("SiteMapLink", "Common", new {linkName = "ExampaperManage"}));

            
            #line default
            #line hidden
WriteLiteral(@"
    <div class=""clb"">
        <div class=""fl span20"">
            <div class=""menu-list"">
                <h3>试卷分类<i class=""il""></i><i class=""ir""></i></h3>
                <div class=""list-con""><div class=""list-do"" style=""padding-bottom: 5px;"">
                    <input type=""button"" id=""btnAddExampaperSort"" value=""");


            
            #line 16 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                    Write(Exampaper.ExampaperSort_Add);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-co\"/>\r\n                    <input type=\"button\" id=\"btnModifyExa" +
"mpaperSort\" value=\"");


            
            #line 17 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                       Write(Exampaper.ExampaperSort_Modify);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn btn-co\"/>\r\n                    <input type=\"button\" id=\"btnDeleteExa" +
"mpaperSort\" value=\"");


            
            #line 18 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                       Write(Exampaper.ExampaperSortDelete);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""btn btn-cancel""/>
                </div></div>
            </div>
            <div class=""treeview-box""><div id=""sortList"" class=""tree-list""></div></div>
        </div>
        <div class=""fr span79"">
            <div id=""Search"" class=""so-set"">
                <table class=""tab-Form"">
                    <tr>
                        <td class=""Tit span6"">");


            
            #line 27 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                         Write(Exampaper.ExampaperTitle);

            
            #line default
            #line hidden
WriteLiteral(@"：</td><td class=""span21"">
                            <input type=""text"" class=""span20 searchclass"" id=""tbPaperTitle"" value=""请输入搜索内容"" info="""" /></td>
                        <td class=""Tit span5"">创建者：</td><td><input type=""text"" class=""span10 searchclass"" id=""tbuser"" value=""请输入搜索内容"" info="""" /></td>
                        <td class=""so-do"">
                            <input type=""button"" class=""btn"" id=""ibtnSearch"" name=""搜索"" value=""搜索"" />
                            <a id=""btnadd"" class=""btn btn-co"">");


            
            #line 32 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                         Write(Exampaper.ExampaperAdd);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                        </td>
                    </tr>
                </table>
            </div>
            <div class=""so-seq"">
                <select id=""selExamType"" onchange=""ExamTypeChange(); "">
                    <option value=""3"">试卷类型</option>
                    <option value=""0"">普通</option>
                    <option value=""1"">随机</option>
                </select>
                ");



WriteLiteral("\r\n                <div class=\"list-do\"><a id=\"btndelete\">");


            
            #line 46 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                  Write(Exampaper.ExampaperDelete);

            
            #line default
            #line hidden
WriteLiteral(@"</a></div>
            </div>
            <div id=""Content"">
                <table class=""tab-List mt10"">
                    <thead>
                        <tr>
                            <th class=""span4""><input type=""checkbox"" id=""selectExampaperall"" /></th>
                            <th>试卷名称</th>
                            <th>题型(数量)</th>
                            <th class=""span8"">发布时间</th>
                            <th class=""span6"">操作</th>
                        </tr>
                    </thead>
                    <tbody id=""ExampaperList""></tbody>
                    <tfoot></tfoot>
                </table>
                ");



WriteLiteral(@"
            </div>
        </div>
    </div>
    <div id=""openUrl"" style=""display: none;""></div>
</div>
<div class=""clear""></div>
<script id=""ExampaperListTemplate"" type=""text/x-jsrender"">
    {{for #data}}
     <tr>
        <td><input id=""{{:id}}"" type=""checkbox"" name=""checkExam"" value=""{{:id}}"" /></td>
        <td>
            <div class=""tl"">
                <p title=""{{:ExampaperTitle}}""><strong>{{:ExampaperTitle.length>15?(ExampaperTitle.substring(0,15)+""…""):ExampaperTitle}}</strong></p>
                <p class=""Info""><strong>{{:Creater}}</strong> 发布<i>|</i>试卷库：<span title=""{{:ExamSortTitle}}"">{{:ExamSortTitle.length>8?(ExamSortTitle.substring(0,8)+""…""):ExamSortTitle}}</span><i>|</i>{{:ExamType}}</p>
            </div>
         </td>
         <td><div class=""tl"">{{:QuestionTypeList}}</div></td>
         <td>{{:LastUpdateTime}}</td>
         <td>
            <a onclick=""Modify({{:id}},{{:ExamSortID}});"" title=""编辑"" class=""icon iedit""></a>
            <a onclick=""Detail({{:id}},{{:ExamSortID}});"" title=""查看详情"" class=""icon iview""></a>
         </td>
      </tr>
    {{/for}}
</script>
");



WriteLiteral("\r\n<script type=\"text/javascript\">\r\n    //初始化试卷库\r\n    function initExampaperSort()" +
" {\r\n        $.getJSON(\"/Exampaper/GetAllExampaperSort?t=\" + new Date(), function" +
"(data) {\r\n            $(\"#sortList\").html(data);\r\n            //树的显示\r\n          " +
"  $(\"#navigation\").treeview({\r\n                persist: \"location\",\r\n           " +
"     collapsed: false,\r\n                unique: false\r\n            });\r\n        " +
"    $(\"#navigation>li>ul>li>div\").each(function () {\r\n                $(this).cl" +
"ick();\r\n            });\r\n        });\r\n    }\r\n    //试卷库树点击事件\r\n    function select" +
"Sort(id,obj) {\r\n        $(\"#selExampaperSort\").val(id);\r\n        postNodeClickSe" +
"lect(obj);\r\n        InitializeTargetList(getUrlParms());\r\n    }\r\n    function po" +
"stNodeClickSelect(obj) {\r\n        $(\"#sortList\").find(\"a\").each(function () {\r\n " +
"           $(this).removeClass(\"On\");\r\n        });\r\n        $(obj).addClass(\"On\"" +
");\r\n    }\r\n    //显示所有试卷\r\n\r\n    function InitializeTargetList(url) {\r\n        var" +
" templateId = \'\';\r\n//        if ($(\".listOn\").length > 0) {\r\n//            $(\"#E" +
"xampaperList\").addClass(\"Wordlist\").removeClass(\"Piclist\");\r\n//            templ" +
"ateId = \'ExampaperListTemplate\';\r\n//        } else {\r\n//            $(\"#Exampape" +
"rList\").addClass(\"Piclist\").removeClass(\"Wordlist\");\r\n//            templateId =" +
" \'ExampaperBlockTemlpate\';\r\n//        }\r\n        $(\"#ExampaperList\").JsRenderDat" +
"a({\r\n            sourceUrl: url,\r\n            isPage: true,\r\n            pageSiz" +
"e: 10,\r\n            pageIndex: 1,\r\n            templateID: \'ExampaperListTemplat" +
"e\',\r\n//            templateID: templateId,\r\n            funCallback: function() " +
"{\r\n                SetCheckBox(\"selectExampaperall\", \"ExampaperList\");\r\n        " +
"        $(\"#selectExampaperall\").removeAttr(\"checked\");\r\n            }\r\n        " +
"});\r\n\r\n    }\r\n\r\n    function getUrlParms() {\r\n        return \'/Exampaper/GetAllE" +
"xampaperList?type=1&eSortID=\' + $(\"#selExampaperSort\").val() + \'&eTitle=\' + esca" +
"pe(getSearchWord(\"tbPaperTitle\")) + \'&eUser=\' + escape(getSearchWord(\"tbuser\")) " +
"+ \'&eExamType=\' + $(\"#selExamType\").val() + \'&t=\' + new Date();\r\n    }\r\n\r\n    $(" +
"document).ready(function () {\r\n        //初始化查询条件\r\n        initSearch();\r\n       " +
" //初始化试卷库\r\n        initExampaperSort();\r\n        //初始化列表\r\n        InitializeTarg" +
"etList(getUrlParms());\r\n\r\n        //新增库\r\n        $(\"#btnAddExampaperSort\").bind(" +
"\"click\", function () {\r\n            art.dialog.load(\"/Exampaper/ExampaperSortEdi" +
"t?id=0&fatherID=\" + $(\"#selExampaperSort\").val() + \"&t=\" + new Date(), { title: " +
"\"");


            
            #line 180 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                                                                                    Write(Exampaper.ExampaperSort_Add);

            
            #line default
            #line hidden
WriteLiteral(@""", id: ""SortEdit"", width: 500, height: 250 });
        });

        //修改库
        $(""#btnModifyExampaperSort"").bind(""click"", function () {
            if ($(""#selExampaperSort"").val() != ""0"") {
                art.dialog.load(""/Exampaper/ExampaperSortEdit?id="" + $(""#selExampaperSort"").val() + ""&t="" + new Date(), { title: """);


            
            #line 186 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                                                                             Write(Exampaper.ExampaperSort_Modify);

            
            #line default
            #line hidden
WriteLiteral("\", id: \"SortEdit\", width: 500, height: 350 });\r\n            } else {\r\n           " +
"     art.dialog({ title: \'");


            
            #line 188 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: \"");


            
            #line 188 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                       Write(Exampaper.Prompt_One);

            
            #line default
            #line hidden
WriteLiteral(@""", width: 200, height: 50, fixed: true, lock: true, time: 3 });
            }
        });

        //删除库
        $(""#btnDeleteExampaperSort"").bind(""click"", function () {
            if ($(""#selExampaperSort"").val() != ""0"") {
                art.dialog({
                    title: """);


            
            #line 196 "..\..\Views\Exampaper\ExampaperList.cshtml"
                       Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    content: \"");


            
            #line 197 "..\..\Views\Exampaper\ExampaperList.cshtml"
                         Write(CommonLanguage.Common_Confirm_Delete);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    width: 300,\r\n                    okValue: \'");


            
            #line 199 "..\..\Views\Exampaper\ExampaperList.cshtml"
                         Write(CommonLanguage.Common_Sure);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                    cancelValue: \'");


            
            #line 200 "..\..\Views\Exampaper\ExampaperList.cshtml"
                             Write(CommonLanguage.Common_Cancel);

            
            #line default
            #line hidden
WriteLiteral(@"',
                    height: 50,
                    fixed: true,
                    lock: true,
                    ok: function () {
                        $.getJSON(""/Exampaper/DeleteExampaperSortByID?id="" + $(""#selExampaperSort"").val(), function (data) {
                            if (data.result == 1) {
                                art.dialog.tips(data.content, 1.5); 
                                //art.dialog({ title: '");


            
            #line 208 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, width: 300, height: 100, fixed: true, lock: true, time: 3 });
                                initExampaperSort();
                            } else {
                                art.dialog.tips(data.content, 1.5);
                                //art.dialog({ title: '");


            
            #line 212 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, width: 300, height: 100, fixed: true, lock: true, time: 3 });
                            }
                        });
                    },
                    cancel: function () {
                    }
                });
            } else {
                art.dialog.tips(""");


            
            #line 220 "..\..\Views\Exampaper\ExampaperList.cshtml"
                            Write(Exampaper.Prompt_One);

            
            #line default
            #line hidden
WriteLiteral("\", 1.5);\r\n                //art.dialog({ title: \'");


            
            #line 221 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: \"");


            
            #line 221 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                         Write(Exampaper.Prompt_One);

            
            #line default
            #line hidden
WriteLiteral(@""", width: 200, height: 50, fixed: true, lock: true, time: 3 });
            }
        });

        //新增试卷
        $(""#btnadd"").bind(""click"", function() {
            if ($(""#selExampaperSort"").val() != ""0"") {
                window.location.href = ""/Exampaper/ExampaperEdit?id=0&sortID="" + $(""#selExampaperSort"").val();
            } else {
                art.dialog.tips(""");


            
            #line 230 "..\..\Views\Exampaper\ExampaperList.cshtml"
                            Write(Exampaper.Prompt_One);

            
            #line default
            #line hidden
WriteLiteral("\", 1.5);\r\n                //art.dialog({ title: \'");


            
            #line 231 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: \"");


            
            #line 231 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                         Write(Exampaper.Prompt_One);

            
            #line default
            #line hidden
WriteLiteral(@""", width: 200, height: 50, fixed: true, lock: true, time: 3 });
            }
        });

        //删除试卷
        $(""#btndelete"").bind(""click"", function() {
            var flag = false;
            var check = document.getElementsByName(""checkExam"");
            var checkList = """";
            for (var i = 0; i < check.length; i++) {
                if (check[i].checked) {
                    checkList = checkList + check[i].value + "","";
                    flag = true;
                }
            }

            if (!flag) {
                art.dialog.tips(""");


            
            #line 248 "..\..\Views\Exampaper\ExampaperList.cshtml"
                            Write(Exampaper.Prompt_Two);

            
            #line default
            #line hidden
WriteLiteral("\", 1.5);\r\n                //art.dialog({ title: \'");


            
            #line 249 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: \"");


            
            #line 249 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                                         Write(Exampaper.Prompt_Two);

            
            #line default
            #line hidden
WriteLiteral("\", width: 200, height: 50, fixed: true, lock: true, time: 3 });\r\n                " +
"return false;\r\n            } else {\r\n                if (checkList != \"\") {\r\n   " +
"                 art.dialog({\r\n                        title: \"");


            
            #line 254 "..\..\Views\Exampaper\ExampaperList.cshtml"
                           Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        content: \'");


            
            #line 255 "..\..\Views\Exampaper\ExampaperList.cshtml"
                             Write(Exampaper.Prompt_Three);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                        width: 200,\r\n                        okValue: \'");


            
            #line 257 "..\..\Views\Exampaper\ExampaperList.cshtml"
                             Write(CommonLanguage.Common_Sure);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                        cancelValue: \'");


            
            #line 258 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                 Write(CommonLanguage.Common_Cancel);

            
            #line default
            #line hidden
WriteLiteral(@"',
                        height: 50,
                        fixed: true,
                        lock: true,
                        ok: function() {
                            $.getJSON(""/Exampaper/DeleteExampaer?IDlist="" + checkList, function(data) {
                                if (data.result == 1) {
                                    art.dialog.tips(data.content, 1.5);
                                    //art.dialog({ title: '");


            
            #line 266 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                      Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, width: 200, height: 50, fixed: true, lock: true, time: 3 });
                                    InitializeTargetList(getUrlParms());
                                } else {
                                    art.dialog.tips(data.content, 1.5);
                                    //art.dialog({ title: '");


            
            #line 270 "..\..\Views\Exampaper\ExampaperList.cshtml"
                                                      Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, width: 200, height: 50, fixed: true, lock: true, time: 3 });
                                }
                            });
                        },
                        cancel: function() {
                        }
                    });
                } else {
                    return false;
                }
            }
        });
        //查询
        $(""#ibtnSearch"").bind(""click"", function() {
            InitializeTargetList(getUrlParms());
        });
    });

    function ExamTypeChange() {
        InitializeTargetList(getUrlParms());
    }

//修改试卷

    function Modify(id, sid) {
        window.location.href = ""/Exampaper/ExampaperEdit?id="" + id + ""&sortID="" + sid + ""&selectSortID="" + $(""#selExampaperSort"").val();
    }

    //查看试卷

    function Detail(id, sid) {
        var openurl = ""/Exampaper/ExampaperDetail?type=1&id="" + id + ""&sortID="" + sid;
        art.dialog({
            title: """);


            
            #line 303 "..\..\Views\Exampaper\ExampaperList.cshtml"
               Write(Exampaper.ExampaerDetail);

            
            #line default
            #line hidden
WriteLiteral(@""",
            lock: true,
            fixed: true,
            width: 700,
            height: 450,
            time: false,
            content: '<div class=""tac mt20""><img src=""../Images/loading.gif"" alt=""loading""/></div>',
            close: function() {
                $('#popIframe').hide();
                $("".aui_content"").css({ ""height"": ""auto"", ""width"": ""auto"", ""overflow"": ""auto"" });
            }
        });
        $("".aui_content"").css({ ""height"": ""450px"", ""width"": ""700px"", ""overflow"": ""auto"" });
        $.get(openurl + ""&t="" + new Date(), function(data) {
            $("".aui_content"").html(data);
        });
    }
</script>");


        }
    }
}
#pragma warning restore 1591
