#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Exampaper
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Exampaper/ExampaperSelect.cshtml")]
    public class ExampaperSelect : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExampaperSelect()
        {
        }
        public override void Execute()
        {



WriteLiteral("\r\n");


            
            #line 12 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
  
   Layout = null;
   // Layout = "~/Views/Shared/_Layout.cshtml";
    string selectType = Request.QueryString["selectType"] ?? "checkbox"; //标志单选还是多选


            
            #line default
            #line hidden
WriteLiteral("<link rel=\"Stylesheet\" href=\"");


            
            #line 17 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                        Write(Url.Content("~/CSS/jquery.treeview.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" />\r\n<style type=\"text/css\">\r\n    .hide { display: none; }\r\n</st" +
"yle>\r\n<input type=\"hidden\" id=\"selExampaperSort\" value=\"0\" />\r\n<input type=\"hidd" +
"en\" id=\"selectType\" value=\"");


            
            #line 22 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                                       Write(selectType);

            
            #line default
            #line hidden
WriteLiteral(@""" />
<div class=""clb"">
    <div class=""treeview-box fl span20"">
        <div id=""sortList"" class=""tree-list""></div>
    </div>
    <div class=""fr span56 ml10"">
        <div id=""Exampaper"">
            <table id=""table_ExamList"" class=""tab-List"">
                <thead>
                    <tr>
                        <th class=""span3"">
");


            
            #line 33 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                             if (selectType == "checkbox")
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <input id=\"examSelectall\" type=\"");


            
            #line 35 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                                                            Write(selectType);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 36 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </th>\r\n                        <th class=\"span12\">\r\n   " +
"                         ");


            
            #line 40 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                       Write(Exampaper.ExampaperTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </th>\r\n                        <th class=\"span12\">\r\n   " +
"                         ");


            
            #line 43 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                       Write(Exampaper.ExampaperSortName);

            
            #line default
            #line hidden
WriteLiteral(" (试卷类型)\r\n                        </th>\r\n                        <th>\r\n           " +
"                 ");


            
            #line 46 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                       Write(Exampaper.ExampaperDescription);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </th>\r\n                        <th class=\"span6\">试卷总分\r\n" +
"                        </th>\r\n                        <th class=\"span4\">\r\n     " +
"                       ");


            
            #line 51 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                       Write(Exampaper.Operation);

            
            #line default
            #line hidden
WriteLiteral(@"
                        </th>
                    </tr>
                </thead>
                <tbody id=""ExampaperList"">
                </tbody>
                <tfoot>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<center class=""mt10"">
    <input id=""btnAddExam"" class=""btn"" type=""button"" onclick="" GetExamIDList(); "" value=""确定"" />
</center>
<script id=""ExamKeyTemplate"" type=""text/x-jsrender"">
    {{for #data}}
    <tr>
        <td><input id=""{{:id}}"" name=""ExamList"" type=""");


            
            #line 69 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                                                  Write(selectType);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"{{:id}}\" /></td>\r\n        <td><div class=\"tl ovh span10\" id=\"paper_{{:id" +
"}}\"  pop_totalsocre=\"{{:ExampaperScore}}\" title=\"{{:ExampaperTitle}}\"><strong>{{" +
":ExampaperTitle}}</strong></div></td>\r\n        <td>\r\n            <p class=\"tl\" t" +
"itle=\"{{:ExamSortTitle}}\">{{:ExamSortTitle}}</p>\r\n            <p class=\"tl Info\"" +
">{{:ExamType}}</p>\r\n        </td>\r\n        <td><div class=\"tl\" title=\"{{:Questio" +
"nTypeList}}\">{{:QuestionTypeList}}</div></td>\r\n        <td>{{:ExampaperScore}}</" +
"td>\r\n        <td><a title=\"预览\" onclick=\"Detail({{:id}},{{:ExamSortID}});\" class=" +
"\"icon iview\"></a></td>\r\n    </tr>\r\n    {{/for}}\r\n</script>\r\n<script type=\"text/j" +
"avascript\">\r\n    function initExampaperSort() {\r\n        $.getJSON(\"/Exampaper/G" +
"etAllExampaperSort?t=\" + new Date(), function(data) {\r\n            $(\"#sortList\"" +
").html(data);\r\n            //树的显示\r\n            $(\"#navigation ul\").treeview({\r\n " +
"               persist: \"location\",\r\n                collapsed: false,\r\n        " +
"        unique: false\r\n            });\r\n            $(\"#navigation>li>ul>li>div\"" +
").each(function () {\r\n                $(this).click();\r\n            });\r\n       " +
"     //选择后定位\r\n            threeBackground(\'0\');\r\n        });\r\n    }\r\n\r\n//显示所有试卷\r" +
"\n\r\n    function InitializeTargetList(url)\r\n    {\r\n        $(\"#ExampaperList\").Js" +
"RenderData({\r\n            sourceUrl: url,\r\n            isPage: true,\r\n          " +
"  pageSize: 10,\r\n            pageIndex: 1,\r\n            templateID: \'ExamKeyTemp" +
"late\',\r\n            funCallback: function() {\r\n                SetCheckBox(\"exam" +
"Selectall\", \"Exampaper\");\r\n                HiddenSelectExam($(\"#selectType\").val" +
"());\r\n            }\r\n        });        \r\n    }\r\n\r\n    function getUrlParms() {\r" +
"\n        return \'/Exampaper/GetAllExampaperList?type=0&eSortID=\' + $(\"#selExampa" +
"perSort\").val() + \'&eExamType=3&eTitle=&t=\' + new Date();\r\n    }\r\n\r\n    //问题分类树点" +
"击事件\r\n\r\n    function selectSort(id) {\r\n        $(\"#selExampaperSort\").val(id);\r\n " +
"       $(\"#tbPaperTitle\").val(\"\");\r\n        InitializeTargetList(getUrlParms());" +
"\r\n    }\r\n\r\n    $(document).ready(function() {\r\n        //初始化试卷库\r\n       initExam" +
"paperSort();\r\n        //初始化列表\r\n       InitializeTargetList(getUrlParms());\r\n    " +
"});\r\n\r\n    function HiddenSelectExam(obj) {\r\n        if ($(\"#AllExamID\") != unde" +
"fined && $(\"#AllExamID\") != null && $(\"#AllExamID\") != \"\") {\r\n            $(\"#Ex" +
"ampaper td input[type=\'\" + obj + \"\']\").each(function() {\r\n                if ((\'" +
",\' + $(\"#AllExamID\").val() + \',\').indexOf(\',\' + $(this).attr(\'id\') + \',\') >= 0) " +
"{\r\n                    $(this).attr(\'disabled\', \'disabled\');\r\n                }\r" +
"\n            });\r\n        }\r\n    }\r\n\r\n    function GetExamIDList() {\r\n       \r\n " +
"       var flag = false;\r\n        var check = document.getElementsByName(\"ExamLi" +
"st\");\r\n        var checkList = \"\";\r\n        for (var i = 0; i < check.length; i+" +
"+) {\r\n            if (check[i].checked) {\r\n                checkList = checkList" +
" + check[i].value + \",\";\r\n                flag = true;\r\n            }\r\n        }" +
"\r\n        if (!flag) {\r\n            art.dialog.tips(\"请选择试卷\", 1.5);\r\n            " +
"return;\r\n        } else {\r\n            checkList = checkList.substring(0, checkL" +
"ist.length - 1);\r\n            ExamIDList(checkList);\r\n        }\r\n    }\r\n\r\n//查看试卷" +
"\r\n\r\n    function Detail(id, sid) {\r\n        var openurl = \"/Exampaper/ExampaperD" +
"etail?type=1&id=\" + id + \"&sortID=\" + sid + \"&t=\" + new Date();\r\n        $.get(o" +
"penurl, function (data) {\r\n            art.dialog({\r\n                title: \"");


            
            #line 171 "..\..\Views\Exampaper\ExampaperSelect.cshtml"
                   Write(Exampaper.ExampaerDetail);

            
            #line default
            #line hidden
WriteLiteral(@""",
                id: ""examSee"",
                lock: true,
                fixed: true,
                width: 700,
                height: 450,
                time: false,
                content: data,
                close: function () {
                    $('#popIframe').hide();
                    $("".aui_content"").css({ ""height"": ""500px"", ""width"": ""850px"", ""overflow"": ""auto"" });
                }
            });
            $("".aui_content"").css({ ""height"": ""500px"", ""width"": ""850px"", ""overflow"": ""auto"" });
            //$("".aui_content"").html(data);
        });
    }
</script>");


        }
    }
}
#pragma warning restore 1591
