#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Exampaper
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
    using LiXinModels.Examination.DBModel;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
    using LiXinModels.Examination.ShowModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Exampaper/ExampaperEdit.cshtml")]
    public class ExampaperEdit : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExampaperEdit()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
  
    var expape = ViewData["expape"] as tbExampaper;
    var expapeQuestion = ViewData["expapeQuestion"] as List<tbQuestion>;
    var expapeRule = ViewData["expapeRule"] as List<MExamRuleShow>;
    string fsort = Request.QueryString["sortID"] == null ? "0" : Request.QueryString["sortID"];
    string selectSortID = Request.QueryString["selectSortID"] ?? "0";
    ViewBag.Title = ViewData["id"].ToString() == "0" ? NavigateMenuLanguage.AddExampaper : NavigateMenuLanguage.EditExampaper;


            
            #line default
            #line hidden
WriteLiteral("<script type=\"text/javascript\" src=\"");


            
            #line 12 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                               Write(Url.Content("~/Scripts/jquery.dragsort-0.4.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"> </script>\r\n<div class=\"main-c\">\r\n    ");


            
            #line 14 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
Write(Html.Action("SiteMapLink", "Common", new
    {
        linkName = ViewData["id"].ToString() == "0" ? "AddExampaper" : "EditExampaper"
    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");



WriteLiteral("\r\n    <form id=\"EditExampaerForm\" method=\"post\" action=\"\">\r\n    <h3 class=\"tit-h3" +
" mt10\">试卷基本信息</h3>\r\n    <table class=\"tab-Form tab-now mt10\">\r\n        <tr>\r\n   " +
"         <td class=\"Tit all15\"><span title=\"必填项\" class=\"must\">*</span>");


            
            #line 25 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                    Write(Exampaper.ExampaperTitle);

            
            #line default
            #line hidden
WriteLiteral("：</td>\r\n            <td>\r\n                <input class=\"span20\" type=\"text\" id=\"t" +
"bExamTitle\" name=\"tbExamTitle\" maxlength=\"30\" value=\"");


            
            #line 27 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                        Write(expape == null ? "" : expape.ExampaperTitle);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"Tit\">" +
"<span title=\"必填项\" class=\"must\">*</span>");


            
            #line 31 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                              Write(Exampaper.Score);

            
            #line default
            #line hidden
WriteLiteral("：</td>\r\n            <td>\r\n                <input class=\"span5\" type=\"text\" id=\"qu" +
"estion_sum\" name=\"question_sum\" readonly=\"readonly\" />\r\n            </td>\r\n     " +
"   </tr>\r\n        <tr>\r\n            <td class=\"Tit\"><span title=\"必填项\" class=\"mus" +
"t\">*</span>");


            
            #line 37 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                              Write(Exampaper.ExampaperSortName);

            
            #line default
            #line hidden
WriteLiteral("：</td>\r\n            <td>\r\n                <input class=\"span20\" type=\"text\" id=\"f" +
"atherid\" name=\"fatherid\" disabled=\"disabled\" value=\"");


            
            #line 39 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                      Write(ViewData["fatherModel"]);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                <input type=\"button\" id=\"btnSelecte\" class=\"btn btn-co\" val" +
"ue=\"选择试卷库\" />\r\n                <input type=\"hidden\" id=\"Sortid\" name=\"Sortid\" va" +
"lue=\"");


            
            #line 41 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                 Write(fsort);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"Tit\"" +
"><span title=\"必填项\" class=\"must\">*</span>试卷类型：</td>\r\n            <td>\r\n          " +
"      <div class=\"sel\">\r\n");


            
            #line 48 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                  
                    if (expape == null || expape.ExamType == 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <input type=\"radio\" id=\"examType0\" name=\"examType\" value=\"0\" " +
"checked=\"checked\" onclick=\"checkType(0)\" />");



WriteLiteral("<label>普通</label>\r\n");



WriteLiteral("                    <input type=\"radio\" id=\"examType1\" name=\"examType\" value=\"1\" " +
"onclick=\"checkType(1)\" />");



WriteLiteral("<label>随机</label>\r\n");


            
            #line 53 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <input type=\"radio\" id=\"examType0\" name=\"examType\" value=\"0\" " +
"onclick=\"checkType(0)\" />");



WriteLiteral("<label>普通</label>\r\n");



WriteLiteral("                    <input type=\"radio\" id=\"examType1\" name=\"examType\" value=\"1\" " +
"checked=\"checked\" onclick=\"checkType(1)\" />");



WriteLiteral("<label>随机</label>\r\n");


            
            #line 58 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                    }
                

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n         " +
"   <td class=\"Tit\">");


            
            #line 64 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                       Write(Exampaper.Description);

            
            #line default
            #line hidden
WriteLiteral("：\r\n            </td>\r\n            <td>\r\n                <textarea class=\"span40\" " +
"id=\"txtDescription\" name=\"tbRemark\" onkeydown=\" TextearaMaxlength(this); \"\r\n    " +
"                onkeyup=\" TextearaMaxlength(this); \" maxlength=\"200\" textmode=\"M" +
"ultiLine\">");


            
            #line 68 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                          Write(expape == null ? "" : expape.Description);

            
            #line default
            #line hidden
WriteLiteral(@"</textarea>
            </td>
        </tr>
        <tr>
            <td class=""Tit"">题型排序：</td>
            <td class=""c99""><div class=""charleft originalTextareaInfo"">( 请前后拖动调整排序方式 )</div></td>
        </tr>
        <tr>
            <td class=""Tit"">
            </td>
            <td id=""paixu"" class=""qorder"">
                <ul id=""typeorder"" class=""clb"">
");


            
            #line 80 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                      
                        if (expape != null)
                        {
                            string[] parr = expape.QuestionTypeOrder.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries);
                            for (int i = 0; i < parr.Length; i++)
                            {
                                switch (parr[i])
                                {
                                    case "1":

            
            #line default
            #line hidden
WriteLiteral("                        <li id=\"t1\">问答题</li>\r\n");


            
            #line 90 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                        break;
                                    case "2":

            
            #line default
            #line hidden
WriteLiteral("                        <li id=\"t2\">单选题</li>\r\n");


            
            #line 93 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                        break;
                                    case "3":

            
            #line default
            #line hidden
WriteLiteral("                        <li id=\"t3\">多选题</li>\r\n");


            
            #line 96 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                        break;
                                    case "4":

            
            #line default
            #line hidden
WriteLiteral("                        <li id=\"t4\">判断题</li>\r\n");


            
            #line 99 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                        break;
                                    case "5":

            
            #line default
            #line hidden
WriteLiteral("                        <li id=\"t5\">填空题</li>\r\n");


            
            #line 102 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                        break;
                                    case "6":

            
            #line default
            #line hidden
WriteLiteral("                        <li id=\"t6\">情景题</li>\r\n");


            
            #line 105 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                        break;
                                }
                            }
                        }
                    

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <h3 cl" +
"ass=\"tit-h3\">\r\n        <div class=\"pos_a f12\" style=\"top:-5px;right:0;\">\r\n");


            
            #line 116 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
              
                if (expape == null || expape.ExamType == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                <input id=\"btAddQuestion\" class=\"btn btn-co\" type=\"button\" value=" +
"\"");


            
            #line 119 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                             Write(Exampaper.SortAdd);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("                <input id=\"btRandomQuestion\" class=\"btn btn-co\" type=\"button\" val" +
"ue=\"");


            
            #line 120 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                Write(Exampaper.RandomAdd);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("                <input id=\"btExportNewQuestion\" class=\"btn btn-co\" type=\"button\" " +
"value=\"");


            
            #line 121 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                   Write(Exampaper.ImportQuestion);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("                <input type=\"button\" id=\"btQuestionRule\" class=\"btn btn-co\" disab" +
"led=\"disabled\"\r\n                    value=\"组卷规则\" />\r\n");


            
            #line 124 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                <input id=\"btAddQuestion\" class=\"btn btn-co\" disabled=\"disabled\" " +
"type=\"button\" value=\"");


            
            #line 127 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                 Write(Exampaper.SortAdd);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("                <input id=\"btRandomQuestion\" class=\"btn btn-co\" disabled=\"disable" +
"d\" type=\"button\" value=\"");


            
            #line 128 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                    Write(Exampaper.RandomAdd);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("                <input id=\"btExportNewQuestion\" class=\"btn btn-co\" disabled=\"disa" +
"bled\" type=\"button\" value=\"");


            
            #line 129 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                       Write(Exampaper.ImportQuestion);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");



WriteLiteral("                <input type=\"button\" id=\"btQuestionRule\" class=\"btn btn-co\" value" +
"=\"组卷规则\" />\r\n");


            
            #line 131 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                }
            

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        试题信息\r\n    </h3>\r\n    <div>\r\n");


            
            #line 137 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
      
        if ("#StatType" != "")
        {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"qView mt10\">\r\n            <div id=\"StatType\" class=\"clb\">\r\n  " +
"              <input type=\"hidden\" name=\"desum\" value=\"");


            
            #line 142 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                     Write(expape == null ? "" : expape.Distribution);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n            </div>\r\n            <div id=\"StatScore\" class=\"clb\"></div>\r\n    " +
"    </div>\r\n");


            
            #line 146 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
        }
    

            
            #line default
            #line hidden
WriteLiteral("        <div id=\"divExamQuestions\" class=\"mt10\" style=\"height: 500px; overflow-y:" +
" auto;\">\r\n");


            
            #line 149 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
              
                if (expapeQuestion != null && expapeQuestion.Count > 0)
                {
                        int qq = 0;
                        foreach (tbQuestion Question in expapeQuestion)
                      {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"QSingle\" id=\"QuestionID");


            
            #line 155 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                   Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <input type=\"hidden\" name=\"");


            
            #line 156 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                               Write(Question.QuestionType);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");


            
            #line 156 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral("|");


            
            #line 156 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                Write(Question.QuestionType);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                        <div class=\"title\">\r\n                            <di" +
"v class=\"info\">\r\n                                <input type=\"text\" id=\"Order");


            
            #line 159 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                        Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"Order");


            
            #line 159 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                    Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");


            
            #line 159 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                            Write(expape.QuestionList[qq].QOrder);

            
            #line default
            #line hidden
WriteLiteral("\" readonly=\"readonly\" maxlength=\"3\" />\r\n                                .[\r\n     " +
"                           <input type=\"text\" class=\"fen\" id=\"Score");


            
            #line 161 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                    Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"Score");


            
            #line 161 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral("\" readonly=\"readonly\" maxlength=\"3\" value=\"");


            
            #line 161 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                          Write(expape.QuestionList[qq].QScore);

            
            #line default
            #line hidden
WriteLiteral("\" />分\r\n                                ]\r\n                            </div>\r\n   " +
"                         <h5>\r\n                                ");


            
            #line 165 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                            Write(Html.Raw(Question.QuestionContent));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div class=\"do\"><a href=\"#");


WriteLiteral("@\" onclick=\" Delete(");


            
            #line 166 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                           Write(Question._id);

            
            #line default
            #line hidden
WriteLiteral(") \" class=\"icon idel\" title=\"删除\"></a></div>\r\n                            </h5>\r\n " +
"                       \r\n                        </div>\r\n                       " +
" <div class=\"content\">\r\n");


            
            #line 171 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                              
                              switch (Question.QuestionType)
                              {
                                  case 1:

            
            #line default
            #line hidden
WriteLiteral("                                <textarea disabled=\"disabled\"></textarea>\r\n");


            
            #line 176 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      break;
                                  case 2:
                                      {
                                          int count = 0;
                                          foreach (QuestionAnswer s in Question.QuestionAnswer)
                                          {

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n                                    <input" +
" type=\"radio\" disabled=\"disabled\" />");


            
            #line 183 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                          Write((char)(65 + count));

            
            #line default
            #line hidden
WriteLiteral(". ");


            
            #line 183 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                Write(s.Answer);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 184 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                              count++;
                                          }
                                      }
                                      break;
                                  case 3:
                                      {
                                          int count = 0;
                                          foreach (QuestionAnswer ss in Question.QuestionAnswer)
                                          {

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n                                    <input" +
" type=\"checkbox\" disabled=\"disabled\" />");


            
            #line 194 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                             Write((char)(65 + count));

            
            #line default
            #line hidden
WriteLiteral(". ");


            
            #line 194 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                   Write(ss.Answer);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 195 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                              count++;
                                          }
                                      }
                                      break;
                                  case 4:

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n                                    <input" +
" type=\"radio\" disabled=\"disabled\" /><label>");


            
            #line 201 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                Write(Exampaper.eTrue);

            
            #line default
            #line hidden
WriteLiteral("</label></div>\r\n");



WriteLiteral("                                <div>\r\n                                    <input" +
" type=\"radio\" disabled=\"disabled\" /><label>");


            
            #line 203 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                Write(Exampaper.eFalse);

            
            #line default
            #line hidden
WriteLiteral("</label></div>\r\n");


            
            #line 204 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                break;
                                  case 6:
                                                                                if (Question.QuestionAnswer[0].AnswerType == 0)
                                                                                {

            
            #line default
            #line hidden
WriteLiteral("                                <textarea class=\"Boxarea\" disabled=\"disabled\"></t" +
"extarea>\r\n");


            
            #line 209 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                }
                                                                                else if (Question.QuestionAnswer[0].AnswerType == 1)
                                                                                {
                                                                                    int count = 0;
                                                                                    foreach (QuestionAnswer sss in Question.QuestionAnswer)
                                                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n                                    <input" +
" type=\"radio\" disabled=\"disabled\" />");


            
            #line 216 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                          Write((char)(65 + count));

            
            #line default
            #line hidden
WriteLiteral(". ");


            
            #line 216 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                Write(sss.Answer);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 217 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                        count++;
                                                                                    }
                                                                                }
                                                                                else
                                                                                {
                                                                                    int count = 0;
                                                                                    foreach (QuestionAnswer ssss in Question.QuestionAnswer)
                                                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n                                    <input" +
" type=\"checkbox\" disabled=\"disabled\" />");


            
            #line 226 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                             Write((char)(65 + count));

            
            #line default
            #line hidden
WriteLiteral(". ");


            
            #line 226 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                   Write(ssss.Answer);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 227 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                        count++;
                                                                                    }
                                                                                }
                                                                                break;
                              }
                            

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n");


            
            #line 235 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          qq++;
                      }
                    
                }
                if (expapeRule != null && expapeRule.Count > 0)
                {
                    int rid = 1;
                    foreach (MExamRuleShow Rule in expapeRule)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"exam-rule\">\r\n                            <inp" +
"ut type=\"hidden\" name=\"Rule\" value=\"");


            
            #line 245 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                               Write(rid);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                            <input type=\"hidden\" id=\"qru");


            
            #line 246 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                    Write(rid);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"qru\" value=\"");


            
            #line 246 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                              Write(Rule.qitaone);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                            <input type=\"hidden\" id=\"eqid");


            
            #line 247 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                     Write(rid);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"eqid\" value=\"");


            
            #line 247 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                Write(Rule.qita);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                            <p class=\"tit\">");


            
            #line 248 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      Write(Exampaper.qType);

            
            #line default
            #line hidden
WriteLiteral("：</p>\r\n                            <p class=\"span8\">");


            
            #line 249 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                         Write(Rule.QuestionType);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p class=\"tit\">");


            
            #line 250 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      Write(Exampaper.qSort);

            
            #line default
            #line hidden
WriteLiteral("：</p>\r\n                            <p class=\"ovh span40\" title=\"");


            
            #line 251 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                     Write(Rule.QuestionSort);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 251 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                           Write(Rule.QuestionSort);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p class=\"tit\">每题分值：</p>\r\n                     " +
"       <p><span>");


            
            #line 253 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                 Write(Rule.QuestingScore);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n                            <p class=\"tit\">");


            
            #line 254 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      Write(Exampaper.qLevel);

            
            #line default
            #line hidden
WriteLiteral("：</p>\r\n                            <p>易<span>");


            
            #line 255 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                  Write(Rule.Leveleasy);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n                            <p>中<span>");


            
            #line 256 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                  Write(Rule.Levelcommon);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n                            <p>难<span>");


            
            #line 257 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                  Write(Rule.Levelhard);

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n                            <a name=\"rmRule\" title=\"");


            
            #line 258 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                               Write(CommonLanguage.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral("\"  class=\"icon idel\"></a>\r\n                        </div>\r\n");


            
            #line 260 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                        rid++;
                    }
                }
            

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div id=\"hiddExamQuestions\">\r\n        </div>\r\n        <di" +
"v id=\"hiddtypeorder\">\r\n        </div>\r\n    </div>\r\n    <center class=\"mt10\">\r\n  " +
"      <a id=\"btnSaveSort\" class=\"btn\" onclick=\" $(this).submit(); \">");


            
            #line 271 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                 Write(Exampaper.Save);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        <a id=\"btBack\" class=\"btn btn-cancel\">");


            
            #line 272 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                         Write(Exampaper.Back);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n    </center>\r\n    </form>\r\n\r\n</div>\r\n<script type=\"text/javascript\">\r\n    " +
"$(\"#paixu ul\").dragsort();\r\n\r\n    function countInstances(mainStr, subStr) {\r\n  " +
"      var count = 0;\r\n        var offset = 0;\r\n        do {\r\n            offset " +
"= mainStr.indexOf(subStr, offset);\r\n            if (offset != -1) {\r\n           " +
"     count++;\r\n                offset += subStr.length;\r\n            }\r\n        " +
"} while (offset != -1);\r\n        return count;\r\n    }\r\n\r\n    function checkType(" +
"tt) {\r\n        if (tt == 1) {\r\n            $(\'#StatType\').html(\"\");\r\n           " +
" $(\'#StatScore\').html(\"\");\r\n            $(\'#divExamQuestions\').html(\"\");\r\n      " +
"      $(\'#hiddExamQuestions\').html(\"\");\r\n            $(\"#question_sum\").val(\"\");" +
"\r\n            $(\'#typeorder\').html(\"\");\r\n            $(\'#btAddQuestion\').attr(\"d" +
"isabled\", \"disabled\");\r\n            $(\'#btRandomQuestion\').attr(\"disabled\", \"dis" +
"abled\");\r\n            $(\'#btAddNewQuestion\').attr(\"disabled\", \"disabled\");\r\n    " +
"        $(\'#btExportNewQuestion\').attr(\"disabled\", \"disabled\");\r\n            $(\'" +
"#btQuestionRule\').removeAttr(\"disabled\");\r\n        } else {\r\n            $(\'#Sta" +
"tType\').html(\"\");\r\n            $(\'#StatScore\').html(\"\");\r\n            $(\'#divExa" +
"mQuestions\').html(\"\");\r\n            $(\'#hiddExamQuestions\').html(\"\");\r\n         " +
"   $(\"#question_sum\").val(\"\");\r\n            $(\'#typeorder\').html(\"\");\r\n         " +
"   $(\'#btAddQuestion\').removeAttr(\"disabled\");\r\n            $(\'#btRandomQuestion" +
"\').removeAttr(\"disabled\");\r\n            $(\'#btAddNewQuestion\').removeAttr(\"disab" +
"led\");\r\n            $(\'#btExportNewQuestion\').removeAttr(\"disabled\");\r\n         " +
"   $(\'#btQuestionRule\').attr(\"disabled\", \"disabled\");\r\n        }\r\n    }\r\n\r\n//题型\r" +
"\n    function qtype() {\r\n        var eqids = \"\";\r\n        var tmp = $(\'#divExamQ" +
"uestions\').find(\'input[type=hidden]\');\r\n        if ($(\'input[name=examType]:chec" +
"ked\').val() == 1) {\r\n            tmp = $(\'#divExamQuestions\').find(\'input[name=q" +
"ru]\');\r\n        }\r\n        for (var i = 0; i < tmp.length; i++) {\r\n            i" +
"f (tmp[i].name != \"\" && tmp[i].name != null) {\r\n                var linshi = \"\";" +
"\r\n                var sum = parseInt(tmp[i].name);\r\n                if ($(\'input" +
"[name=examType]:checked\').val() == 1) {\r\n                    var msg = tmp[i].va" +
"lue.split(\"|\");\r\n                    sum = parseInt(msg[0]);\r\n                }\r" +
"\n                switch (sum) {\r\n                case 1:\r\n                    li" +
"nshi = \'<li id=\"t1\">问答题</li>\';\r\n                    break;\r\n                case" +
" 2:\r\n                    linshi = \'<li id=\"t2\">单选题</li>\';\r\n                    b" +
"reak;\r\n                case 3:\r\n                    linshi = \'<li id=\"t3\">多选题</l" +
"i>\';\r\n                    break;\r\n                case 4:\r\n                    l" +
"inshi = \'<li id=\"t4\">判断题</li>\';\r\n                    break;\r\n                cas" +
"e 5:\r\n                    linshi = \'<li id=\"t5\">填空题</li>\';\r\n                    " +
"break;\r\n                case 6:\r\n                    linshi = \'<li id=\"t6\">情景题</" +
"li>\';\r\n                    break;\r\n                }\r\n                if (parseI" +
"nt(countInstances(eqids, linshi)) < 1) {\r\n                    eqids += linshi;\r\n" +
"                }\r\n            }\r\n        }\r\n        $(\"#typeorder\").html(eqids)" +
";\r\n    }\r\n\r\n//题型排序\r\n    function typeorder() {\r\n        var tmp = $(\'#paixu li\')" +
";\r\n        var eqids = \"\";\r\n        for (var i = 0; i < tmp.length; i++) {\r\n    " +
"        if (tmp[i].id != \"\" && tmp[i].id != null) {\r\n                var msg = t" +
"mp[i].id.replace(\"t\", \"\");\r\n                eqids += msg + \",\";\r\n            }\r\n" +
"        }\r\n        var qidhtml = \'<input type=\"hidden\" name=\"typeorder\" value=\"\'" +
" + eqids + \'\"/>\';\r\n        $(\"#hiddtypeorder\").html(qidhtml);\r\n    }\r\n\r\n//序号排序\r\n" +
"\r\n    function order() {\r\n        var tmp = $(\'#divExamQuestions\').find(\'input[t" +
"ype=hidden]\');\r\n        for (var i = 0; i < tmp.length; i++) {\r\n            if (" +
"tmp[i].value != \"\" && tmp[i].value != null) {\r\n                var msg = tmp[i]." +
"value.split(\"|\");\r\n                var hidd = \"Order\" + msg[0];\r\n               " +
" $(\"#\" + hidd).val(i + 1);\r\n            }\r\n        }\r\n    }\r\n\r\n    //统计类型\r\n\r\n   " +
" function StatType() {\r\n        var tmp1 = $(\"input[name=\'2\']\");\r\n        var tm" +
"p2 = $(\"input[name=\'3\']\");\r\n        var tmp3 = $(\"input[name=\'1\']\");\r\n        va" +
"r tmp4 = $(\"input[name=\'4\']\");\r\n        var tmp5 = $(\"input[name=\'5\']\");\r\n      " +
"  var tmp6 = $(\"input[name=\'6\']\");\r\n        var tmphtml = \"\";\r\n        var tmeph" +
"tml = \"\";\r\n        var desum = \"\";\r\n        if (tmp1.length > 0 || tmp2.length >" +
" 0 || tmp3.length > 0 || tmp4.length > 0 || tmp5.length > 0 || tmp6.length > 0) " +
"{\r\n            tmphtml += \'<p class=\"Tit\"><strong>");


            
            #line 404 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                          Write(Exampaper.QuestionNumber);

            
            #line default
            #line hidden
WriteLiteral(":</strong></p>\';\r\n            tmephtml += \'<p class=\"Tit\"><strong>");


            
            #line 405 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                           Write(Exampaper.QuestionScore);

            
            #line default
            #line hidden
WriteLiteral(@":</strong></p>';

            if (tmp1.length > 0) {
                var single = tmp1.eq(0).val().split(""|"");
                tmephtml += '<p>每题 <input type=""text"" class=""inpbor"" id=""question_single"" value=""' + $(""#Score"" + single[0]).val() + '"" onkeyup=""verifyInput(this)"" onblur=""upperCase(\'single\',this.value)"" />");


            
            #line 409 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                                                                           Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                tmphtml += \'<p>");


            
            #line 410 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          Write(Exampaper.Single);

            
            #line default
            #line hidden
WriteLiteral(" - <font>\' + tmp1.length + \'</font>");


            
            #line 410 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                              Write(Exampaper.Ti);

            
            #line default
            #line hidden
WriteLiteral(@"</p>';
                desum += ""2:"" + tmp1.length + "","";
            }
            if (tmp2.length > 0) {
                var multi = tmp2.eq(0).val().split(""|"");
                tmephtml += '<p>每题 <input type=""text"" class=""inpbor"" id=""question_multi"" value=""' + $(""#Score"" + multi[0]).val() + '"" onkeyup=""verifyInput(this)"" onblur=""upperCase(\'multi\',this.value)"" />");


            
            #line 415 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                                                                        Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                tmphtml += \'<p>");


            
            #line 416 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          Write(Exampaper.Multi);

            
            #line default
            #line hidden
WriteLiteral(" - <font>\' + tmp2.length + \'</font>");


            
            #line 416 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                             Write(Exampaper.Ti);

            
            #line default
            #line hidden
WriteLiteral(@"</p>';
                desum += ""3:"" + tmp2.length + "","";
            }
            if (tmp3.length > 0) {
                var subject = tmp3.eq(0).val().split(""|"");
                tmephtml += '<p>每题 <input type=""text"" class=""inpbor"" id=""question_subject"" value=""' + $(""#Score"" + subject[0]).val() + '"" onkeyup=""verifyInput(this)"" onblur=""upperCase(\'subject\',this.value)"" />");


            
            #line 421 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                                                                              Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                tmphtml += \'<p>");


            
            #line 422 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          Write(Exampaper.Subject);

            
            #line default
            #line hidden
WriteLiteral(" - <font>\' + tmp3.length + \'</font>");


            
            #line 422 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                               Write(Exampaper.Ti);

            
            #line default
            #line hidden
WriteLiteral(@"</p>';
                desum += ""1:"" + tmp3.length + "","";
            }
            if (tmp4.length > 0) {
                var judge = tmp4.eq(0).val().split(""|"");
                tmephtml += '<p>每题 <input type=""text"" class=""inpbor"" id=""question_judge"" value=""' + $(""#Score"" + judge[0]).val() + '"" onkeyup=""verifyInput(this)"" onblur=""upperCase(\'judge\',this.value)"" />");


            
            #line 427 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                                                                        Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                tmphtml += \'<p>");


            
            #line 428 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          Write(Exampaper.Judge);

            
            #line default
            #line hidden
WriteLiteral(" - <font>\' + tmp4.length + \'</font>");


            
            #line 428 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                             Write(Exampaper.Ti);

            
            #line default
            #line hidden
WriteLiteral(@"</p>';
                desum += ""4:"" + tmp4.length + "","";
            }
            if (tmp5.length > 0) {
                var fill = tmp5.eq(0).val().split(""|"");
                tmephtml += '<p>每题 <input type=""text"" class=""inpbor"" id=""question_fill"" value=""' + $(""#Score"" + fill[0]).val() + '"" onkeyup=""verifyInput(this)"" onblur=""upperCase(\'fill\',this.value)"" />");


            
            #line 433 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                                                                     Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                tmphtml += \'<p>");


            
            #line 434 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          Write(Exampaper.Fill);

            
            #line default
            #line hidden
WriteLiteral(" - <font>\' + tmp5.length + \'</font>");


            
            #line 434 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                            Write(Exampaper.Ti);

            
            #line default
            #line hidden
WriteLiteral(@"</p>';
                desum += ""5:"" + tmp5.length + "","";
            }
            if (tmp6.length > 0) {
                var scene = tmp6.eq(0).val().split(""|"");
                tmephtml += '<p>每题 <input type=""text"" class=""inpbor"" id=""question_scene"" value=""' + $(""#Score"" + scene[0]).val() + '"" onkeyup=""verifyInput(this)"" onblur=""upperCase(\'scene\',this.value)"" />");


            
            #line 439 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                                                                                                        Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                tmphtml += \'<p>");


            
            #line 440 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                          Write(Exampaper.Scene);

            
            #line default
            #line hidden
WriteLiteral(" - <font>\' + tmp6.length + \'</font>");


            
            #line 440 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                             Write(Exampaper.Ti);

            
            #line default
            #line hidden
WriteLiteral("</p>\';\r\n                desum += \"6:\" + tmp6.length + \",\";\r\n            }\r\n      " +
"  }\r\n        var dehtml = \'<input type=\"hidden\" name=\"desum\" value=\"\' + desum + " +
"\'\"/>\';\r\n        $(\"#StatType\").html(\"\");\r\n        $(\"#StatType\").append(tmphtml)" +
";\r\n        $(\"#StatType\").append(dehtml);\r\n        $(\"#StatScore\").html(tmephtml" +
");\r\n    }\r\n\r\n    //统计QuestionID\r\n\r\n    function statID() {\r\n        var tmp = $(" +
"\'#divExamQuestions\').find(\'input[type=hidden]\');\r\n        var eqids = \"\";\r\n     " +
"   for (var i = 0; i < tmp.length; i++) {\r\n            if (tmp[i].value != \"\" &&" +
" tmp[i].value != null) {\r\n                eqids += tmp[i].value + \",\";\r\n        " +
"    }\r\n        }\r\n        var qidhtml = \'<input type=\"hidden\" id=\"Queid\" name=\"Q" +
"ueid\" value=\"\' + eqids + \'\"/>\';\r\n        $(\"#hiddExamQuestions\").html(qidhtml);\r" +
"\n    }\r\n\r\n    function statRule() {\r\n        var tmp = $(\'#divExamQuestions\').fi" +
"nd(\'input[name=Rule]\');\r\n        var eqids = \"\";\r\n        for (var i = 0; i < tm" +
"p.length; i++) {\r\n            if (tmp[i].value != \"\" && tmp[i].value != null) {\r" +
"\n                eqids += $(\"#eqid\" + tmp[i].value).val() + \",\";\r\n            }\r" +
"\n        }\r\n        var qidhtml = \'<input type=\"hidden\" id=\"Queid\" name=\"Queid\" " +
"value=\"\' + eqids + \'\"/>\';\r\n        $(\"#hiddExamQuestions\").html(qidhtml);\r\n    }" +
"\r\n\r\n//初始化计分\r\n\r\n    function Score() {\r\n        var sum = 0;\r\n        if ($(\'inpu" +
"t[name=examType]:checked\').val() == 0) {\r\n            var tmp = $(\'#divExamQuest" +
"ions\').find(\'input[type=hidden]\');\r\n            for (var i = 0; i < tmp.length; " +
"i++) {\r\n                if (tmp[i].value != \"\" && tmp[i].value != null) {\r\n     " +
"               var msg = tmp[i].value.split(\"|\");\r\n                    var tom =" +
" \"#Score\" + msg[0];\r\n                    sum = parseInt(sum) + parseInt($(tom).v" +
"al());\r\n                }\r\n            }\r\n        } else {\r\n            var tmp " +
"= $(\'#divExamQuestions\').find(\'input[name=Rule]\');\r\n            for (var i = 0; " +
"i < tmp.length; i++) {\r\n                if (tmp[i].value != \"\" && tmp[i].value !" +
"= null) {\r\n                    var su = $(\"#eqid\" + tmp[i].value).val();\r\n      " +
"              var msg = su.split(\"|\");\r\n                    var so = msg[2];\r\n  " +
"                  if (parseInt(so) > 0) {\r\n                        sum += (parse" +
"Int(msg[3]) + parseInt(msg[4]) + parseInt(msg[5])) * parseInt(so);\r\n            " +
"        }\r\n                }\r\n            }\r\n        }\r\n        $(\"#question_sum" +
"\").val(sum);\r\n    }\r\n\r\n//批量修改分值\r\n\r\n    function upperCase(num, sum) {\r\n        v" +
"ar tmp = null;\r\n        switch (num) {\r\n        case \'single\':\r\n            tmp " +
"= document.getElementsByName(\"2\");\r\n            break;\r\n        case \'multi\':\r\n " +
"           tmp = document.getElementsByName(\"3\");\r\n            break;\r\n        c" +
"ase \'subject\':\r\n            tmp = document.getElementsByName(\"1\");\r\n            " +
"break;\r\n        case \'fill\':\r\n            tmp = document.getElementsByName(\"5\");" +
"\r\n            break;\r\n        case \'judge\':\r\n            tmp = document.getEleme" +
"ntsByName(\"4\");\r\n            break;\r\n        case \'scene\':\r\n            tmp = do" +
"cument.getElementsByName(\"6\");\r\n            break;\r\n        }\r\n        var str =" +
" sum.replace(/\\s+/g, \"\");\r\n        var r = /^[0-9]*[1-9][0-9]*$/;\r\n        if (s" +
"um != \"\" && str != \"\" && r.test(sum)) {\r\n            for (var i = 0; i < tmp.len" +
"gth; i++) {\r\n                if (tmp[i].value != \"\" && tmp[i].value != null) {\r\n" +
"                    var msg = tmp[i].value.split(\"|\");\r\n                    $(\"#" +
"Score\" + msg[0]).val(sum);\r\n                }\r\n            }\r\n            Score(" +
");\r\n        }\r\n    }\r\n\r\n    function upScore() {\r\n        if ($(\"#question_fill\"" +
").length > 0) {\r\n            upperCase(\"fill\", $(\"#question_fill\").val());\r\n    " +
"    }\r\n        if ($(\"#question_single\").length > 0) {\r\n            upperCase(\"s" +
"ingle\", $(\"#question_single\").val());\r\n        }\r\n        if ($(\"#question_multi" +
"\").length > 0) {\r\n            upperCase(\"multi\", $(\"#question_multi\").val());\r\n " +
"       }\r\n        if ($(\"#question_subject\").length > 0) {\r\n            upperCas" +
"e(\"subject\", $(\"#question_subject\").val());\r\n        }\r\n        if ($(\"#question" +
"_judge\").length > 0) {\r\n            upperCase(\"judge\", $(\"#question_judge\").val(" +
"));\r\n        }\r\n        if ($(\"#question_scene\").length > 0) {\r\n            uppe" +
"rCase(\"scene\", $(\"#question_scene\").val());\r\n        }\r\n    }\r\n\r\n    $(document)" +
".ready(function() {\r\n        StatType();\r\n        upScore();\r\n        Score();\r\n" +
"        statID();\r\n        bindRule();\r\n//        jQuery.validator.addMethod(\"st" +
"ringCheck\", function (value, element) {\r\n//            return this.optional(elem" +
"ent) || /^[\\u0391-\\uFFE5\\w]+$/.test(value);\r\n//        }, \"只能包括中文字、英文字母、数字和下划线\")" +
";\r\n\r\n        $(\"#EditExampaerForm\").validate({\r\n            rules: {\r\n          " +
"      tbExamTitle: {\r\n                    required: true,\r\n                    m" +
"axlength: 30,\r\n//                    stringCheck:true,\r\n                    remo" +
"te: {\r\n                        type: \"post\",\r\n                        dataType: " +
"\"json\",\r\n                        url: \"/Exampaper/CheckExampaper\",\r\n            " +
"            data: { etitle: function() { return $.trim($(\"#tbExamTitle\").val());" +
" }, eid: function() { return ");


            
            #line 584 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                                                     Write(expape == null ? 0 : expape._id);

            
            #line default
            #line hidden
WriteLiteral(@"; } }
                    }
                },
                tbRemark: {
                    maxlength: 200
                }
            },
            messages: {
                tbExamTitle: {
                    required: ""请填名称"",
                    maxlength: ""字数不能超过30个字符"",
//                    stringCheck: ""只能包括中文字、英文字母、数字和下划线"",
                    remote: ""试卷已经存在""
                },
                tbRemark: {
                    maxlength: ""字数不能超过200个字符""
                }
            },
            errorElement: ""span"",
            submitHandler: function(form) {
                if ($('input[name=examType]:checked').val() == 0) {
                    statID();
                } else {
                    statRule();
                }
                typeorder();
                if ($(""#Queid"").val() != """" && $(""#Queid"").val() != null) {
                    jQuery(form).ajaxSubmit({
                        url: '/Exampaper/SubmitExampaer?id=");


            
            #line 612 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                       Write(expape == null ? 0 : expape._id);

            
            #line default
            #line hidden
WriteLiteral(@"',
                        type: ""post"",
                        dataType: ""json"",
                        success: function(data) {
                            if (data.result == 1) {
                                window.location.href = ""/Exampaper/ExampaperList?sortID=");


            
            #line 617 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                                   Write(selectSortID);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                            } else {\r\n                                art.dia" +
"log.tips(data.content, 3);\r\n                                //art.dialog({ title" +
": \'");


            
            #line 620 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, width: 400, height: 100, fixed: true, lock: true, time: 3 });
                            }
                        }
                    });
                } else {
                    art.dialog.tips(""请选择试卷题目"", 3);
                    //art.dialog({ title: '");


            
            #line 626 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请选择试卷题目！"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
                }
            }
        });
        //重新选择试卷库
        $(""#btnSelecte"").bind(""click"", function() {
            art.dialog.load(""/Exampaper/ExampaperSort"",{ title: ""试卷库"", id:""ExamSort"",close:function () {
                $(""#sortList"").css({""height"":""auto""});
            }
            });
        });

        $(""#btBack"").bind(""click"", function() {
            window.location.href = ""/Exampaper/ExampaperList?sortID=");


            
            #line 639 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                               Write(selectSortID);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        });\r\n        //题库添加\r\n        $(\"#btAddQuestion\").bind(\"click\", functi" +
"on() {\r\n            art.dialog.load(\"/Exampaper/ExamQuestionList\", {title: \"");


            
            #line 643 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                               Write(Exampaper.SortAdd);

            
            #line default
            #line hidden
WriteLiteral("\",id:\"QueList\" });\r\n        });\r\n        //自由组卷\r\n        $(\"#btRandomQuestion\").b" +
"ind(\"click\", function() {\r\n            art.dialog.load(\"/Exampaper/ExampaperRand" +
"om\", {title: \"");


            
            #line 647 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                              Write(Exampaper.RandomAdd);

            
            #line default
            #line hidden
WriteLiteral("\", id:\"ExamRan\", height: 200});\r\n        });\r\n        //导入新试题\r\n        $(\"#btExpo" +
"rtNewQuestion\").bind(\"click\", function() {\r\n            art.dialog.load(\"/Exampa" +
"per/ImportQuestions?id=0\", {title: \"");


            
            #line 651 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                                                   Write(Exampaper.ImportQuestion);

            
            #line default
            #line hidden
WriteLiteral(@""",id:""NewQue""});
        });
        //组卷规则
        $(""#btQuestionRule"").bind(""click"", function() {
            art.dialog.load(""/Exampaper/ExampaperRule"", {title: ""组卷规则"",id:""ExamRule"", height: 200 });
        });
    });
    //删除试题

    function Delete(id) {
        var hiddID = ""#QuestionID"" + id;
        $(hiddID).remove();
        StatType();
        upScore();
        order();
        Score();
        qtype();
        statID();
    }

//验证正整数

    function verifyInput(obj) {
        var r = /^[0-9]*[1-9][0-9]*$/;
        if (obj.value != """" && obj.value != null) {
            if (!(r.test(obj.value))) {
                art.dialog.tips(""请输入正整数"", 3);
                //art.dialog({ title: '");


            
            #line 678 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请输入正整数"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
                obj.value = """";
                return false;
            } else {
                if (parseInt(obj.value) > 100) {
                    obj.value = 100;
                    art.dialog.tips(""请输入1-100的正整数"", 3);
                    //art.dialog({ title: '");


            
            #line 685 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请输入1-100的正整数"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
                    return false;
                }
            }
        } else {
            art.dialog.tips(""请输入正整数"", 3);
            //art.dialog({ title: '");


            
            #line 691 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请输入正整数"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
            obj.value = """";
            return false;
        }
    }
    //验证规则正整数

    function verifyInput1(obj) {
        var r = /^[0-9]*[1-9][0-9]*$/;
        if (obj.value != """" && obj.value != null) {
            if (!(r.test(obj.value))) {
                art.dialog.tips(""请输入正整数"", 3);
                //art.dialog({ title: '");


            
            #line 703 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                  Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请输入正整数"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
                obj.value = 0;
                return false;
            } else {
                if (parseInt(obj.value) > 100) {
                    obj.value = 0;
                    art.dialog.tips(""请输入1-100的正整数"", 3);
                    //art.dialog({ title: '");


            
            #line 710 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                                      Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请输入1-100的正整数"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
                    return false;
                }
            }
        } else {
            art.dialog.tips(""请输入正整数"", 3);
            //art.dialog({ title: '");


            
            #line 716 "..\..\Views\Exampaper\ExampaperEdit.cshtml"
                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: ""请输入正整数"", width: 400, height: 100, fixed: true, lock: true, time: 3 });
            obj.value = 0;
            return false;
        }
    }
    //删除

    function bindRule() {
        $(""a[name=rmRule]"").unbind().click(function() {
            $(this).parent().remove();
            StatType();
            upScore();
            order();
            Score();
            qtype();
            statID();
        });
    }
</script>
");


        }
    }
}
#pragma warning restore 1591
