#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Exampaper
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
    using LiXinModels.Examination.DBModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Exampaper/ExampaperSortEdit.cshtml")]
    public class ExampaperSortEdit : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExampaperSortEdit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
  
    Layout = null;
    var model = ViewData["model"] as tbExampaperSort;
    string fsort = Request.QueryString["fatherID"] == null ? "0" : Request.QueryString["fatherID"];


            
            #line default
            #line hidden
WriteLiteral("<div class=\"centerbody\">\r\n    <form id=\"ExampaperSortForm\" method=\"post\" action=\"" +
"\">\r\n        <input id=\"hidfatherID\" name=\"hidfatherID\" type=\"hidden\" value=\"");


            
            #line 10 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                                   Write(ViewData["fatherID"]);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <table class=\"tab-Form\">\r\n            <tr>\r\n                <td cla" +
"ss=\"Tit span10\"><span class=\"red\">*</span>");


            
            #line 13 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                            Write(Exampaper.FatherSort);

            
            #line default
            #line hidden
WriteLiteral("：</td>\r\n                <td class=\"span30\">\r\n                    <input type=\"hid" +
"den\" id=\"fatherSort\" class=\"span20\" name=\"fatherSort\" value=\"");


            
            #line 15 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                                                            Write(fsort);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                    <div title=\"");


            
            #line 16 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                           Write(ViewData["fatherModel"]);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 16 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                     Write(ViewData["fatherModel"]);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n             " +
"   <td class=\"Tit\"><span class=\"red\">*</span>");


            
            #line 20 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                     Write(Exampaper.SortName);

            
            #line default
            #line hidden
WriteLiteral("：</td>\r\n                <td>\r\n                    <input type=\"text\" id=\"txtSortN" +
"ame\" class=\"span20\" name=\"txtSortName\" value=\"");


            
            #line 22 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                                                             Write(model.Title);

            
            #line default
            #line hidden
WriteLiteral("\" maxlength=\"30\"  />\r\n                    <div id=\"nameTip\"></div>\r\n             " +
"   </td>\r\n            </tr>\r\n            <tr>\r\n                <td class=\"Tit\">");


            
            #line 27 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                           Write(Exampaper.SortDescription);

            
            #line default
            #line hidden
WriteLiteral("：</td>\r\n                <td>\r\n                    <textarea class=\"span20\" id=\"tx" +
"tMemo\" name=\"txtMemo\" maxlength=\"200\" onkeyup=\" TextearaMaxlength(this); \" >");


            
            #line 29 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                                                                                           Write(model.Description);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n        " +
"        <td colspan=\"2\" class=\"tc\">\r\n                    <a id=\"btnSaveSort\" cla" +
"ss=\"btn\" onclick=\" $(this).submit(); \">");


            
            #line 34 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                                             Write(Exampaper.Save);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                </td>
            </tr>
        </table>
    </form>
</div>
<script type=""text/javascript"">
    $(document).ready(function() {
//        jQuery.validator.addMethod(""stringCheck"", function (value, element) {
//            return this.optional(element) || /^[\u0391-\uFFE5\w]+$/.test(value);
//        }, ""只能包括中文字、英文字母、数字和下划线"");

        $(""#ExampaperSortForm"").validate({
            rules: {
                txtSortName: {
                    required: true,
                    maxlength: 30,
//                    stringCheck:true,
                    remote: {
                        type: ""POST"",
                        dataType: ""json"",
                        url: ""/Exampaper/CheckExampaperSort"",
                        data: { etitle: function() { return $.trim($(""#txtSortName"").val()); }, eid: function() { return ");


            
            #line 56 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                                                                                     Write(model._id);

            
            #line default
            #line hidden
WriteLiteral(@"; }, fid: function() { return jQuery(""#hidfatherID"").val(); } }
                    }
                },
                txtMemo: {
                    maxlength: 200
                }
            },
            messages: {
                txtSortName: {
                    required: ""请填写名称"",
                    maxlength: ""长度必须小于30个字符"",
//                    stringCheck: ""只能包括中文字、英文字母、数字和下划线"",
                    remote: ""试卷库已经存在""
                },
                txtMemo: {
                    maxlength: ""长度必须小于200个字符""
                }
            },
            submitHandler: function(form) {
                jQuery(form).ajaxSubmit({
                    url: '/Exampaper/SubmitExampaperSort?id=");


            
            #line 76 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                                        Write(model._id);

            
            #line default
            #line hidden
WriteLiteral(@"',
                    type: ""post"",
                    dataType: ""json"",
                    success: function(data) {
                        if (data.result == 1) {
                            art.dialog.tips(data.content, 1.5);
                            //art.dialog({ title: '");


            
            #line 82 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, width: 200, height: 50, fixed: true, lock: true, time: 3 });
                            initExampaperSort();
                            InitializeTargetList(getUrlParms());
                            art.dialog.list['SortEdit'].close();
                        } else {
                            art.dialog.tips(data.content, 1.5);
                            //art.dialog({ title: '");


            
            #line 88 "..\..\Views\Exampaper\ExampaperSortEdit.cshtml"
                                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: data.content, width: 200, height: 50, fixed: true, lock: true, time: " +
"3 });\r\n                        }\r\n                    }\r\n                });\r\n  " +
"          }\r\n        });\r\n    });\r\n</script>");


        }
    }
}
#pragma warning restore 1591
