#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Exampaper
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Exampaper\ImportQuestions.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Exampaper/ImportQuestions.cshtml")]
    public class ImportQuestions : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ImportQuestions()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Exampaper\ImportQuestions.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral(@"<form id=""formQuestion"" method=""post"" enctype=""multipart/form-data"" action="""">
    <div class=""centerbody"">
        <table class=""tab-Form"">
            <tr>
                <td class=""Tit""><span class=""must"">*</span>知识点：</td>
                <td><select id=""keylist""></select></td>
            </tr>
            <tr>
                <td class=""Tit""><span class=""must"">*</span>");


            
            #line 13 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                      Write(Question.Question_QuestionManage_Sort);

            
            #line default
            #line hidden
WriteLiteral(@"：</td>
                <td>
                    <input id=""selQuestionSort"" name=""selQuestionSort"" type=""hidden"" />
                    <input id=""sortName"" type=""text""class=""span20"" disabled=""disabled"" readonly=""readonly"" />
                    <input type=""button"" class=""btn btn-co"" value=""选择题库"" onclick="" selectQuestionSort(); "" />
                </td>
            </tr>
            <tr>
                <td class=""Tit""><span class=""must"">*</span>");


            
            #line 21 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                      Write(Question.Question_QuestionManage_QuestionTemplete);

            
            #line default
            #line hidden
WriteLiteral(@"：</td>
                <td>
                    <input type=""file"" id=""questionExcel"" name=""questionExcel"" class=""span20"" />
                </td>
            </tr>
            <tr>
                <td colspan=""2"" class=""tc"">
                    <a id=""submitExcel"" title=""");


            
            #line 28 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                          Write(Exampaper.OK);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\">");


            
            #line 28 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                                     Write(Exampaper.OK);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                </td>
            </tr>
        </table>
    </div>
</form>
<script type=""text/javascript"">
    function selectQuestionSort() {
        var openurl = ""/Question/GetAllQuestionSortTree"";
        $.getJSON(openurl + ""?t="" + new Date(), function(data) {
            art.dialog({
                title: """);


            
            #line 39 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                   Write(Question.Question_QuestionManage_SelectSort);

            
            #line default
            #line hidden
WriteLiteral(@""",
                id: ""QueSort"",
                lock: true,
                fixed: true,
                width: 400,
                height: 300,
                time: false,
                content: ""<div class='treeview-box span30'><div class='tree-list'>"" + data + ""</div></div>"",
                close: function() {
                    $('#popIframe').hide();
//                    $("".aui_content"").css({ ""height"": ""auto"", ""width"": ""auto"", ""overflow"": ""auto"" });
                }
            });
            $(""#navigation"").treeview({
                persist: ""location"",
                collapsed: false,
                unique: false
            });
            $(""#navigation>li>ul>li>div"").each(function () {
                $(this).click();
            });
//            $("".aui_content"").css({ ""height"": ""300px"", ""overflow"": ""auto"" });
        });
    }

    function selectSort(sortID, obj) {
        if (parseInt(sortID) > 0) {
            $(""#selQuestionSort"").val(sortID);
            $(""#sortName"").val($(obj).text());
            art.dialog.list[""QueSort""].close();
        } else {
            art.dialog.tips('");


            
            #line 70 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                        Write(Question.Question_QuestionManage_Tip_SelectSort);

            
            #line default
            #line hidden
WriteLiteral("\', 1.5);\r\n        }\r\n    }\r\n\r\n    $(\"#submitExcel\").bind(\"click\", function() {\r\n " +
"       if ($(\"#sortName\").val() == \"\" || $(\"#sortName\").val() == null) {\r\n      " +
"      //art.dialog({ title: \'");


            
            #line 76 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: \'请选择题库\', fixed: true, lock: true, time: 3 });\r\n            art.dialog" +
".tips(\'请选择题库\', 1.5);\r\n            return;\r\n        }\r\n        if ($(\"#questionEx" +
"cel\").val() == \"\" || $(\"#questionExcel\").val() == null) {\r\n            //art.dia" +
"log({ title: \'");


            
            #line 81 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: \'请选择试题模板\', fixed: true, lock: true, time: 3 });\r\n            art.dial" +
"og.tips(\'请选择试题模板\', 1.5);\r\n            return;\r\n        }\r\n        $(\"#submitExce" +
"l\").attr(\"disabled\", \"disabled\");\r\n        $(this).parent().find(\"span\").remove(" +
");\r\n        $(this).after(\'<span class=\"red\">正在导入，请稍后……</span>\');\r\n        $(\"#f" +
"ormQuestion\").submitForm({\r\n            url: \'/Question/SubmitImportQuestion?sor" +
"tID=\' + $(\"#selQuestionSort\").val() + \'&key=\' + $(\"#keylist\").val(),\r\n          " +
"  callback: function(data) {\r\n                $(\"#submitExcel\").removeAttr(\"disa" +
"bled\");\r\n                $(\"#submitExcel\").parent().find(\"span\").remove();\r\n    " +
"            if (data.result == 1) {\r\n                    var strhtml = \'\';\r\n    " +
"                var datelist = data.itemArray;\r\n                    for (var i =" +
" 1; i <= datelist.length; i++) {\r\n                        var Juid = \"QuestionID" +
"\" + datelist[i - 1].id;\r\n                        //判断题库是否存在\r\n                   " +
"     if (document.getElementById(Juid) == null) {\r\n                            s" +
"trhtml += \'<div class=\"QSingle\" id=\"QuestionID\' + datelist[i - 1].id + \'\">\';\r\n  " +
"                          strhtml += \'<input type=\"hidden\" name=\"\' + datelist[i " +
"- 1].QuestionType + \'\" value=\"\' + datelist[i - 1].id + \'|\' + datelist[i - 1].Que" +
"stionType + \'\"/>\';\r\n                            strhtml += \'<div class=\"title\"><" +
"div class=\"info\"><input id=\"Order\' + datelist[i - 1].id + \'\" readonly=\"readonly\"" +
" type=\"text\" name=\"Order\' + datelist[i - 1].id + \'\"  value=\"\' + i + \'\" maxlength" +
"=\"3\" />.\';\r\n                            strhtml += \'[ <input id=\"Score\' + dateli" +
"st[i - 1].id + \'\"  type=\"text\" name=\"Score\' + datelist[i - 1].id + \'\" readonly=\"" +
"readonly\" value=\"1\" onkeyup=\"verifyInput(this)\" maxlength=\"3\" /> ");


            
            #line 103 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                                                                                                                                                                                Write(Exampaper.Fen);

            
            #line default
            #line hidden
WriteLiteral(" ]</div>\';\r\n                            strhtml += \'<h5>\' + datelist[i - 1].Quest" +
"ionContent + \'<div class=\"do\"><a href=\"#");


WriteLiteral("@\" onclick=\"Delete(\' + datelist[i - 1].id + \')\" title=\"");


            
            #line 104 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                                                                                                                                Write(CommonLanguage.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""icon idel""></a></div></h5></div>';
                            strhtml += '<div class=""content"">';
                            switch (datelist[i - 1].QuestionType) {
                            case 1:
                                strhtml += '<textarea class=""Boxarea"" disabled=""disabled"" ></textarea>';
                                break;
                            case 2:
                                for (var j = 0; j < datelist[i - 1].QuestionAnswer.length; j++) {
                                    strhtml += '<div><input type=""radio""  disabled=""disabled"" />' + String.fromCharCode((65 + j)) + '.' + datelist[i - 1].QuestionAnswer[j].Answer + '</div>';
                                }
                                break;
                            case 3:
                                for (var k = 0; k < datelist[i - 1].QuestionAnswer.length; k++) {
                                    strhtml += '<div><input type=""checkbox"" disabled=""disabled"" />' + String.fromCharCode((65 + k)) + '.' + datelist[i - 1].QuestionAnswer[k].Answer + '</div>';
                                }
                                break;
                            case 4:
                                strhtml += '<div><input type=""radio"" disabled=""disabled"" /><label>");


            
            #line 121 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                                                             Write(Exampaper.eTrue);

            
            #line default
            #line hidden
WriteLiteral("</label></div>\';\r\n                                strhtml += \'<div><input type=\"r" +
"adio\" disabled=\"disabled\" /><label>");


            
            #line 122 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                                                                             Write(Exampaper.eFalse);

            
            #line default
            #line hidden
WriteLiteral("</label></div>\';\r\n                                break;\r\n                       " +
"     case 6:\r\n                                if (datelist[i - 1].QuestionAnswer" +
"[0].AnswerType == 0) {\r\n                                    strhtml += \'<textare" +
"a class=\"Boxarea\" disabled=\"disabled\" ></textarea>\';\r\n                          " +
"      } else if (datelist[i - 1].QuestionAnswer[0].AnswerType == 1) {\r\n         " +
"                           for (var q = 0; q < datelist[i - 1].QuestionAnswer.le" +
"ngth; q++) {\r\n                                        strhtml += \'<div><input ty" +
"pe=\"radio\" disabled=\"disabled\" />\' + String.fromCharCode((65 + q)) + \'.\' + datel" +
"ist[i - 1].QuestionAnswer[q].Answer + \'</div>\';\r\n                               " +
"     }\r\n                                } else {\r\n                              " +
"      for (var y = 0; y < datelist[i - 1].QuestionAnswer.length; y++) {\r\n       " +
"                                 strhtml += \'<div><input type=\"checkbox\" disable" +
"d=\"disabled\" />\' + String.fromCharCode((65 + y)) + \'.\' + datelist[i - 1].Questio" +
"nAnswer[y].Answer + \'</div>\';\r\n                                    }\r\n          " +
"                      }\r\n                                break;\r\n               " +
"             }\r\n                            strhtml += \'</div></div>\';\r\n        " +
"                }\r\n                    }\r\n                    $(\"#divExamQuestio" +
"ns\").append(strhtml);\r\n                    order();\r\n                    StatTyp" +
"e();\r\n                    Score();\r\n                    statID();\r\n             " +
"       qtype();\r\n                    upScore();\r\n                    art.dialog." +
"list[\"NewQue\"].close();\r\n                } else\r\n                    //art.dialo" +
"g({ title: \'");


            
            #line 150 "..\..\Views\Exampaper\ImportQuestions.cshtml"
                                      Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral(@"', content: data.content, fixed: true, lock: true, time: 3 });
                    art.dialog.tips(data.content, 1.5);
            }
        }).submit();
    });

    $(document).ready(function() {
        //知识点填充
        $.getJSON(""/KnowledgeKey/GetKnowledgeKey?t="" + new Date(), function(datalist) {
            var html = """";
            for (var ii = 0; ii < datalist.length; ii++) {
                html += '<option value=""' + datalist[ii].id + '"">' + datalist[ii].name + '</option>';
            }
            $(""#keylist"").append(html);
            $(""#hiddenSelQuestionKey"").val($(""#keylist"").val());
            $(""#keylist"").bind(""change"", function() {
                $(""#hiddenSelQuestionKey"").val($(""#keylist"").val());
            });
        });
    });

</script>");


        }
    }
}
#pragma warning restore 1591
