//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailContentLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailContentLanguage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiXinLanguage.EmailContentLanguage", typeof(EmailContentLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜，您申请的“&lt;a href=&apos;/TrainManage/PostTrainingList&apos;&gt;{0}&lt;/a&gt;”通过了，赶快来学习吧。 的本地化字符串。
        /// </summary>
        public static string ApprovalPassed {
            get {
                return ResourceManager.GetString("ApprovalPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批通过 的本地化字符串。
        /// </summary>
        public static string ApprovalPassed_title {
            get {
                return ResourceManager.GetString("ApprovalPassed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很遗憾，您申请的&quot;&lt;a href=&apos;/TrainManage/TrainApply&apos;&gt;{0}&lt;/a&gt;”被拒绝了，继续努力吧！ 的本地化字符串。
        /// </summary>
        public static string ApprovalRefused {
            get {
                return ResourceManager.GetString("ApprovalRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审批拒绝 的本地化字符串。
        /// </summary>
        public static string ApprovalRefused_title {
            get {
                return ResourceManager.GetString("ApprovalRefused_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的“&lt;a href=&apos;/TrainManage/FunctionLearningList&apos;&gt;{0}&lt;/a&gt;”已经学习7天啦，要加油喔！ 的本地化字符串。
        /// </summary>
        public static string CourseLearning {
            get {
                return ResourceManager.GetString("CourseLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自主学习 的本地化字符串。
        /// </summary>
        public static string CourseLearning_title {
            get {
                return ResourceManager.GetString("CourseLearning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喔，糟糕！您报名的大赛“{0}”被删除了！ 的本地化字符串。
        /// </summary>
        public static string DeleteCompete {
            get {
                return ResourceManager.GetString("DeleteCompete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大赛删除 的本地化字符串。
        /// </summary>
        public static string DeleteCompete_title {
            get {
                return ResourceManager.GetString("DeleteCompete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您有一门考试“&lt;a href=&apos;{0}&apos;&gt;{1}&lt;/a&gt;”需要参加，请尽快哦！ 的本地化字符串。
        /// </summary>
        public static string ExamPublish {
            get {
                return ResourceManager.GetString("ExamPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试安排 的本地化字符串。
        /// </summary>
        public static string ExamPublish_title {
            get {
                return ResourceManager.GetString("ExamPublish_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜，您参与的“&lt;a href=&apos;/TrainManage/PostTrainingList&apos;&gt;{0}&lt;/a&gt;”学习，已经顺利通过喽，快去看看自己的成绩吧！ 的本地化字符串。
        /// </summary>
        public static string LearningPassed {
            get {
                return ResourceManager.GetString("LearningPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晋升学习通过 的本地化字符串。
        /// </summary>
        public static string LearningPassed_title {
            get {
                return ResourceManager.GetString("LearningPassed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}的{1}申请了“{2}”需要您的审批，赶快去看看吧。进行审批，请点击&lt;a href=&apos;/TrainManage/TrainApprove&apos;&gt;这里&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string NewApproval {
            get {
                return ResourceManager.GetString("NewApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的审批 的本地化字符串。
        /// </summary>
        public static string NewApproval_title {
            get {
                return ResourceManager.GetString("NewApproval_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新的专题“&lt;a href=&apos;/TrainManage/SpecialTrainingLearnList&apos;&gt;{0}&lt;/a&gt;”需要参加，快去看看吧！ 的本地化字符串。
        /// </summary>
        public static string NewSpecialTrain {
            get {
                return ResourceManager.GetString("NewSpecialTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增专题 的本地化字符串。
        /// </summary>
        public static string NewSpecialTrain_title {
            get {
                return ResourceManager.GetString("NewSpecialTrain_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜，您参与的“{0}”已经顺利通过喽，快去看看吧！ 的本地化字符串。
        /// </summary>
        public static string PassExam_Content {
            get {
                return ResourceManager.GetString("PassExam_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试通过通知 的本地化字符串。
        /// </summary>
        public static string PassExam_Title {
            get {
                return ResourceManager.GetString("PassExam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新大赛“{0}”可以参加，赶紧去报名吧！ 的本地化字符串。
        /// </summary>
        public static string PublishCompete {
            get {
                return ResourceManager.GetString("PublishCompete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大赛发布 的本地化字符串。
        /// </summary>
        public static string PublishCompete_title {
            get {
                return ResourceManager.GetString("PublishCompete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜，{0}大赛获奖名单已公布，您获得了“{1}”快去看看吧！ 的本地化字符串。
        /// </summary>
        public static string PublishPrize {
            get {
                return ResourceManager.GetString("PublishPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大赛获奖通知 的本地化字符串。
        /// </summary>
        public static string PublishPrize_title {
            get {
                return ResourceManager.GetString("PublishPrize_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜，您参加的“{0}大赛{1}赛程”成功晋级了！ 的本地化字符串。
        /// </summary>
        public static string PublishPromotion {
            get {
                return ResourceManager.GetString("PublishPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大赛晋级通知 的本地化字符串。
        /// </summary>
        public static string PublishPromotion_title {
            get {
                return ResourceManager.GetString("PublishPromotion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您参与的“&lt;a href=&apos;/TrainManage/SpecialTrainingLearnList&apos;&gt;{0}&lt;/a&gt;”学习已结束，恭喜您顺利通过，感谢您的参与。 的本地化字符串。
        /// </summary>
        public static string SpecialTrainPassed {
            get {
                return ResourceManager.GetString("SpecialTrainPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过专题学习 的本地化字符串。
        /// </summary>
        public static string SpecialTrainPassed_title {
            get {
                return ResourceManager.GetString("SpecialTrainPassed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您参与的“&lt;a href=&apos;/TrainManage/SpecialTrainingLearnList&apos;&gt;{0}&lt;/a&gt;”学习已结束，很遗憾您没有通过，感谢您的参与。 的本地化字符串。
        /// </summary>
        public static string SpecialTrainRefused {
            get {
                return ResourceManager.GetString("SpecialTrainRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未通过专题学习 的本地化字符串。
        /// </summary>
        public static string SpecialTrainRefused_title {
            get {
                return ResourceManager.GetString("SpecialTrainRefused_title", resourceCulture);
            }
        }
    }
}
