//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18047
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavigateMenuLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigateMenuLanguage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiXinLanguage.NavigateMenuLanguage", typeof(NavigateMenuLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增试卷 的本地化字符串。
        /// </summary>
        public static string AddExampaper {
            get {
                return ResourceManager.GetString("AddExampaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度计划分解 的本地化字符串。
        /// </summary>
        public static string AddMonthPlan {
            get {
                return ResourceManager.GetString("AddMonthPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配权限 的本地化字符串。
        /// </summary>
        public static string AssignRight {
            get {
                return ResourceManager.GetString("AssignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤管理 的本地化字符串。
        /// </summary>
        public static string AttendceManage {
            get {
                return ResourceManager.GetString("AttendceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试授权 的本地化字符串。
        /// </summary>
        public static string AuthorizedExamManage {
            get {
                return ResourceManager.GetString("AuthorizedExamManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览问卷 的本地化字符串。
        /// </summary>
        public static string BrowsePaper {
            get {
                return ResourceManager.GetString("BrowsePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题预览 的本地化字符串。
        /// </summary>
        public static string BrowseQuestion {
            get {
                return ResourceManager.GetString("BrowseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看答卷情况 的本地化字符串。
        /// </summary>
        public static string BrowseSurvey {
            get {
                return ResourceManager.GetString("BrowseSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑教室 的本地化字符串。
        /// </summary>
        public static string ClassRoomEdit {
            get {
                return ResourceManager.GetString("ClassRoomEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教室管理 的本地化字符串。
        /// </summary>
        public static string ClassRoomManage {
            get {
                return ResourceManager.GetString("ClassRoomManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胜任力课程 的本地化字符串。
        /// </summary>
        public static string CompetencyCourseShowList {
            get {
                return ResourceManager.GetString("CompetencyCourseShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程报名详情 的本地化字符串。
        /// </summary>
        public static string CourseApplyDetail {
            get {
                return ResourceManager.GetString("CourseApplyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程预订状态查询（部门负责人） 的本地化字符串。
        /// </summary>
        public static string CourseDeptSubscribe {
            get {
                return ResourceManager.GetString("CourseDeptSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程预订状态详情 的本地化字符串。
        /// </summary>
        public static string CourseDeptSubscribeDetail {
            get {
                return ResourceManager.GetString("CourseDeptSubscribeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string CourseDetail {
            get {
                return ResourceManager.GetString("CourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程管理 的本地化字符串。
        /// </summary>
        public static string CourseManage {
            get {
                return ResourceManager.GetString("CourseManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程预订查询 的本地化字符串。
        /// </summary>
        public static string CourseSubscribe {
            get {
                return ResourceManager.GetString("CourseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集中授课课程预订详情 的本地化字符串。
        /// </summary>
        public static string CourseSubscribeDetail {
            get {
                return ResourceManager.GetString("CourseSubscribeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑部门 的本地化字符串。
        /// </summary>
        public static string DeptEdit {
            get {
                return ResourceManager.GetString("DeptEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门管理 的本地化字符串。
        /// </summary>
        public static string DeptManage {
            get {
                return ResourceManager.GetString("DeptManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑考试 的本地化字符串。
        /// </summary>
        public static string EditExamination {
            get {
                return ResourceManager.GetString("EditExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑试卷 的本地化字符串。
        /// </summary>
        public static string EditExampaper {
            get {
                return ResourceManager.GetString("EditExampaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑知识点 的本地化字符串。
        /// </summary>
        public static string EditKnowledgeKey {
            get {
                return ResourceManager.GetString("EditKnowledgeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑政策 的本地化字符串。
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复评管理 的本地化字符串。
        /// </summary>
        public static string EvaluationManage {
            get {
                return ResourceManager.GetString("EvaluationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试详情 的本地化字符串。
        /// </summary>
        public static string ExaminationDetail {
            get {
                return ResourceManager.GetString("ExaminationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试管理 的本地化字符串。
        /// </summary>
        public static string ExaminationList {
            get {
                return ResourceManager.GetString("ExaminationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试管理 的本地化字符串。
        /// </summary>
        public static string ExaminationManage {
            get {
                return ResourceManager.GetString("ExaminationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试卷管理 的本地化字符串。
        /// </summary>
        public static string ExampaperManage {
            get {
                return ResourceManager.GetString("ExampaperManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 答卷详情 的本地化字符串。
        /// </summary>
        public static string ExamTestDetail {
            get {
                return ResourceManager.GetString("ExamTestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线考试 的本地化字符串。
        /// </summary>
        public static string ExamTestOnline {
            get {
                return ResourceManager.GetString("ExamTestOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 政策管理 的本地化字符串。
        /// </summary>
        public static string FAQ_NoteManage {
            get {
                return ResourceManager.GetString("FAQ_NoteManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 政策管理 的本地化字符串。
        /// </summary>
        public static string FAQManage {
            get {
                return ResourceManager.GetString("FAQManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训级别变更 的本地化字符串。
        /// </summary>
        public static string GradeManage {
            get {
                return ResourceManager.GetString("GradeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑群组 的本地化字符串。
        /// </summary>
        public static string GroupEdit {
            get {
                return ResourceManager.GetString("GroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组管理 的本地化字符串。
        /// </summary>
        public static string GroupManage {
            get {
                return ResourceManager.GetString("GroupManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识点管理 的本地化字符串。
        /// </summary>
        public static string KnowledgeKeyManage {
            get {
                return ResourceManager.GetString("KnowledgeKeyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志管理 的本地化字符串。
        /// </summary>
        public static string LogManage {
            get {
                return ResourceManager.GetString("LogManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改个人资料 的本地化字符串。
        /// </summary>
        public static string ModifyPersonalInfo {
            get {
                return ResourceManager.GetString("ModifyPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度大纲 的本地化字符串。
        /// </summary>
        public static string MonthPlan {
            get {
                return ResourceManager.GetString("MonthPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度大纲详情 的本地化字符串。
        /// </summary>
        public static string MonthPlanDetail {
            get {
                return ResourceManager.GetString("MonthPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的月度计划课程表 的本地化字符串。
        /// </summary>
        public static string MonthPlanScheduleTask {
            get {
                return ResourceManager.GetString("MonthPlanScheduleTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的申请 的本地化字符串。
        /// </summary>
        public static string MyApply {
            get {
                return ResourceManager.GetString("MyApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时申请审批详情 的本地化字符串。
        /// </summary>
        public static string MyApprovalOutTimeLeaveInfor {
            get {
                return ResourceManager.GetString("MyApprovalOutTimeLeaveInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已预订的课程 的本地化字符串。
        /// </summary>
        public static string MyCourse {
            get {
                return ResourceManager.GetString("MyCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的可预订课程 的本地化字符串。
        /// </summary>
        public static string MyCourseSubscribe {
            get {
                return ResourceManager.GetString("MyCourseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的考试 的本地化字符串。
        /// </summary>
        public static string MyExamination {
            get {
                return ResourceManager.GetString("MyExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的需求 的本地化字符串。
        /// </summary>
        public static string MySurvey {
            get {
                return ResourceManager.GetString("MySurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的培训首页 的本地化字符串。
        /// </summary>
        public static string MyTrainIndex {
            get {
                return ResourceManager.GetString("MyTrainIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告详情 的本地化字符串。
        /// </summary>
        public static string NoteDetail {
            get {
                return ResourceManager.GetString("NoteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告列表 的本地化字符串。
        /// </summary>
        public static string NoteManage {
            get {
                return ResourceManager.GetString("NoteManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告详情 的本地化字符串。
        /// </summary>
        public static string NoteManageDetail {
            get {
                return ResourceManager.GetString("NoteManageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数配置 的本地化字符串。
        /// </summary>
        public static string ParamConfig {
            get {
                return ResourceManager.GetString("ParamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员管理 的本地化字符串。
        /// </summary>
        public static string PeopleManage {
            get {
                return ResourceManager.GetString("PeopleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训计划管理 的本地化字符串。
        /// </summary>
        public static string PlanManage {
            get {
                return ResourceManager.GetString("PlanManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑岗位 的本地化字符串。
        /// </summary>
        public static string PostEdit {
            get {
                return ResourceManager.GetString("PostEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位管理 的本地化字符串。
        /// </summary>
        public static string PostManage {
            get {
                return ResourceManager.GetString("PostManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增试题 的本地化字符串。
        /// </summary>
        public static string QuestionAdd {
            get {
                return ResourceManager.GetString("QuestionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑试题 的本地化字符串。
        /// </summary>
        public static string QuestionEdit {
            get {
                return ResourceManager.GetString("QuestionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 题库管理 的本地化字符串。
        /// </summary>
        public static string QuestionManage {
            get {
                return ResourceManager.GetString("QuestionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工复评 的本地化字符串。
        /// </summary>
        public static string ReEvaluation {
            get {
                return ResourceManager.GetString("ReEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        public static string RightManage {
            get {
                return ResourceManager.GetString("RightManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色 的本地化字符串。
        /// </summary>
        public static string RoleEdit {
            get {
                return ResourceManager.GetString("RoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门问卷审核明细 的本地化字符串。
        /// </summary>
        public static string SurveyCheckDeatils {
            get {
                return ResourceManager.GetString("SurveyCheckDeatils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷审核 的本地化字符串。
        /// </summary>
        public static string SurveyCheckForDept {
            get {
                return ResourceManager.GetString("SurveyCheckForDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷审核汇总 的本地化字符串。
        /// </summary>
        public static string SurveyCheckForOffice {
            get {
                return ResourceManager.GetString("SurveyCheckForOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑调查 的本地化字符串。
        /// </summary>
        public static string SurveyEdit {
            get {
                return ResourceManager.GetString("SurveyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑问卷 的本地化字符串。
        /// </summary>
        public static string SurveyExampaperEdit {
            get {
                return ResourceManager.GetString("SurveyExampaperEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷管理 的本地化字符串。
        /// </summary>
        public static string SurveyExampaperList {
            get {
                return ResourceManager.GetString("SurveyExampaperList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调查管理 的本地化字符串。
        /// </summary>
        public static string SurveyManage {
            get {
                return ResourceManager.GetString("SurveyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理首页 的本地化字符串。
        /// </summary>
        public static string SystemManageIndex {
            get {
                return ResourceManager.GetString("SystemManageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讲师管理 的本地化字符串。
        /// </summary>
        public static string TeacherIndex {
            get {
                return ResourceManager.GetString("TeacherIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试评估 的本地化字符串。
        /// </summary>
        public static string TestingAssessment {
            get {
                return ResourceManager.GetString("TestingAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时审批申请 的本地化字符串。
        /// </summary>
        public static string TimeOutApply {
            get {
                return ResourceManager.GetString("TimeOutApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时审批申请详情 的本地化字符串。
        /// </summary>
        public static string TimeOutApplyDetail {
            get {
                return ResourceManager.GetString("TimeOutApplyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时申请审批管理 的本地化字符串。
        /// </summary>
        public static string TimeOutApproval {
            get {
                return ResourceManager.GetString("TimeOutApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时申请审批详情 的本地化字符串。
        /// </summary>
        public static string TimeOutApprovalDetail {
            get {
                return ResourceManager.GetString("TimeOutApprovalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训级别维护 的本地化字符串。
        /// </summary>
        public static string TrainGrade {
            get {
                return ResourceManager.GetString("TrainGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护级别详情 的本地化字符串。
        /// </summary>
        public static string TrainGradeDetail {
            get {
                return ResourceManager.GetString("TrainGradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户信息 的本地化字符串。
        /// </summary>
        public static string UserBaseInfo {
            get {
                return ResourceManager.GetString("UserBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户详情 的本地化字符串。
        /// </summary>
        public static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑人员 的本地化字符串。
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指纹管理 的本地化字符串。
        /// </summary>
        public static string UserFingerInfor {
            get {
                return ResourceManager.GetString("UserFingerInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户管理 的本地化字符串。
        /// </summary>
        public static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string VideoCourseMain {
            get {
                return ResourceManager.GetString("VideoCourseMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频管理 的本地化字符串。
        /// </summary>
        public static string VideoManage {
            get {
                return ResourceManager.GetString("VideoManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划管理 的本地化字符串。
        /// </summary>
        public static string YearPlan {
            get {
                return ResourceManager.GetString("YearPlan", resourceCulture);
            }
        }
    }
}
