//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinLanguage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavigateMenuLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigateMenuLanguage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiXinLanguage.NavigateMenuLanguage", typeof(NavigateMenuLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增试卷 的本地化字符串。
        /// </summary>
        public static string AddExampaper {
            get {
                return ResourceManager.GetString("AddExampaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度计划分解 的本地化字符串。
        /// </summary>
        public static string AddMonthPlan {
            get {
                return ResourceManager.GetString("AddMonthPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划预览 的本地化字符串。
        /// </summary>
        public static string AppYearPlanDetail {
            get {
                return ResourceManager.GetString("AppYearPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配权限 的本地化字符串。
        /// </summary>
        public static string AssignRight {
            get {
                return ResourceManager.GetString("AssignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤管理 的本地化字符串。
        /// </summary>
        public static string AttendceManage {
            get {
                return ResourceManager.GetString("AttendceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试授权 的本地化字符串。
        /// </summary>
        public static string AuthorizedExamManage {
            get {
                return ResourceManager.GetString("AuthorizedExamManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览问卷 的本地化字符串。
        /// </summary>
        public static string BrowsePaper {
            get {
                return ResourceManager.GetString("BrowsePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览试题 的本地化字符串。
        /// </summary>
        public static string BrowseQuestion {
            get {
                return ResourceManager.GetString("BrowseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看答卷情况 的本地化字符串。
        /// </summary>
        public static string BrowseSurvey {
            get {
                return ResourceManager.GetString("BrowseSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑教室 的本地化字符串。
        /// </summary>
        public static string ClassRoomEdit {
            get {
                return ResourceManager.GetString("ClassRoomEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教室管理 的本地化字符串。
        /// </summary>
        public static string ClassRoomManage {
            get {
                return ResourceManager.GetString("ClassRoomManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胜任力课程 的本地化字符串。
        /// </summary>
        public static string CompetencyCourseShowList {
            get {
                return ResourceManager.GetString("CompetencyCourseShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程报名详情 的本地化字符串。
        /// </summary>
        public static string CourseApplyDetail {
            get {
                return ResourceManager.GetString("CourseApplyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程预订状态查询（部门负责人） 的本地化字符串。
        /// </summary>
        public static string CourseDeptSubscribe {
            get {
                return ResourceManager.GetString("CourseDeptSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程预订状态详情 的本地化字符串。
        /// </summary>
        public static string CourseDeptSubscribeDetail {
            get {
                return ResourceManager.GetString("CourseDeptSubscribeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string CourseDetail {
            get {
                return ResourceManager.GetString("CourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程管理 的本地化字符串。
        /// </summary>
        public static string CourseManage {
            get {
                return ResourceManager.GetString("CourseManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学员评估明细 的本地化字符串。
        /// </summary>
        public static string CourseStudentDetail {
            get {
                return ResourceManager.GetString("CourseStudentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程预订查询 的本地化字符串。
        /// </summary>
        public static string CourseSubscribe {
            get {
                return ResourceManager.GetString("CourseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集中授课课程预订详情 的本地化字符串。
        /// </summary>
        public static string CourseSubscribeDetail {
            get {
                return ResourceManager.GetString("CourseSubscribeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DeCourseDetail {
            get {
                return ResourceManager.GetString("DeCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DeNoCourseDetail {
            get {
                return ResourceManager.GetString("DeNoCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程考勤详情 的本地化字符串。
        /// </summary>
        public static string DepAttendceApprovalCourseInfDepAttendceApprovalCourseInfor {
            get {
                return ResourceManager.GetString("DepAttendceApprovalCourseInfDepAttendceApprovalCourseInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤审批管理 的本地化字符串。
        /// </summary>
        public static string DepAttendceApprovalList {
            get {
                return ResourceManager.GetString("DepAttendceApprovalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤详情 的本地化字符串。
        /// </summary>
        public static string DepAttendceDetail {
            get {
                return ResourceManager.GetString("DepAttendceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤管理 的本地化字符串。
        /// </summary>
        public static string DepAttendceList {
            get {
                return ResourceManager.GetString("DepAttendceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤管理部门详情 的本地化字符串。
        /// </summary>
        public static string DepAttendceListDetail {
            get {
                return ResourceManager.GetString("DepAttendceListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览试题 的本地化字符串。
        /// </summary>
        public static string DepBrowseQuestion {
            get {
                return ResourceManager.GetString("DepBrowseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教室管理 的本地化字符串。
        /// </summary>
        public static string DepClassRoomManage {
            get {
                return ResourceManager.GetString("DepClassRoomManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课前建议 的本地化字符串。
        /// </summary>
        public static string DepCoruseAdvice {
            get {
                return ResourceManager.GetString("DepCoruseAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程建议详情 的本地化字符串。
        /// </summary>
        public static string DepCourseAdviceDetail {
            get {
                return ResourceManager.GetString("DepCourseAdviceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程指定详情 的本地化字符串。
        /// </summary>
        public static string DepCourseAppointDetail {
            get {
                return ResourceManager.GetString("DepCourseAppointDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程评估 的本地化字符串。
        /// </summary>
        public static string DepCourseEvlution {
            get {
                return ResourceManager.GetString("DepCourseEvlution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程评估详情 的本地化字符串。
        /// </summary>
        public static string DepCourseEvlutionDetail {
            get {
                return ResourceManager.GetString("DepCourseEvlutionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程评估汇总 的本地化字符串。
        /// </summary>
        public static string DepCourseEvlutionTotal {
            get {
                return ResourceManager.GetString("DepCourseEvlutionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门自学开课详情 的本地化字符串。
        /// </summary>
        public static string DepCourseLearnSelfList {
            get {
                return ResourceManager.GetString("DepCourseLearnSelfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程管理 的本地化字符串。
        /// </summary>
        public static string DepCourseManage {
            get {
                return ResourceManager.GetString("DepCourseManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门课程开放至全所审批 的本地化字符串。
        /// </summary>
        public static string DepCourseOpenOthersCheck {
            get {
                return ResourceManager.GetString("DepCourseOpenOthersCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放至全所课程详情 的本地化字符串。
        /// </summary>
        public static string DepCourseOpenOthersList {
            get {
                return ResourceManager.GetString("DepCourseOpenOthersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程查询 的本地化字符串。
        /// </summary>
        public static string DepCourseQuery {
            get {
                return ResourceManager.GetString("DepCourseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程指定详情 的本地化字符串。
        /// </summary>
        public static string DepCourseSignDetail {
            get {
                return ResourceManager.GetString("DepCourseSignDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学员评估明细 的本地化字符串。
        /// </summary>
        public static string DepCourseStudentDetail {
            get {
                return ResourceManager.GetString("DepCourseStudentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DepCourseTogetherDetial {
            get {
                return ResourceManager.GetString("DepCourseTogetherDetial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑试卷 的本地化字符串。
        /// </summary>
        public static string DepEditExampaper {
            get {
                return ResourceManager.GetString("DepEditExampaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑公告 的本地化字符串。
        /// </summary>
        public static string DepEditNote {
            get {
                return ResourceManager.GetString("DepEditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试管理 的本地化字符串。
        /// </summary>
        public static string DepExaminationManage {
            get {
                return ResourceManager.GetString("DepExaminationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试卷管理 的本地化字符串。
        /// </summary>
        public static string DepExampaperManage {
            get {
                return ResourceManager.GetString("DepExampaperManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识点管理 的本地化字符串。
        /// </summary>
        public static string DepKnowledgeKeyManage {
            get {
                return ResourceManager.GetString("DepKnowledgeKeyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假审批管理 的本地化字符串。
        /// </summary>
        public static string DepLeaveApprovalManage {
            get {
                return ResourceManager.GetString("DepLeaveApprovalManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请假详情 的本地化字符串。
        /// </summary>
        public static string DepLeaveDetail {
            get {
                return ResourceManager.GetString("DepLeaveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门/分所管理 的本地化字符串。
        /// </summary>
        public static string DepManage {
            get {
                return ResourceManager.GetString("DepManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训管理首页 的本地化字符串。
        /// </summary>
        public static string DepManageIndex {
            get {
                return ResourceManager.GetString("DepManageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程列表 的本地化字符串。
        /// </summary>
        public static string DepManageList {
            get {
                return ResourceManager.GetString("DepManageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联合上报考勤管理 的本地化字符串。
        /// </summary>
        public static string DepMinAttendceList {
            get {
                return ResourceManager.GetString("DepMinAttendceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的考试 的本地化字符串。
        /// </summary>
        public static string DepMyExamList {
            get {
                return ResourceManager.GetString("DepMyExamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告管理 的本地化字符串。
        /// </summary>
        public static string DepNoteManage {
            get {
                return ResourceManager.GetString("DepNoteManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告详情 的本地化字符串。
        /// </summary>
        public static string DepNoteManageDetail {
            get {
                return ResourceManager.GetString("DepNoteManageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门开课跟踪 的本地化字符串。
        /// </summary>
        public static string DepOpenCourseFollowing {
            get {
                return ResourceManager.GetString("DepOpenCourseFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数配置 的本地化字符串。
        /// </summary>
        public static string DepParamConfig {
            get {
                return ResourceManager.GetString("DepParamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训计划管理 的本地化字符串。
        /// </summary>
        public static string DepPlanManage {
            get {
                return ResourceManager.GetString("DepPlanManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划开课详情 的本地化字符串。
        /// </summary>
        public static string DepPlanOpenYearCourse {
            get {
                return ResourceManager.GetString("DepPlanOpenYearCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑试题 的本地化字符串。
        /// </summary>
        public static string DepQuestionEdit {
            get {
                return ResourceManager.GetString("DepQuestionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题管理 的本地化字符串。
        /// </summary>
        public static string DepQuestionManage {
            get {
                return ResourceManager.GetString("DepQuestionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DepSelfCourse {
            get {
                return ResourceManager.GetString("DepSelfCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程指定查询 的本地化字符串。
        /// </summary>
        public static string DepSelfCourseAppointSearch {
            get {
                return ResourceManager.GetString("DepSelfCourseAppointSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训需求管理 的本地化字符串。
        /// </summary>
        public static string DepSurvey {
            get {
                return ResourceManager.GetString("DepSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        public static string DepSystemManage {
            get {
                return ResourceManager.GetString("DepSystemManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览调查 的本地化字符串。
        /// </summary>
        public static string DeptBrowseSurvey {
            get {
                return ResourceManager.GetString("DeptBrowseSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的需求 的本地化字符串。
        /// </summary>
        public static string DeptDoSurveyList {
            get {
                return ResourceManager.GetString("DeptDoSurveyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的授课课程 的本地化字符串。
        /// </summary>
        public static string DepTeacherCourse {
            get {
                return ResourceManager.GetString("DepTeacherCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的授课课程详情 的本地化字符串。
        /// </summary>
        public static string DepTeacherCourseDetail {
            get {
                return ResourceManager.GetString("DepTeacherCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑部门 的本地化字符串。
        /// </summary>
        public static string DeptEdit {
            get {
                return ResourceManager.GetString("DeptEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门管理 的本地化字符串。
        /// </summary>
        public static string DeptManage {
            get {
                return ResourceManager.GetString("DeptManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DeptMyCourseList {
            get {
                return ResourceManager.GetString("DeptMyCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DeptMyNoCourseList {
            get {
                return ResourceManager.GetString("DeptMyNoCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转播考勤详情 的本地化字符串。
        /// </summary>
        public static string DepTranAttendceDetail {
            get {
                return ResourceManager.GetString("DepTranAttendceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string DepTranCourseDetail {
            get {
                return ResourceManager.GetString("DepTranCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工部门学习学时查询 的本地化字符串。
        /// </summary>
        public static string DepUserScore {
            get {
                return ResourceManager.GetString("DepUserScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人学时详情 的本地化字符串。
        /// </summary>
        public static string DepUserScoreDetails {
            get {
                return ResourceManager.GetString("DepUserScoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划管理 的本地化字符串。
        /// </summary>
        public static string DepYearPlan {
            get {
                return ResourceManager.GetString("DepYearPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增年度计划 的本地化字符串。
        /// </summary>
        public static string DepYearPlanAdd {
            get {
                return ResourceManager.GetString("DepYearPlanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划预览 的本地化字符串。
        /// </summary>
        public static string DepYearPlanDetail {
            get {
                return ResourceManager.GetString("DepYearPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑年度计划 的本地化字符串。
        /// </summary>
        public static string DepYearPlanEdit {
            get {
                return ResourceManager.GetString("DepYearPlanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划跟踪 的本地化字符串。
        /// </summary>
        public static string DepYearPlanTrack {
            get {
                return ResourceManager.GetString("DepYearPlanTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程开设 的本地化字符串。
        /// </summary>
        public static string EditDepCourseTogether {
            get {
                return ResourceManager.GetString("EditDepCourseTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑考试 的本地化字符串。
        /// </summary>
        public static string EditExamination {
            get {
                return ResourceManager.GetString("EditExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑试卷 的本地化字符串。
        /// </summary>
        public static string EditExampaper {
            get {
                return ResourceManager.GetString("EditExampaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑知识点 的本地化字符串。
        /// </summary>
        public static string EditKnowledgeKey {
            get {
                return ResourceManager.GetString("EditKnowledgeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑政策 的本地化字符串。
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复评管理 的本地化字符串。
        /// </summary>
        public static string EvaluationManage {
            get {
                return ResourceManager.GetString("EvaluationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程评估详情 的本地化字符串。
        /// </summary>
        public static string EvlutionDetail {
            get {
                return ResourceManager.GetString("EvlutionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程评估详情 的本地化字符串。
        /// </summary>
        public static string EvlutionTotal {
            get {
                return ResourceManager.GetString("EvlutionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试详情 的本地化字符串。
        /// </summary>
        public static string ExaminationDetail {
            get {
                return ResourceManager.GetString("ExaminationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试管理 的本地化字符串。
        /// </summary>
        public static string ExaminationList {
            get {
                return ResourceManager.GetString("ExaminationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试管理 的本地化字符串。
        /// </summary>
        public static string ExaminationManage {
            get {
                return ResourceManager.GetString("ExaminationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试卷管理 的本地化字符串。
        /// </summary>
        public static string ExampaperManage {
            get {
                return ResourceManager.GetString("ExampaperManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 答卷详情 的本地化字符串。
        /// </summary>
        public static string ExamTestDetail {
            get {
                return ResourceManager.GetString("ExamTestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线考试 的本地化字符串。
        /// </summary>
        public static string ExamTestOnline {
            get {
                return ResourceManager.GetString("ExamTestOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 政策管理 的本地化字符串。
        /// </summary>
        public static string FAQ_NoteManage {
            get {
                return ResourceManager.GetString("FAQ_NoteManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 政策管理 的本地化字符串。
        /// </summary>
        public static string FAQManage {
            get {
                return ResourceManager.GetString("FAQManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门自学开课详情 的本地化字符串。
        /// </summary>
        public static string FDepCourseLearnSelfList {
            get {
                return ResourceManager.GetString("FDepCourseLearnSelfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放至全所课程详情 的本地化字符串。
        /// </summary>
        public static string FDepCourseOpenOthersList {
            get {
                return ResourceManager.GetString("FDepCourseOpenOthersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划开课详情 的本地化字符串。
        /// </summary>
        public static string FDepPlanOpenYearCourse {
            get {
                return ResourceManager.GetString("FDepPlanOpenYearCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string FDepSelfCourse {
            get {
                return ResourceManager.GetString("FDepSelfCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免修审批详情 的本地化字符串。
        /// </summary>
        public static string FreeApproveDetails {
            get {
                return ResourceManager.GetString("FreeApproveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训级别变更 的本地化字符串。
        /// </summary>
        public static string GradeManage {
            get {
                return ResourceManager.GetString("GradeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑群组 的本地化字符串。
        /// </summary>
        public static string GroupEdit {
            get {
                return ResourceManager.GetString("GroupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 群组管理 的本地化字符串。
        /// </summary>
        public static string GroupManage {
            get {
                return ResourceManager.GetString("GroupManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识点管理 的本地化字符串。
        /// </summary>
        public static string KnowledgeKeyManage {
            get {
                return ResourceManager.GetString("KnowledgeKeyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志管理 的本地化字符串。
        /// </summary>
        public static string LogManage {
            get {
                return ResourceManager.GetString("LogManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划预览 的本地化字符串。
        /// </summary>
        public static string ManageYearPlanDetail {
            get {
                return ResourceManager.GetString("ManageYearPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改个人资料 的本地化字符串。
        /// </summary>
        public static string ModifyPersonalInfo {
            get {
                return ResourceManager.GetString("ModifyPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度大纲 的本地化字符串。
        /// </summary>
        public static string MonthPlan {
            get {
                return ResourceManager.GetString("MonthPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差异对比 的本地化字符串。
        /// </summary>
        public static string MonthPlanCompare {
            get {
                return ResourceManager.GetString("MonthPlanCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月度大纲详情 的本地化字符串。
        /// </summary>
        public static string MonthPlanDetail {
            get {
                return ResourceManager.GetString("MonthPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的月度计划课程表 的本地化字符串。
        /// </summary>
        public static string MonthPlanScheduleTask {
            get {
                return ResourceManager.GetString("MonthPlanScheduleTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的申请 的本地化字符串。
        /// </summary>
        public static string MyApply {
            get {
                return ResourceManager.GetString("MyApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时申请审批详情 的本地化字符串。
        /// </summary>
        public static string MyApprovalOutTimeLeaveInfor {
            get {
                return ResourceManager.GetString("MyApprovalOutTimeLeaveInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string MyBroadcastCourseDetail {
            get {
                return ResourceManager.GetString("MyBroadcastCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转播课程 的本地化字符串。
        /// </summary>
        public static string MyBroadcastList {
            get {
                return ResourceManager.GetString("MyBroadcastList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已预订的课程 的本地化字符串。
        /// </summary>
        public static string MyCourse {
            get {
                return ResourceManager.GetString("MyCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的可预订课程 的本地化字符串。
        /// </summary>
        public static string MyCourseSubscribe {
            get {
                return ResourceManager.GetString("MyCourseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的课程 的本地化字符串。
        /// </summary>
        public static string MyDepCourse {
            get {
                return ResourceManager.GetString("MyDepCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的已预订课程 的本地化字符串。
        /// </summary>
        public static string MyDepCourseList {
            get {
                return ResourceManager.GetString("MyDepCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的可预订课程 的本地化字符串。
        /// </summary>
        public static string MyDepCourseSubscribe {
            get {
                return ResourceManager.GetString("MyDepCourseSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的培训首页 的本地化字符串。
        /// </summary>
        public static string MyDepIndex {
            get {
                return ResourceManager.GetString("MyDepIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的课前建议与评估 的本地化字符串。
        /// </summary>
        public static string MyDepProposeAndEvlution {
            get {
                return ResourceManager.GetString("MyDepProposeAndEvlution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的学时及考勤获取 的本地化字符串。
        /// </summary>
        public static string MyDepTranScore {
            get {
                return ResourceManager.GetString("MyDepTranScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的考试 的本地化字符串。
        /// </summary>
        public static string MyExamination {
            get {
                return ResourceManager.GetString("MyExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的请假申请 的本地化字符串。
        /// </summary>
        public static string MyLeaveApprovalList {
            get {
                return ResourceManager.GetString("MyLeaveApprovalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的请假申请详情 的本地化字符串。
        /// </summary>
        public static string MyLeaveInfor {
            get {
                return ResourceManager.GetString("MyLeaveInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的考勤 的本地化字符串。
        /// </summary>
        public static string MyNewAttendceList {
            get {
                return ResourceManager.GetString("MyNewAttendceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的面授课程 的本地化字符串。
        /// </summary>
        public static string MyNewCourse {
            get {
                return ResourceManager.GetString("MyNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的课程 的本地化字符串。
        /// </summary>
        public static string MyNewCourseList {
            get {
                return ResourceManager.GetString("MyNewCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的视频课程 的本地化字符串。
        /// </summary>
        public static string MyNewVideoCourse {
            get {
                return ResourceManager.GetString("MyNewVideoCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放至全所课程指定详情 的本地化字符串。
        /// </summary>
        public static string MyOpenCourseDetail {
            get {
                return ResourceManager.GetString("MyOpenCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的考勤及学分 的本地化字符串。
        /// </summary>
        public static string MyScoreAndAttendence {
            get {
                return ResourceManager.GetString("MyScoreAndAttendence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的需求 的本地化字符串。
        /// </summary>
        public static string MySurvey {
            get {
                return ResourceManager.GetString("MySurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的需求 的本地化字符串。
        /// </summary>
        public static string MySurveyList {
            get {
                return ResourceManager.GetString("MySurveyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的培训首页 的本地化字符串。
        /// </summary>
        public static string MyTrainIndex {
            get {
                return ResourceManager.GetString("MyTrainIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤管理 的本地化字符串。
        /// </summary>
        public static string NewAttendceManage {
            get {
                return ResourceManager.GetString("NewAttendceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看调查详情 的本地化字符串。
        /// </summary>
        public static string NewBrowseSurveyResult {
            get {
                return ResourceManager.GetString("NewBrowseSurveyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参与调查 的本地化字符串。
        /// </summary>
        public static string NewDoSurvey {
            get {
                return ResourceManager.GetString("NewDoSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的评估详情 的本地化字符串。
        /// </summary>
        public static string NewMyAfterCourseDetail {
            get {
                return ResourceManager.GetString("NewMyAfterCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的课前建议与评估 的本地化字符串。
        /// </summary>
        public static string NewMyPropose {
            get {
                return ResourceManager.GetString("NewMyPropose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的课前建议 的本地化字符串。
        /// </summary>
        public static string NewMyProposeDetail {
            get {
                return ResourceManager.GetString("NewMyProposeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的授课课程(新进员工) 的本地化字符串。
        /// </summary>
        public static string NewMyTeachCourse {
            get {
                return ResourceManager.GetString("NewMyTeachCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的培训首页 的本地化字符串。
        /// </summary>
        public static string NewMyTrainIndex {
            get {
                return ResourceManager.GetString("NewMyTrainIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评价详情 的本地化字符串。
        /// </summary>
        public static string NewTeacherEvlutionDetail {
            get {
                return ResourceManager.GetString("NewTeacherEvlutionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评价详情 的本地化字符串。
        /// </summary>
        public static string NewTeacherEvlutionManageDetail {
            get {
                return ResourceManager.GetString("NewTeacherEvlutionManageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告详情 的本地化字符串。
        /// </summary>
        public static string NoteDetail {
            get {
                return ResourceManager.GetString("NoteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告列表 的本地化字符串。
        /// </summary>
        public static string NoteManage {
            get {
                return ResourceManager.GetString("NoteManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告详情 的本地化字符串。
        /// </summary>
        public static string NoteManageDetail {
            get {
                return ResourceManager.GetString("NoteManageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告管理 的本地化字符串。
        /// </summary>
        public static string NoteSysManage {
            get {
                return ResourceManager.GetString("NoteSysManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string OpenOthersDepCourseTogetherDetial {
            get {
                return ResourceManager.GetString("OpenOthersDepCourseTogetherDetial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他形式审批详情 的本地化字符串。
        /// </summary>
        public static string OtherApproveDetails {
            get {
                return ResourceManager.GetString("OtherApproveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他有组织形式审批详情 的本地化字符串。
        /// </summary>
        public static string OtherOrgDetails {
            get {
                return ResourceManager.GetString("OtherOrgDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数配置 的本地化字符串。
        /// </summary>
        public static string ParamConfig {
            get {
                return ResourceManager.GetString("ParamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员管理 的本地化字符串。
        /// </summary>
        public static string PeopleManage {
            get {
                return ResourceManager.GetString("PeopleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训计划管理 的本地化字符串。
        /// </summary>
        public static string PlanManage {
            get {
                return ResourceManager.GetString("PlanManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑岗位 的本地化字符串。
        /// </summary>
        public static string PostEdit {
            get {
                return ResourceManager.GetString("PostEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位管理 的本地化字符串。
        /// </summary>
        public static string PostManage {
            get {
                return ResourceManager.GetString("PostManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识详情 的本地化字符串。
        /// </summary>
        public static string PreReMyResourceListShow {
            get {
                return ResourceManager.GetString("PreReMyResourceListShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增试题 的本地化字符串。
        /// </summary>
        public static string QuestionAdd {
            get {
                return ResourceManager.GetString("QuestionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑试题 的本地化字符串。
        /// </summary>
        public static string QuestionEdit {
            get {
                return ResourceManager.GetString("QuestionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试题管理 的本地化字符串。
        /// </summary>
        public static string QuestionManage {
            get {
                return ResourceManager.GetString("QuestionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工复评 的本地化字符串。
        /// </summary>
        public static string ReEvaluation {
            get {
                return ResourceManager.GetString("ReEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识详情 的本地化字符串。
        /// </summary>
        public static string ReMyResourceListShow {
            get {
                return ResourceManager.GetString("ReMyResourceListShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门/分所自学课程汇总统计 的本地化字符串。
        /// </summary>
        public static string Report_DepCourseALL {
            get {
                return ResourceManager.GetString("Report_DepCourseALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频课程汇总统计 的本地化字符串。
        /// </summary>
        public static string Report_VedioLearnList {
            get {
                return ResourceManager.GetString("Report_VedioLearnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训目标完成情况统计 的本地化字符串。
        /// </summary>
        public static string ReportTarget {
            get {
                return ResourceManager.GetString("ReportTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频课程学习详情 的本地化字符串。
        /// </summary>
        public static string ReportVedioDetial {
            get {
                return ResourceManager.GetString("ReportVedioDetial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        public static string RightManage {
            get {
                return ResourceManager.GetString("RightManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色 的本地化字符串。
        /// </summary>
        public static string RoleEdit {
            get {
                return ResourceManager.GetString("RoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string RoleManage {
            get {
                return ResourceManager.GetString("RoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门问卷审核明细 的本地化字符串。
        /// </summary>
        public static string SurveyCheckDeatils {
            get {
                return ResourceManager.GetString("SurveyCheckDeatils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷审核 的本地化字符串。
        /// </summary>
        public static string SurveyCheckForDept {
            get {
                return ResourceManager.GetString("SurveyCheckForDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷审核汇总 的本地化字符串。
        /// </summary>
        public static string SurveyCheckForOffice {
            get {
                return ResourceManager.GetString("SurveyCheckForOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑调查 的本地化字符串。
        /// </summary>
        public static string SurveyEdit {
            get {
                return ResourceManager.GetString("SurveyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑问卷 的本地化字符串。
        /// </summary>
        public static string SurveyExampaperEdit {
            get {
                return ResourceManager.GetString("SurveyExampaperEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问卷管理 的本地化字符串。
        /// </summary>
        public static string SurveyExampaperList {
            get {
                return ResourceManager.GetString("SurveyExampaperList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调查管理 的本地化字符串。
        /// </summary>
        public static string SurveyManage {
            get {
                return ResourceManager.GetString("SurveyManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理首页 的本地化字符串。
        /// </summary>
        public static string SystemManageIndex {
            get {
                return ResourceManager.GetString("SystemManageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 讲师管理 的本地化字符串。
        /// </summary>
        public static string TeacherIndex {
            get {
                return ResourceManager.GetString("TeacherIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考试评估 的本地化字符串。
        /// </summary>
        public static string TestingAssessment {
            get {
                return ResourceManager.GetString("TestingAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时审批申请 的本地化字符串。
        /// </summary>
        public static string TimeOutApply {
            get {
                return ResourceManager.GetString("TimeOutApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时审批申请详情 的本地化字符串。
        /// </summary>
        public static string TimeOutApplyDetail {
            get {
                return ResourceManager.GetString("TimeOutApplyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时申请审批管理 的本地化字符串。
        /// </summary>
        public static string TimeOutApproval {
            get {
                return ResourceManager.GetString("TimeOutApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逾时申请审批详情 的本地化字符串。
        /// </summary>
        public static string TimeOutApprovalDetail {
            get {
                return ResourceManager.GetString("TimeOutApprovalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 培训级别维护 的本地化字符串。
        /// </summary>
        public static string TrainGrade {
            get {
                return ResourceManager.GetString("TrainGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护级别详情 的本地化字符串。
        /// </summary>
        public static string TrainGradeDetail {
            get {
                return ResourceManager.GetString("TrainGradeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户信息 的本地化字符串。
        /// </summary>
        public static string UserBaseInfo {
            get {
                return ResourceManager.GetString("UserBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人培训学时汇总 的本地化字符串。
        /// </summary>
        public static string userCPAScore {
            get {
                return ResourceManager.GetString("userCPAScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户详情 的本地化字符串。
        /// </summary>
        public static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑人员 的本地化字符串。
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指纹管理 的本地化字符串。
        /// </summary>
        public static string UserFingerInfor {
            get {
                return ResourceManager.GetString("UserFingerInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户管理 的本地化字符串。
        /// </summary>
        public static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学习人员明细 的本地化字符串。
        /// </summary>
        public static string VedioUserDetails {
            get {
                return ResourceManager.GetString("VedioUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 课程详情 的本地化字符串。
        /// </summary>
        public static string VideoCourseMain {
            get {
                return ResourceManager.GetString("VideoCourseMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频管理 的本地化字符串。
        /// </summary>
        public static string VideoManage {
            get {
                return ResourceManager.GetString("VideoManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受或拒绝联合 的本地化字符串。
        /// </summary>
        public static string YearLinkPlan {
            get {
                return ResourceManager.GetString("YearLinkPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年度计划管理 的本地化字符串。
        /// </summary>
        public static string YearPlan {
            get {
                return ResourceManager.GetString("YearPlan", resourceCulture);
            }
        }
    }
}
