//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinLanguage.Login {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginLanguage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiXinLanguage.Login.LoginLanguage", typeof(LoginLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，密码错误&lt;b&gt;{0}&lt;/b&gt; 次，您的账户已被锁定！ 的本地化字符串。
        /// </summary>
        public static string Login_AccountsLocked {
            get {
                return ResourceManager.GetString("Login_AccountsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，请检查密码是否正确！您已经错误 &lt;b&gt;{0}&lt;/b&gt; 次！ 的本地化字符串。
        /// </summary>
        public static string Login_CheckPassword {
            get {
                return ResourceManager.GetString("Login_CheckPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败，请检查用户名是否正确！ 的本地化字符串。
        /// </summary>
        public static string Login_CheckUserName {
            get {
                return ResourceManager.GetString("Login_CheckUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码： 的本地化字符串。
        /// </summary>
        public static string Login_Code {
            get {
                return ResourceManager.GetString("Login_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已经连续输入错误&lt;b&gt;{0}&lt;/b&gt;次，系统已经锁定您的账号，请联系管理员解锁！ 的本地化字符串。
        /// </summary>
        public static string Login_ErrorPassword {
            get {
                return ResourceManager.GetString("Login_ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的账号已被冻结，请联系管理员！ 的本地化字符串。
        /// </summary>
        public static string Login_FreezeAccount {
            get {
                return ResourceManager.GetString("Login_FreezeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录&gt;&gt; 的本地化字符串。
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户不存在，请检查用户名是否正确！ 的本地化字符串。
        /// </summary>
        public static string Login_NotFindUserName {
            get {
                return ResourceManager.GetString("Login_NotFindUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码： 的本地化字符串。
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string Login_RememberPassword {
            get {
                return ResourceManager.GetString("Login_RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Login_Reset {
            get {
                return ResourceManager.GetString("Login_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名： 的本地化字符串。
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不能为空！ 的本地化字符串。
        /// </summary>
        public static string Login_ValidateCode {
            get {
                return ResourceManager.GetString("Login_ValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码不正确！ 的本地化字符串。
        /// </summary>
        public static string Login_ValidateCodeTrue {
            get {
                return ResourceManager.GetString("Login_ValidateCodeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空！ 的本地化字符串。
        /// </summary>
        public static string Login_ValidatePassword {
            get {
                return ResourceManager.GetString("Login_ValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空！ 的本地化字符串。
        /// </summary>
        public static string Login_ValidateUserName {
            get {
                return ResourceManager.GetString("Login_ValidateUserName", resourceCulture);
            }
        }
    }
}
