#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.ExamTest
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ExamTest/ExamTestOnline.cshtml")]
    public partial class ExamTestOnline : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExamTestOnline()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
  
    ViewBag.Title = "在线考试";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string examUserID = Request.QueryString["euID"];
    string txtsourceType = Request.QueryString["SourceType"];


            
            #line default
            #line hidden
WriteLiteral("<script src=\"");


            
            #line 7 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
        Write(Url.Content("~/Scripts/exam.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"> </script>\r\n<script src=\"");


            
            #line 8 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
        Write(Url.Content("~/Scripts/ckplayer5.8/ckplayer.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"> </script>\r\n<input id=\"examUserID\" name=\"examUserID\" typ" +
"e=\"hidden\" value=\"");


            
            #line 9 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                          Write(examUserID);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n<input id=\"txtsourceType\" name=\"txtsourceType\" type=\"hidden\" value=\"");


            
            #line 10 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                                Write(txtsourceType);

            
            #line default
            #line hidden
WriteLiteral(@""" />
<form id=""submitAnswerForm"" method=""post"" action="""">
<input id=""questionOrder"" name=""questionOrder"" type=""hidden"" />
<input id=""userAnswer"" name=""userAnswer"" type=""hidden"" />
<input id=""questionScore"" name=""questionScore"" type=""hidden"" />
</form>
<div class=""main-c"">
    ");


            
            #line 17 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
Write(Html.Action("SiteMapLink", "Common", new
{ 
    linkName = "ExamTestOnline"
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!-- 考试基本信息 -->\r\n    <div id=\"examBaseInfor\">\r\n    </div>\r\n    <!-- 考试内容 --" +
">\r\n    <div id=\"examTestMain\" style=\"display: none;\">\r\n        <div id=\"examTest" +
"\">\r\n        </div>\r\n        <div class=\"exam-main\">\r\n            <div class=\"fl " +
"span77\">\r\n                <div class=\"tab-bk tab-exam\"><ul id=\"operation\"></ul><" +
"/div>\r\n                <div id=\"questionList\" class=\"exam-con\"></div>\r\n         " +
"   </div>\r\n            <div class=\"fr span22\">\r\n                <div id=\"questio" +
"nCountTotal\"></div>\r\n                <div id=\"questionCountDetail\">\r\n           " +
"     </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<!-- 试题填空题输" +
"入框模板 -->\r\n<script id=\"fillBlankTemplate\" type=\"text/x-jsrender\">\r\n    <p><input " +
"type=\"text\" class=\"Box all50\" count=\"{{:#data}}\" questionID=\"0\"/></p>\r\n</script>" +
"\r\n<!-- 试题显示模板 -->\r\n<script id=\"questionShowTemplate\" type=\"text/x-jsrender\">\r\n  " +
"  <div id=\"q{{:QuestionID}}\" type=\"{{:QType}}\" class=\"singleQuestion\">\r\n        " +
"<dl class=\"clb\">\r\n            <dt>\r\n                <a sign=\"sign\" class=\"signf\"" +
" signflag=\"0\" onclick=\"Exam.ChangeSign({{:QuestionID}},this);\"></a>{{:QuestionOr" +
"der}} <span class=\"c_green\">({{:Score}}分) . </span> \r\n            </dt>\r\n       " +
"     <dd>\r\n                <h5 style=\"overflow:auto;\">{{:QuestionContent}}</h5>\r" +
"\n                {{if QType==6}}\r\n                    <a class=\"icon iview\" titl" +
"e=\'查看\' onclick=\'Exam.BrowQuestionFiles({{:QuestionID}});\'></a>\r\n                " +
"{{/if}}\r\n            </dd>\r\n            <dd class=\"questionAnswer\">\r\n           " +
"     {{if QType==1}}\r\n                    <!-- 问答题 -->\r\n                    {{fo" +
"r QuestionAnswer}}\r\n                        <p><textarea id=\"answer_{{:QuID}}_0\"" +
" class=\"Boxarea all50\" onblur=\"Exam.UpdateUserAnswer({{:QuID}},{{:QType}});\">{{:" +
"UserAnswer}}</textarea><p>\r\n                    {{/for}}\r\n                {{/if}" +
"}\r\n                {{if QType==2}}\r\n                    <!-- 单选题 -->\r\n          " +
"          {{for QuestionAnswer}}\r\n                        <p><input type=\"radio\"" +
" name=\"answer_{{:QuID}}\" order=\"{{:Order}}\" id=\"answer_{{:QuID}}_{{:Order}}\" onc" +
"hange=\"Exam.UpdateUserAnswer({{:QuID}},{{:QType}});\"/>{{:AnswerOrderShow}}. {{:A" +
"nswerContent}}</p>\r\n                    {{/for}}    \r\n                {{/if}}\r\n " +
"               {{if QType==3}}\r\n                    <!-- 多选题 -->\r\n              " +
"      {{for QuestionAnswer}}\r\n                        <p><input type=\"checkbox\" " +
"id=\"answer_{{:QuID}}_{{:Order}}\" order=\"{{:Order}}\" onchange=\"Exam.UpdateUserAns" +
"wer({{:QuID}},{{:QType}});\"/>{{:AnswerOrderShow}}. {{:AnswerContent}}</p>\r\n     " +
"               {{/for}}\r\n                {{/if}}\r\n                {{if QType==4}" +
"}\r\n                    <!-- 判断题 -->\r\n                    <p><input type=\"radio\" " +
"name=\"answer_{{:QuestionID}}\" order=\"0\" id=\"answer_{{:QuestionID}}_0\" onchange=\"" +
"Exam.UpdateUserAnswer({{:QuestionID}},{{:QType}});\"/>A. 正确</p>\r\n                " +
"    <p><input type=\"radio\" name=\"answer_{{:QuestionID}}\" order=\"1\" id=\"answer_{{" +
":QuestionID}}_1\" onchange=\"Exam.UpdateUserAnswer({{:QuestionID}},{{:QType}});\"/>" +
"B. 错误</p>\r\n                {{/if}}\r\n                {{if QType==5}}\r\n           " +
"         <!-- 填空题 -->\r\n                {{/if}}\r\n                {{if QType==6}}\r" +
"\n                    <!-- 多选题 -->\r\n                    {{for QuestionAnswer}}\r\n " +
"                       {{if AnswerType==0}}\r\n                            <p><tex" +
"tarea id=\"answer_{{:QuID}}_0\" class=\"Boxarea all50\" onblur=\"Exam.UpdateUserAnswe" +
"r({{:QuID}},{{:QType}});\">{{:UserAnswer}}</textarea></p>\r\n                      " +
"  {{/if}}\r\n                        {{if AnswerType!=0}}\r\n                       " +
"     <p><input type=\"{{:AnswerType==1?\"radio\":\"checkbox\"}}\" order=\"{{:Order}}\" n" +
"ame=\"answer_{{:QuID}}\" id=\"answer_{{:QuID}}_{{:Order}}\" onchange=\"Exam.UpdateUse" +
"rAnswer({{:QuID}},{{:QType}});\"/>{{:AnswerOrderShow}}. {{:AnswerContent}}</p>\r\n " +
"                       {{/if}}\r\n                    {{/for}}\r\n                {{" +
"/if}}\r\n            </dd>\r\n        </dl>\r\n    </div>\r\n\r\n</script>\r\n<!-- 右侧单个显示 --" +
">\r\n<script id=\"questionSingleShowTemplate\" type=\"text/x-jsrender\">\r\n    <div id=" +
"\"order{{:QuestionID}}\"  class=\"singlequ {{:UserAnswer.length>0?\'done\':\'nodone\'}}" +
"\" doflag=\"{{:UserAnswer.length>0?1:0}}\" signflag=\"0\" onclick=\"Exam.GetShowSingle" +
"Question({{:QuestionID}},{{:QuestionOrder}});\">\r\n        {{:QuestionOrder}}\r\n   " +
" </div>\r\n</script>\r\n<!-- 右侧题目数目统计 -->\r\n<script id=\"questionCountTotalTemplate\" t" +
"ype=\"text/x-jsrender\">\r\n    <div class=\"tab-topic\">\r\n        <ul>\r\n            <" +
"li onclick=\" Exam.QuestionStatusSelect(this,0); \" class=\"On\">全部<div>(<span id=\"q" +
"uAllTotal\">{{:QuAllTotal}}</span>)</div><i></i></li>\r\n            <li onclick=\" " +
"Exam.QuestionStatusSelect(this,1); \">未完成<div>(<span id=\"quNoTotal\">{{:QuNoTotal}" +
"}</span>)</div><i></i></li>\r\n            <li onclick=\" Exam.QuestionStatusSelect" +
"(this,2); \">已完成<div>(<span id=\"quOverTotal\">{{:QuOverTotal}}</span>)</div><i></i" +
"></li>\r\n            <li onclick=\" Exam.QuestionStatusSelect(this,3); \">已标记<div>(" +
"<span id=\"quSignTotal\">{{:QuSignTotal}}</span>)</div><i></i></li>\r\n        </ul>" +
"\r\n    </div>\r\n\r\n</script>\r\n<!-- 右侧题目列表 -->\r\n<script id=\"questionCountDetailTempl" +
"ate\" type=\"text/x-jsrender\">\r\n    <h4>{{:#data}}</h4>\r\n    <div type=\"{{:#data}}" +
"\" class=\"Numlist\"></div>\r\n</script>\r\n<!-- 试题上部的操作按钮模板(单题可逆) -->\r\n<script id=\"exa" +
"mOperationSingleBackTemplate\" type=\"text/x-jsrender\">\r\n        <input id=\"btnPre" +
"Question\" value=\"上一题\" type=\"button\" onclick=\"Exam.GetShowQuestionList(1,-1);\" cl" +
"ass=\"btn\"/>\r\n        <input id=\"btnNextQuestion\" value=\"下一题\" type=\"button\" oncli" +
"ck=\"Exam.GetShowQuestionList(1,1);\" class=\"btn btn-co\"/>\r\n</script>\r\n<!-- 试题上部的操" +
"作按钮模板(单题不可逆) -->\r\n<script id=\"examOperationSingleNoBackTemplate\" type=\"text/x-js" +
"render\">\r\n        <input id=\"btnNextQuestion\" value=\"下一题\" type=\"button\" onclick=" +
"\"Exam.GetShowQuestionList(2,1);\" class=\"btn btn-co\" />\r\n</script>\r\n<!-- 试题上部的操作按" +
"钮模板(整体显示) -->\r\n<script id=\"examOperationAllShowTemplate\" type=\"text/x-jsrender\">" +
"\r\n    <li onclick=\"Exam.QuestionTypeSelect(this,\'{{:#data}}\');\">{{:#data}}</li>\r" +
"\n</script>\r\n<!--考试头部信息模板-->\r\n<script id=\"examTopTemplate\" type=\"text/x-jsrender\"" +
">\r\n    <div class=\"examTit\">\r\n        <h2>{{:ExamTitle}}</h2>\r\n        <dl>\r\n   " +
"         <dd>总分：<strong>{{:ExamScore}}</strong>分</dd>\r\n            <dd>及格分数：<str" +
"ong>{{:PassScore}}</strong>分</dd>\r\n            <dd>考试时长：<strong>{{:ExamLength}}<" +
"/strong>分钟</dd>\r\n            <dt>\r\n                <span>距本场考试结束时间还有：<strong id=" +
"\"examlefttime\"></strong></span>\r\n                <input type=\"button\" id=\"btnSub" +
"mitExam\" onclick=\"Exam.SubmitExam(\'\');\" value=\"提交试卷\" class=\"btn btn-co\"/>\r\n     " +
"       </dt>\r\n        </dl>\r\n    </div>\r\n</script>\r\n<!--进入考试提示信息模板-->\r\n<script i" +
"d=\"examTemplate\" type=\"text/x-jsrender\">\r\n    <div class=\"exam-info\">\r\n        <" +
"div class=\"pic\"></div>\r\n        <table class=\"tab-Form\">\r\n            <tr><td cl" +
"ass=\"Tit\"><i></i>考试总分：</td><td><strong>{{:ExamScore}}</strong>分</td></tr>\r\n     " +
"       <tr><td class=\"Tit\"><i></i>及格分数：</td><td><strong>{{:PassScore}}</strong>分" +
"</td></tr>\r\n            <tr><td class=\"Tit\"><i></i>考试时长：</td><td><strong>{{:Exam" +
"Length}}</strong>分钟</td></tr>\r\n            <tr><td class=\"Tit\"><i></i>显示方式：</td>" +
"<td>{{:ExamShowWay==0?\"整卷显示\":(ExamShowWay==1?\"单题可逆\":\"单题不可逆\")}}</td></tr>\r\n      " +
"  </table>\r\n        <div class=\"time\">\r\n            <p>距本场考试还有：<strong id=\"leftT" +
"ime\"></strong></p>\r\n            <div><input type=\"button\" class=\"btn-blue\" oncli" +
"ck=\"Exam.StartExamTest();\" id=\"btnGoExam\" disabled=\"disabled\" value=\"点击进入考试\"/></" +
"div>\r\n        </div>\r\n    </div>\r\n    <ul class=\"examrule\">\r\n        <li><h5>考试必" +
"读: </h5></li>\r\n        <li>1、本场考试考试时间为：<strong>{{:ExamStartTime}}</strong> 至 <st" +
"rong>{{:ExamEndTime}}</strong>；</li>\r\n        <li>2、当考试时间到了，请点击“<strong>点击进入考试</" +
"strong>”，进入考试，同时考试计时开始；</li>\r\n        <li>3、进入考试页面请不要刷新页面，后果自负；</li>\r\n        <l" +
"i>4、考试倒计时结束会自动交卷，您也可以手动交卷；</li>\r\n        <li>5、祝大家考出好成绩；</li>\r\n    </ul>\r\n</scri" +
"pt>\r\n<!--试题附件查看模板-->\r\n<script id=\"questionFileTemplate\" type=\"text/x-jsrender\">\r" +
"\n    <table >\r\n        <tr>\r\n            {{if #data.FileUpload[0]._fileType==0}}" +
"\r\n                <td class=\"QSingle\">\r\n                <center>\r\n              " +
"      <div id=\"imageCollection\">\r\n                        <a class=\"pl\" onclick=" +
"\" turnToNext(this, \'left\'); \"></a>\r\n                        <input type=\"hidden\"" +
" value=\"1\" />\r\n                        {{for FileUpload}}\r\n                     " +
"       <img src=\"../../ClientBin/UploadFile/{{:_fileName}}\" style=\"{{:#index == " +
"0 ? \'display:block; \' : \' display:none; \'}}\" />\r\n                        {{/for}" +
"}\r\n                        <a class=\"pr\" onclick=\" turnToNext(this, \'right\'); \" " +
"></a>\r\n                    </div>\r\n                </center>\r\n                </" +
"td>\r\n            {{else if #data.FileUpload[0]._fileType==1}}\r\n               <t" +
"d>\r\n                 {{for FileUpload}}\r\n                    <embed type=\"applic" +
"ation/x-mplayer2\" src=\"../../ClientBin/UploadFile/{{:_fileName}}\" name=\"mediapla" +
"yer\" width=\"400\" height=\"250\" showcontrols=\"1\" showstatusbar=\"0\" showdisplay=\"0\"" +
" autostart=\"0\"></embed>\r\n                 {{/for}} \r\n               </td>\r\n     " +
"       {{else}}\r\n                <td>\r\n                {{for FileUpload}}\r\n     " +
"            <input name=\"FlvName\" value=\"{{:_fileName}}\" type=\"hidden\" />\r\n     " +
"             <div id=\'{{:_fileName==null?\"\":_fileName.substring(0,_fileName.leng" +
"th-4)}}\'>\r\n                  </div> \r\n                {{/for}}\r\n                " +
"</td>\r\n            {{/if}}\r\n        </tr>\r\n    </table>\r\n</script>\r\n<script type" +
"=\"text/javascript\">\r\n\r\n    var timer = 0;\r\n    $(document).ready(function () {\r\n" +
"        //隐藏头部、底部\r\n        //……\r\n\r\n        //弹出加载提示\r\n        art.dialog({ width:" +
" 400, height: 150, id: \"loadcounter\", content: \'正在加载，请稍后……<span id=\"process\">0%<" +
"/span>\' });\r\n\r\n        //考试基本信息\r\n        $.getJSON(\"/ExamTest/GetExaminationInfo" +
"rmation?examUserID=");


            
            #line 222 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                              Write(examUserID);

            
            #line default
            #line hidden
WriteLiteral("&SourceType=");


            
            #line 222 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                                                       Write(txtsourceType);

            
            #line default
            #line hidden
WriteLiteral(@""", function (exam) {
            if (exam.result == 1) {
                $(""#process"").html(""30%"");
                Exam.Examination = exam.data;
                $(""#examBaseInfor"").html($(""#examTemplate"").render(exam.data));
                //获取时间
                var tempI = setInterval(""countTimer()"", 1000);

                $.getJSON(""/ExamTest/GetSericeTimeDifference?euID=");


            
            #line 230 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                              Write(examUserID);

            
            #line default
            #line hidden
WriteLiteral("&SourceType=");


            
            #line 230 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                                                       Write(txtsourceType);

            
            #line default
            #line hidden
WriteLiteral(@""", function(time) {
                    if (time.result == 1) {
                        clearInterval(tempI);
                        Exam.timeGoInToTicker = time.timeLength - timer; //局考试开始时间还有多少
                        //倒计时
                        Exam.GoInToTicker();
                        $(""#process"").html(""50%"");
                        $.getJSON(""/ExamTest/GetExampaperInformation?examUserID=");


            
            #line 237 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                                            Write(examUserID);

            
            #line default
            #line hidden
WriteLiteral("&SourceType=");


            
            #line 237 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                                                                                                     Write(txtsourceType);

            
            #line default
            #line hidden
WriteLiteral(@""", function(data) {
                            if (data.result == 1) {
                                $(""#process"").html(""100%"");
                                art.dialog.list['loadcounter'].close();
                                Exam.ExampaperShow = data.data; //试题
                                Exam.UserAnswer = data.data.StudentAnswer; //学员答案
                            }
                        });
                    }
                });
            }
        });
    });

    //计数

    function countTimer()
    {
        timer++;
    }
    function player()
    {
        $(""input[name='FlvName']"").each(function ()
        {
            ckplay($(this).val());
        });
    }
    function ckplay(name)
    {

        var url = '");


            
            #line 267 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
              Write(Url.Content("~/ClientBin/UploadFile/"));

            
            #line default
            #line hidden
WriteLiteral("\' + name;\r\n        var id = name.substring(0, name.length - 4);\r\n        var s1 =" +
" new swfupload();\r\n        s1.ckplayer_url = \'");


            
            #line 270 "..\..\Views\ExamTest\ExamTestOnline.cshtml"
                      Write(Url.Content("~/Scripts/ckplayer5.8/ckplayer.swf"));

            
            #line default
            #line hidden
WriteLiteral(@"'; //播放器文件名
        s1.ckplayer_flv = url; //视频地址,这里也可以填写一个网址或xml地址或flash文件,具体的设置请到网站了解
        s1.ckplayer_pat = '1'; //传递的参数,这里的具体参数设置方式到网站了解
        s1.ckplayer_style = 0; //传递的方式,0是普通方式，1是网址传送，2是xml传送，3是flash传送
        s1.ckplayer_default = 0; //读取文本配置，此参数具有非常强大的功能，（比如外站引用视频只需一个参数即可）说来话长，请到网站了解详情
        s1.ckplayer_xml = ''; //风格配置xml文件，如果为空的话将使用js文件配置
        s1.ckplayer_loadimg = ''; //初始图片地址
        s1.ckplayer_pauseflash = ''; //暂停时播放的广告，只支持flash和图片
        s1.ckplayer_pauseurl = ''; //暂停时播放图片时需要加一个链接
        s1.ckplayer_loadadv = ''; //视频开始前播放的广告，可以是flash,也可是视频格式
        s1.ckplayer_loadurl = ''; //视频开始前广告的链接地址，主要针对视频广告，如果是flash可以不填写
        s1.ckplayer_loadtime = 0; //视频开始前广告播放的秒数,只针对flash或图片有效
        s1.ckplayer_endstatus = 2; //视频结束后的动作，0停止播放并发送js,1是不发送js且重新循环播放,2停止播放
        s1.ckplayer_volume = 40; //视频默认音量0-100之间
        s1.ckplayer_play = 0; //视频默认播放还是暂停，0是暂停，1是播放
        s1.ckplayer_width = 300; //播放器宽度
        s1.ckplayer_height = 150; //播放器高度
        s1.ckplayer_bgcolor = '#000000'; //播放器背景颜色
        s1.ckplayer_allowFullScreen = true; //是否支持全屏，true支持，false不支持，默认支持
        s1.swfwrite(id); //div的id

    }

</script>
");


        }
    }
}
#pragma warning restore 1591
