#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Examination
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    
    #line 1 "..\..\Views\Examination\ReEvaluationList.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Examination\ReEvaluationList.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Examination/ReEvaluationList.cshtml")]
    public class ReEvaluationList : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ReEvaluationList()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Examination\ReEvaluationList.cshtml"
  
    ViewBag.Title = NavigateMenuLanguage.EvaluationManage;
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("<div id=\"contentInfor\" class=\"main-c\">\r\n    ");


            
            #line 8 "..\..\Views\Examination\ReEvaluationList.cshtml"
Write(Html.Action("SiteMapLink", "Common", new {linkName = "EvaluationManage"}));

            
            #line default
            #line hidden
WriteLiteral(@"
    <div id=""Search"" class=""so-set"">
        <table class=""tab-Form"">
            <tr>
                <td class=""Tit span6"">考试名称：</td>
                <td class=""span21""><input type=""text"" class=""span20"" name=""examinationTitle"" value=""请输入搜索内容"" info="""" id=""txt_examTitle"" /></td>
                <td class=""Tit span8"">考试开始时间：</td>
                <td>
                    <div class=""time-choose"">
                        <input type=""text"" name=""examBeginTime"" value="""" id=""txt_examBeginTime"" onclick="" WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm', maxDate: '#F{$dp.$D(\'txt_examEndTime\')}' }) "" />
                        <i></i>
                    </div>
                    至
                    <div class=""time-choose"">
                        <input type=""text"" name=""examEndTime"" onclick="" WdatePicker({ dateFmt: 'yyyy-MM-dd HH:mm', minDate: '#F{$dp.$D(\'txt_examBeginTime\')}' }) "" value="""" id=""txt_examEndTime"" />
                        <i></i>
                    </div>
                    ");



WriteLiteral("\r\n                    ");



WriteLiteral("\r\n                </td>\r\n                <td class=\"so-do\"><input type=\"button\" c" +
"lass=\"btn\" value=\"搜索\" onclick=\" searchExamList() \" /></td>\r\n            </tr>\r\n " +
"       </table>\r\n        ");



WriteLiteral(@"
    </div>
    <div id=""Content"">
        <table class=""tab-List mt10"">
            <thead>
                <tr>
                    <th>
                        考试名称
                    </th>
                    <th class=""span15"">
                        起止时间
                    </th>
                    <th class=""span9"">
                        操作
                    </th>
                </tr>
            </thead>
            <tbody id=""examList"">
            </tbody>
            <tfoot>
            </tfoot>
        </table>
        ");



WriteLiteral(@"
    </div>
</div>
<script id=""examListTemplate"" type=""text/x-jsRender"">
 {{for #data}}
    <tr>
        <td>
            <p title=""{{:ExaminationTitle}}""><strong>{{:ExaminationTitle.length>20?(ExaminationTitle.substring(0,20)+""…""):ExaminationTitle}}</strong></p>
            <p class=""Info"">时长: {{:ExamLength}}<span>|</span>总分: {{:examTotalScore}}<span>|</span>及格线: {{:PassScore}}</p>
        </td>
        <td>{{:ExamBeginTime}} -<br/>{{:ExamEndTime}}</td>
        <td>
            <a {{:ReEvaluationHtml}} title=""复评"" class=""icon ieva-re""></a>
            <a {{:PublishResultHtml}} title=""发布成绩"" class=""icon ipub""></a>
        </td>
    </tr>
    {{/for}}
</script>
");



WriteLiteral("\r\n<script type=\"text/javascript\">\r\n\r\n    $(document).ready(function() {\r\n\r\n      " +
"  InitExamList();\r\n    });\r\n\r\n    function changeView(str) {\r\n        ChangeList" +
"({ str: str, fun: function() { InitExamList(); } });\r\n    }\r\n\r\n    function sear" +
"chExamList() {\r\n        InitExamList();\r\n    }\r\n\r\n    function getUrlParms() {\r\n" +
"        return \"/Examination/GetReEvaluationList?examBeginTimeStart=\" + $(\"#txt_" +
"examBeginTime\").val() + \"&examBeginTimeEnd=\" + $(\"#txt_examEndTime\").val() + \"&e" +
"xaminationTitle=\" + escape($.trim(getSearchWord($(\"#txt_examTitle\").val())));\r\n " +
"   }\r\n\r\n    function InitExamList() {\r\n        var templateId = \'\';\r\n        // " +
"       if ($(\".listOn\").length > 0) {\r\n        //            $(\"#examList\").addC" +
"lass(\"Wordlist\").removeClass(\"Piclist\");\r\n        //            templateId = \'ex" +
"amListTemplate\';\r\n        //        } else {\r\n        //            $(\"#examList" +
"\").addClass(\"Piclist\").removeClass(\"Wordlist\");\r\n        //            templateI" +
"d = \'examBlockTemplate\';\r\n        //        }\r\n        $(\"#examList\").JsRenderDa" +
"ta({\r\n            sourceUrl: getUrlParms(),\r\n            isPage: true,\r\n        " +
"    pageSize: 10,\r\n            pageIndex: 1,\r\n            templateID: \'examListT" +
"emplate\'\r\n            //            templateID: templateId\r\n        });\r\n    }\r\n" +
"\r\n\r\n    function ReEvaluationExam(id) {\r\n        window.location.href = \'/Examin" +
"ation/ReEvaluation/\' + id;\r\n    }\r\n\r\n    function PublishResultExam(id) {\r\n     " +
"   $.post(\"/Examination/PublishExamResult/\" + id, function (data) {\r\n           " +
" //art.dialog({ title: \'");


            
            #line 146 "..\..\Views\Examination\ReEvaluationList.cshtml"
                              Write(CommonLanguage.Common_Tip);

            
            #line default
            #line hidden
WriteLiteral("\', content: data.content, width: 200, height: 50, fixed: true, lock: true, time: " +
"3 });\r\n            art.dialog.tips(data.content, 3);\r\n            searchExamLi" +
"st();\r\n        });\r\n    }\r\n</script>");


        }
    }
}
#pragma warning restore 1591
