#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.Question
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Question\ImportQuestions.cshtml"
    using LiXinLanguage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Question/ImportQuestions.cshtml")]
    public class ImportQuestions : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ImportQuestions()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Question\ImportQuestions.cshtml"
  
    Layout = null;
    string sortID = Request.QueryString["id"];


            
            #line default
            #line hidden
WriteLiteral(@"<div class=""centerbody"">
    <form id=""formQuestion"" method=""post"" enctype=""multipart/form-data"" action="""">
    <div class=""ma"">
        <table class=""tab-Form"">
            <tr>
                <td class=""Tit span8"">
                    <span class=""red"">*</span>知识点：
                </td>
                <td>
                    <select id=""keylist"" class=""sel span20"">
                    </select>
                </td>
            </tr>
            <tr>
                <td class=""Tit"">
                    <span class=""red"">*</span>");


            
            #line 21 "..\..\Views\Question\ImportQuestions.cshtml"
                                         Write(Question.Question_QuestionManage_Sort);

            
            #line default
            #line hidden
WriteLiteral("：\r\n                </td>\r\n                <td>\r\n                    <input id=\"se" +
"lQuestionSort\" name=\"selQuestionSort\" type=\"hidden\" value=\"");


            
            #line 24 "..\..\Views\Question\ImportQuestions.cshtml"
                                                                                       Write(sortID);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                    <input id=\"sortName\" type=\"text\" readonly=\"readonly\" cla" +
"ss=\"span20\" disabled=\"disabled\" value=\"");


            
            #line 25 "..\..\Views\Question\ImportQuestions.cshtml"
                                                                                                              Write(ViewData["fatherModel"]);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n               " +
" <td class=\"Tit\">\r\n                    <span class=\"red\">*</span>");


            
            #line 30 "..\..\Views\Question\ImportQuestions.cshtml"
                                         Write(Question.Question_QuestionManage_QuestionTemplete);

            
            #line default
            #line hidden
WriteLiteral(@"：
                </td>
                <td>
                    <input type=""file"" id=""questionExcel"" name=""questionExcel"" class=""Raster_20"" />
                </td>
            </tr>
            <tr>
                <td colspan=""2"" class=""tc"">
                    <a id=""submitExcel"" class=""btn"" flag=""0"">");


            
            #line 38 "..\..\Views\Question\ImportQuestions.cshtml"
                                                        Write(CommonLanguage.Common_Save);

            
            #line default
            #line hidden
WriteLiteral(@"</a>
                </td>
            </tr>
        </table>
    </div>
    </form>
</div>
<script type=""text/javascript"">
    $(""#submitExcel"").bind(""click"", function ()
    {
        if ($(this).attr(""flag"") == ""0"")
        {

            if ($(""#questionExcel"").val() == """")
            {
                art.dialog.tips(""请选择试题模板"", 3);
                return;
            }
            $(this).attr(""flag"", ""1"");
            $(this).text(""导入中…"");
            $(""#formQuestion"").submitForm({
                url: '/Question/SubmitImportQuestion?sortID=");


            
            #line 59 "..\..\Views\Question\ImportQuestions.cshtml"
                                                       Write(sortID);

            
            #line default
            #line hidden
WriteLiteral(@"&key=' + $(""#keylist"").val(),
                callback: function (data)
                {
                    if (data.result == 1)
                    {
                        art.dialog.tips(data.content, 3);
                        //初始化问题
                        InitlQUestion();
                        art.dialog.list['ImportQue'].close();
                    } else
                    {
                        $(""#submitExcel"").attr(""flag"", ""0"");
                        $(""#submitExcel"").text(""保存"");
                        art.dialog.tips(data.content, 3);
                        $(this).attr(""flag"", ""0"").text(""");


            
            #line 73 "..\..\Views\Question\ImportQuestions.cshtml"
                                                   Write(CommonLanguage.Common_Save);

            
            #line default
            #line hidden
WriteLiteral(@""");

                    }
                }
            }).submit();
        }
    });

    $.getJSON(""/KnowledgeKey/GetKnowledgeKey?t="" + new Date(), function (data)
    {
        var html = """";
        for (var i = 0; i < data.length; i++)
        {
            html += '<option value=""' + data[i].id + '"">' + data[i].name + '</option>';
        }
        $(""#keylist"").append(html);
        $(""#hiddenSelQuestionKey"").val($(""#keylist"").val());
        $(""#keylist"").bind(""change"", function ()
        {
            $(""#hiddenSelQuestionKey"").val($(""#keylist"").val());
        });
    });

    function cancel()
    {
        //初始化问题
        InitlQUestion();
        art.dialog.list['ImportQue'].close();
    }

</script>
");


        }
    }
}
#pragma warning restore 1591
