#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.ExamReport
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\ExamReport\GradeRank.cshtml"
    using LiXinModels.User;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ExamReport/GradeRank.cshtml")]
    public class GradeRank : System.Web.Mvc.WebViewPage<dynamic>
    {
        public GradeRank()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\ExamReport\GradeRank.cshtml"
  
    ViewBag.Title = "成绩与排名统计";
    var postlist = (List<Sys_Post>)ViewData["listPost"];
    var deptlist = (List<Sys_Department>)ViewData["listDept"];
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    <!--查询条件-->\r\n    <div class=\"search_box\">\r\n        <div class=\"clb\">\r\n" +
"            <input id=\"btnSearchGrade\" type=\"button\" value=\"查询\" onclick=\" InitTa" +
"ble() \" class=\"Btn Btn_blue\" />\r\n            <p>\r\n                <label>\r\n     " +
"               考试名称:\r\n                </label>\r\n                <input id=\"txtex" +
"amname\" class=\"Box Raster_16\" type=\"text\" />\r\n                <label>\r\n         " +
"           岗位:\r\n                </label>\r\n                <input id=\"txtpostcode" +
"\" class=\"Box Raster_16\" type=\"text\" />\r\n            </p>\r\n            <p>\r\n     " +
"           <label>\r\n                    部门:\r\n                </label>\r\n         " +
"       <input id=\"txtdeptcode\" class=\"Box Raster_16\" type=\"text\" />\r\n           " +
"     <label>\r\n                    工号:\r\n                </label>\r\n               " +
" <input id=\"jobnum\" type=\"text\" class=\"Box Raster_6\" />\r\n                <label>" +
"\r\n                    姓名:\r\n                </label>\r\n                <input id=\"" +
"realname\" type=\"text\" class=\"Box Raster_6\" />\r\n                <label>\r\n        " +
"            是否通过:\r\n                </label>\r\n                <select id=\"isPass\"" +
" class=\"sel\">\r\n                    <option value=\"-1\">显示全部</option>\r\n           " +
"         <option value=\"1\">是</option>\r\n                    <option value=\"0\">否</" +
"option>\r\n                </select></p>\r\n        </div>\r\n    </div>\r\n    <!--数据列表" +
"-->\r\n    <div class=\"mTop_1 btop_so_ce\">\r\n        <table class=\"blue_table all\">" +
"\r\n            <thead>\r\n                <tr>\r\n                    <th class=\"w100" +
"\">\r\n                        考试名称\r\n                    </th>\r\n                   " +
" <th>\r\n                        姓名(工号)\r\n                    </th>\r\n              " +
"      <th>\r\n                        部门&岗位\r\n                    </th>\r\n          " +
"          <th>\r\n                        得分\r\n                    </th>\r\n         " +
"           <th>\r\n                        已答题数\r\n                    </th>\r\n      " +
"              <th>\r\n                        未答题数\r\n                    </th>\r\n   " +
"                 <th>\r\n                        <p>\r\n                            " +
"正确率</p>\r\n                        <p>\r\n                            (答对/总题数)</p>\r\n" +
"                    </th>\r\n                    <th>\r\n                        <p>" +
"\r\n                            错误率</p>\r\n                        <p>\r\n            " +
"                (答错/总题数)</p>\r\n                    </th>\r\n                    <th" +
">\r\n                        是否通过\r\n                    </th>\r\n                    " +
"<th>\r\n                        排名\r\n                    </th>\r\n                </t" +
"r>\r\n            </thead>\r\n            <tbody id=\"gradeRank\">\r\n            </tbod" +
"y>\r\n            <tfoot>\r\n            </tfoot>\r\n        </table>\r\n    </div>\r\n</d" +
"iv>\r\n<script id=\"rankTemplate\" type=\"text/x-jsrender\">\r\n    {{for #data}}\r\n    <" +
"tr>\r\n        <td title=\"{{:examinationTitle}}\" class=\"tc c33\"><strong>{{:examina" +
"tionTitle}}</strong></td>\r\n        <td class=\"w120 tc\">\r\n            <p title=\"{" +
"{:realname}}\">{{:realname}}</p>\r\n            <p title=\"{{:jobnum}}\">{{:jobnum}}<" +
"/p>\r\n        </td>\r\n        <td class=\"w120 tc\">\r\n            <p title=\"{{:deptc" +
"ode}}\">{{:deptcode.length>8?deptcode.substring(0,8)+\"......\":deptcode}}</p>\r\n   " +
"         <p title=\"{{:postcode}}\" class=\"c_green\">{{:postcode.length>8?postcode." +
"substring(0,8)+\"......\":postcode}}</p>\r\n        </td>  \r\n        <td title=\"{{:G" +
"etScore}}\" class=\"c_green f14\"><strong>{{:GetScore}}</strong></td>\r\n        \r\n  " +
"      <td title=\"{{:hasAnswerNumber}}\">{{:hasAnswerNumber}}</td>\r\n        <td ti" +
"tle=\"{{:NotAnswerNumber}}\">{{:NotAnswerNumber}}</td>\r\n        <td title=\"{{:Corr" +
"ectRate+\"%\"}}\" class=\"tr\">\r\n            <p class=\"c_green f14\"><strong>{{:Correc" +
"tRate+\"%\"}}</strong></p>\r\n            <p>( {{:CorrectAnswerNumber}}/{{:(hasAnswe" +
"rNumber+NotAnswerNumber)}} )</p>\r\n        </td>\r\n        <td title=\"{{:WrongRate" +
"+\"%\"}}\" class=\"tr\">\r\n            <p class=\"f14\"><strong>{{:WrongRate+\"%\"}}</stro" +
"ng></p>\r\n            <p>( {{:WrongAnswerNumber}}/{{:(hasAnswerNumber+NotAnswerNu" +
"mber)}} )</p>\r\n        </td>\r\n        <td title=\"{{:passState}}\" class=\"tc\">{{:p" +
"assState}}</td>\r\n        <td title=\"{{:Rank}}\" class=\"tc\">{{:Rank}}</td>\r\n    </" +
"tr>\r\n    {{/for}}\r\n</script>\r\n<script type=\"text/javascript\">\r\n\r\n    $(document)" +
".ready(function () {\r\n        InitTable();\r\n\r\n        //下拉框事件\r\n        $(\"#isPas" +
"s\").bind(\"change\", function () {\r\n            InitTable();\r\n        });\r\n    });" +
"\r\n\r\n    function InitTable()\r\n    {\r\n        $(\"#gradeRank\").JsRenderData({\r\n   " +
"         sourceUrl: getUrl(),\r\n            isPage: true,\r\n            pageSize: " +
"20,\r\n            pageIndex: 1,\r\n            templateID: \'rankTemplate\'\r\n        " +
"});\r\n    }\r\n\r\n    function getUrl()\r\n    {\r\n        return \"/ExamReport/GetGrade" +
"Rank?examname=\" + escape($(\"#txtexamname\").val()) +\r\n            \"&deptcode=\" + " +
"escape($(\"#txtdeptcode\").val()) + \"&postcode=\" +\r\n            escape($(\"#txtpost" +
"code\").val()) + \"&jobnum=\" + $(\"#jobnum\").val()\r\n            + \"&realname=\" + es" +
"cape($(\"#realname\").val()) + \"&isPass=\" + $(\"#isPass\").val()\r\n            + \"&st" +
"artDate=\" + $(\"#startDate\").val() + \"&endDate=\" + $(\"#endDate\").val();\r\n    }\r\n\r" +
"\n    //导出\r\n\r\n    function ExportReportChart()\r\n    {\r\n        window.location.hr" +
"ef = \"/ExamReport/ExportGrandRank?examname=\" + escape($(\"#txtexamname\").val()) +" +
"\r\n            \"&deptcode=\" + escape($(\"#txtdeptcode\").val()) + \"&postcode=\" +\r\n " +
"           escape($(\"#txtpostcode\").val()) + \"&jobnum=\" + $(\"#jobnum\").val()\r\n  " +
"          + \"&realname=\" + escape($(\"#realname\").val()) + \"&isPass=\" + $(\"#isPas" +
"s\").val()\r\n            + \"&startDate=\" + $(\"#startDate\").val() + \"&endDate=\" + $" +
"(\"#endDate\").val()\r\n            + \"&t=\" + new Date();\r\n\r\n    }\r\n\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
