#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.544
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiXinExam.Views.ExamReport
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ExamReport/ReportIndex.cshtml")]
    public class ReportIndex : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ReportIndex()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\ExamReport\ReportIndex.cshtml"
  
    ViewBag.Title = "考试评估";
    Layout = "~/Views/Shared/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("<div id=\"contentInfor\" class=\"main-c\">\r\n    ");


            
            #line 6 "..\..\Views\ExamReport\ReportIndex.cshtml"
Write(Html.Action("SiteMapLink", "Common", new
          {
              linkName = "TestingAssessment"
          }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--上半部分-->\r\n    <div class=\"tab-bk\">\r\n        <ul class=\"clb\" id=\"tabmenu\"" +
">\r\n            <li onclick=\" Search(1); $(\'#tabmenu li\').removeClass(\'On\'); $(th" +
"is).addClass(\'On\');\">最近一个月</li>\r\n            <li onclick=\" Search(2); $(\'#tabmen" +
"u li\').removeClass(\'On\'); $(this).addClass(\'On\'); \">最近一季度</li>\r\n            <li " +
"onclick=\" Search(3); $(\'#tabmenu li\').removeClass(\'On\'); $(this).addClass(\'On\');" +
"\">最近半年</li>\r\n            <li class=\"On\" onclick=\"Showinfo();$(\'#tabmenu li\').rem" +
"oveClass(\'On\'); $(this).addClass(\'On\');Search(4);\">更多查询</li>\r\n        </ul>\r\n   " +
"     <p class=\"fr mTop_05 mRight_1\">\r\n            <input type=\"button\" class=\"bt" +
"n btn-co\" onclick=\" ExportReportChart() \" value=\"导出\" /></p>\r\n        <div class=" +
"\"\" id=\"show\">\r\n            <input id=\"btnSearch\" type=\"button\" value=\"查询\" onclic" +
"k=\" Search(4) \" class=\"Btn Btn_blue\" />\r\n            <label>\r\n                结束" +
"时间:\r\n            </label>\r\n            <div class=\"data-choose\"><input type=\"tex" +
"t\" id=\"txtStartTime\" onclick=\" WdatePicker({ el: \'txtStartTime\' }); \" value=\"\" /" +
"><i></i></div>\r\n            至\r\n            <div class=\"data-choose\"><input type=" +
"\"text\" id=\"txtEndTime\" onclick=\" WdatePicker({ el: \'txtEndTime\' }); \" value=\"\" /" +
"><i></i></div>\r\n        </div>\r\n    </div>\r\n    <!--下半部分-->\r\n    <div class=\"clb" +
" mTop_1\">\r\n        <!--左边的菜单-->\r\n        <div class=\"fl Raster_21 box_white\">\r\n " +
"           <div class=\"box_w_title\">\r\n                <h1>\r\n                    " +
"考试总体分析</h1>\r\n            </div>\r\n            <ul class=\"sort_tree\">\r\n           " +
"     <li><a onclick=\" MenuClick(1) \">参与及通过情况统计</a></li>\r\n                <li><a " +
"onclick=\" MenuClick(2) \">题型正确率统计</a> </li>\r\n                <li><a onclick=\" Men" +
"uClick(3) \">题库正确率统计</a> </li>\r\n                <li><a onclick=\" MenuClick(4) \">成" +
"绩分布统计</a> </li>\r\n            </ul>\r\n            <div class=\"box_w_title\">\r\n     " +
"           <h1>\r\n                    考试情况分析</h1>\r\n            </div>\r\n          " +
"  <ul class=\"sort_tree\">\r\n                <li><a onclick=\" MenuClick(5) \">成绩与排名统" +
"计</a></li>\r\n                ");



WriteLiteral("\r\n            </ul>\r\n        </div>\r\n        <!--右边的内容边的菜单-->\r\n        <div id=\"c" +
"ontent\" class=\"fr Raster_78\">\r\n        </div>\r\n        <input id=\"Menutype\" type" +
"=\"hidden\" />\r\n        <input id=\"startDate\" type=\"hidden\" />\r\n        <input id=" +
"\"endDate\" type=\"hidden\" />\r\n        <input id=\"examName\" type=\"hidden\" value=\"\" " +
"/>\r\n    </div>\r\n</div>\r\n<script type=\"text/javascript\">\r\n    $(document).ready(f" +
"unction ()\r\n    {\r\n        MenuClick(1);\r\n    });\r\n\r\n    function Showinfo()\r\n  " +
"  {\r\n        $(\"#txtStartTime\").val(\"\");\r\n        $(\"#txtEndTime\").val(\"\");\r\n   " +
"     if ($(\"#show\").hasClass(\'dis\'))\r\n        {\r\n            $(\"#show\").removeCl" +
"ass(\'dis\');\r\n            $(\".tab_menu\").addClass(\'mBot_5\');\r\n        } else\r\n   " +
"     {\r\n\r\n            $(\"#show\").addClass(\'dis\');\r\n            $(\".tab_menu\").re" +
"moveClass(\'mBot_5\');\r\n        }\r\n\r\n\r\n    }\r\n\r\n\r\n    //点击菜单\r\n\r\n    function MenuC" +
"lick(type)\r\n    {\r\n        //Showinfo();\r\n        $(\"#Menutype\").val(type);\r\n   " +
"     Menu();\r\n    }\r\n\r\n    //点击查询条件\r\n\r\n    function Search(type)\r\n    {\r\n       " +
" start = $(\"#txtStartTime\").val();\r\n        end = $(\"#txtEndTime\").val();\r\n     " +
"   if (start > end)\r\n        {\r\n            art.dialog.tips(\'请输入正确的时间范围\', 1.5);\r" +
"\n            return;\r\n        }\r\n        DateChange(type);\r\n        InitTable();" +
"\r\n    }\r\n\r\n    //加载不同的内容\r\n\r\n    function Menu()\r\n    {\r\n        //var query = \"s" +
"tartDate=\" + $(\"#startDate\").val() + \"&endDate=\" + $(\"#endDate\").val() + \"&examN" +
"ame=\" + $(\"#examName\").val();\r\n        switch ($(\"#Menutype\").val())\r\n        {\r" +
"\n            //参与及通过情况统计                                                        " +
"    \r\n            case \"1\":\r\n                $(\"#content\").load(\"JoinAndPassExam" +
"?t=\" + (new Date()).valueOf());\r\n                break;\r\n            //题型正确率统计  " +
"                                                          \r\n            case \"2\"" +
":\r\n                $(\"#content\").load(\"QuestionCorrectReport?t=\" + (new Date())." +
"valueOf());\r\n                break;\r\n            //题库正确率统计                      " +
"                                      \r\n            case \"3\":\r\n                $" +
"(\"#content\").load(\"QuestionSortCorrectReport?t=\" + (new Date()).valueOf());\r\n   " +
"             break;\r\n            //成绩分布统计   \r\n            case \"4\":\r\n           " +
"     $(\"#content\").load(\"ExaminationRecordsDistributionReport?t=\" + (new Date())" +
".valueOf());\r\n                break;\r\n            //成绩与排名统计   \r\n            case" +
" \"5\":\r\n                $(\"#content\").load(\"/ExamReport/GradeRank\");\r\n           " +
"     break;\r\n            //答卷情况统计                                               " +
"             \r\n            case \"6\":\r\n                $(\"#content\").load();\r\n   " +
"             break;\r\n        }\r\n    }\r\n\r\n    //时间的获取\r\n\r\n    function DateChange(" +
"DateType)\r\n    {\r\n\r\n        var now = new Date();\r\n\r\n        var month = now.get" +
"Month();\r\n\r\n        var year = now.getFullYear();\r\n\r\n        var day = now.getDa" +
"te();\r\n\r\n        var start;\r\n\r\n        var end = new Date(year, month, day).Form" +
"at(\"yyyy-MM-dd\");\r\n\r\n        var examName = \"\";\r\n        switch (DateType)\r\n    " +
"    {\r\n            //最近一个月   \r\n            case 1:\r\n                start = new " +
"Date(year, month, 1).Format(\"yyyy-MM-dd\");\r\n                break;\r\n            " +
"//最近一季度                                                          \r\n            c" +
"ase 2:\r\n                start = new Date(year, getQuarterStartMonth(month), 1).F" +
"ormat(\"yyyy-MM-dd\");\r\n                break;\r\n            //最近半年                " +
"                                         \r\n            case 3:\r\n                " +
"start = new Date(year, getYearStartMonth(month), 1).Format(\"yyyy-MM-dd\");\r\n     " +
"           break;\r\n            case 4:\r\n                start = $(\"#txtStartTime" +
"\").val();\r\n                end = $(\"#txtEndTime\").val();\r\n                // exa" +
"mName = $(\"#txtExamName\").val();\r\n                break;\r\n        }\r\n\r\n        $" +
"(\"#startDate\").val(start);\r\n        $(\"#endDate\").val(end);\r\n\r\n        if (DateT" +
"ype == 1 || DateType == 2 || DateType == 3)\r\n        {\r\n            if (!$(\"#sho" +
"w\").hasClass(\'dis\'))\r\n            {\r\n                $(\"#show\").addClass(\'dis\');" +
"\r\n                $(\".tab_menu\").removeClass(\'mBot_5\');\r\n            }\r\n        " +
"}\r\n    }\r\n\r\n    //获得本季度的开始月份     \r\n\r\n    function getQuarterStartMonth(nowMonth)" +
"\r\n    {\r\n        var quarterStartMonth = 0;\r\n        if (nowMonth < 3)\r\n        " +
"{\r\n            quarterStartMonth = 0;\r\n        }\r\n        if (2 < nowMonth && no" +
"wMonth < 6)\r\n        {\r\n            quarterStartMonth = 3;\r\n        }\r\n        i" +
"f (5 < nowMonth && nowMonth < 9)\r\n        {\r\n            quarterStartMonth = 6;\r" +
"\n        }\r\n        if (nowMonth > 8)\r\n        {\r\n            quarterStartMonth " +
"= 9;\r\n        }\r\n        return quarterStartMonth;\r\n    }\r\n\r\n    //获得半年的开始月份\r\n\r\n" +
"    function getYearStartMonth(nowMonth)\r\n    {\r\n        var yearStartMonth = 0;" +
"\r\n        if (5 < nowMonth)\r\n        {\r\n            yearStartMonth = 6;\r\n       " +
" } else\r\n        {\r\n            yearStartMonth = 0;\r\n        }\r\n        return y" +
"earStartMonth;\r\n    }\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
